/* Connected local RP assets. Atomic inventory/storage/crafting operations. */
(() => {
'use strict';
globalThis.CyberpunkAssetsFactory=api=>{
 const C=globalThis.CyberpunkRpgCore,E=api.htmlEscape,tr=(a,b)=>api.settings().language==='th'?b:a,copy=v=>JSON.parse(JSON.stringify(v));
 const recipes=[{id:'medkit',name:'Field medkit',components:3,cost:50,item:{name:'Field medkit',category:'consumable',effect:'Local workshop recovery supply',power:25}},{id:'ping',name:'Ping',components:5,cost:150,item:{name:'Ping',category:'quickhack',ramCost:2,cooldown:1,effect:'Reveal connected devices in the established scene'}},{id:'short-circuit',name:'Short Circuit',components:8,cost:250,item:{name:'Short Circuit',category:'quickhack',ramCost:3,cooldown:2,effect:'Disrupt a targeted electronic system'}}];
 const state=()=>api.state(),find=(kind,id)=>{const x=(kind==='property'?state().properties:state().vehicles).find(x=>x.id===id&&x.status!=='sold');if(!x)throw Error('Owned asset required');return x;};
 const save=()=>{api.saveChat();api.refreshPrompt();};
 const capacity=(kind,x)=>kind==='property'?20+20*(x.upgrades?.stash||0):4+4*(x.upgrades?.cargo||0);
 function transact(kind,id,operation,input={}){
   const s=state();if(s.bd.status!=='stopped'||s.bd.rendering)throw Error('Exit Braindance first');
   const original=find(kind,id),asset=copy(original),player=copy(s.player);asset.storage??=[];asset.upgrades??={};asset.serviceLog??=[];
   let costPaid=0;const charge=n=>{n=C.money(n);if(player.balance<n)throw Error('Insufficient balance');player.balance-=n;costPaid+=n;if(n)player.ledger.push({id:C.uid(),delta:-n,reason:operation+': '+asset.name,at:new Date().toISOString()});};
   const consume=(count)=>{const list=player.inventory.filter(i=>i.category==='component'&&!i.equipped);if(list.reduce((n,i)=>n+i.quantity,0)<count)throw Error('Not enough components in carried inventory');for(const i of list){const take=Math.min(count,i.quantity);i.quantity-=take;count-=take;}player.inventory=player.inventory.filter(i=>i.quantity>0);};
   if(operation==='deposit'||operation==='withdraw'){
     const quantity=Number(input.quantity),deposit=operation==='deposit',source=deposit?player.inventory:asset.storage,target=deposit?asset.storage:player.inventory,it=source.find(i=>i.id===input.itemId);
     if(!it||!Number.isInteger(quantity)||quantity<1||quantity>it.quantity)throw Error('Invalid item quantity');if(deposit&&it.equipped)throw Error('Unequip or unload this item before storing');
     let id=deposit?'stored:'+asset.id+':'+(it.originId||it.id):it.originId||it.id;
     const signature=i=>JSON.stringify(Object.entries(i).filter(([k,v])=>v!==undefined&&!['id','originId','quantity','equipped'].includes(k)).sort(([a],[b])=>a.localeCompare(b)));
     let old=target.find(i=>i.id===id);if(old&&signature(old)!==signature(it)){id=C.uid();old=null;}if(old&&old.quantity+quantity>9999)throw Error('Stack quantity limit reached');if(deposit&&!old&&target.length>=capacity(kind,asset))throw Error('Storage is full; upgrade capacity');
     if(old)old.quantity+=quantity;else target.push({...copy(it),id,originId:deposit?(it.originId||it.id):undefined,quantity,equipped:false});it.quantity-=quantity;if(deposit)player.inventory=source.filter(i=>i.quantity>0);else asset.storage=source.filter(i=>i.quantity>0);C.syncDeck(player);
   }else if(operation==='craft'||operation==='upgrade-item'){
     if(kind!=='property'||(asset.upgrades.workshop||0)<1)throw Error('Upgrade this home workshop to level 1 first');
     if(operation==='craft'){const recipe=recipes.find(r=>r.id===input.recipe);if(!recipe)throw Error('Recipe not found');consume(recipe.components);charge(recipe.cost);player.inventory.push(C.item({...recipe.item,id:C.uid(),quantity:1}));}
     else{const it=player.inventory.find(i=>i.id===input.itemId&&['quickhack','weapons'].includes(i.category));if(!it)throw Error('Owned weapon or quickhack required');const level=Number(it.level||1),limit=Math.min(60,asset.upgrades.workshop*10);if(level>=limit)throw Error('Workshop level limit reached');consume(2+Math.floor(level/5));charge(100*level);it.level=level+1;if(it.category==='weapons')it.power=Math.min(100,Number(it.power||0)+1);}
   }else if(operation==='rest'){
     const level=asset.upgrades.living||0;if(kind!=='property'||level<1)throw Error('Upgrade Living to level 1 first');if(s.map.location.building!==asset.name||!asset.lastVisited)throw Error('Enter this home from Actions first');if(s.lastHomeRestTurn===s.turn)throw Error('Rest already used this story turn');if(player.hp===player.maxHp&&player.stamina===player.maxStamina&&player.ram===player.maxRam&&player.stress===0)throw Error('Already fully rested');player.hp=Math.min(player.maxHp,player.hp+10*level);player.stamina=Math.min(player.maxStamina,player.stamina+20*level);player.ram=Math.min(player.maxRam,player.ram+level);player.stress=Math.max(0,player.stress-5*level);
   }else if(operation==='vehicle-upgrade'){
     if(kind==='property'||!['cargo','armor','engine'].includes(input.area))throw Error('Choose cargo, armor or engine');const level=asset.upgrades[input.area]||0;if(level>=5)throw Error('Maximum upgrade reached');charge(1000*(level+1));asset.upgrades[input.area]=level+1;
   }else if(operation==='refuel'){if(kind==='property')throw Error('Vehicle required');const missing=100-(asset.fuel??100);if(missing<=0)throw Error('Fuel is already full');charge(missing*2);asset.fuel=100;}
   else if(operation==='trip'){
     if(kind==='property'||s.activeVehicle!==id||(asset.condition??100)<=0)throw Error('Summon a working vehicle first');const km=Number(input.distance);if(!Number.isFinite(km)||km<=0||km>1000)throw Error('Distance must be 0–1000 km');const cost=Math.ceil(km/(5+(asset.upgrades.engine||0))),wear=Math.ceil(km/(20+5*(asset.upgrades.armor||0)));if((asset.fuel??100)<cost)throw Error('Refuel before travelling');asset.fuel=(asset.fuel??100)-cost;asset.condition=Math.max(0,(asset.condition??100)-wear);asset.odometer=Math.round(((asset.odometer||0)+km)*10)/10;if(asset.condition===0)asset.status='destroyed';
   }else if(operation==='assign-garage'){
     if(kind==='property')throw Error('Vehicle required');if(input.homeId){const home=find('property',input.homeId),count=s.vehicles.filter(v=>v.id!==id&&v.status!=='sold'&&v.garageId===home.id).length;if(count>=1+(home.upgrades?.garage||0))throw Error('Home garage full; upgrade garage');}asset.garageId=input.homeId||'';
   }else if(operation==='details'){
     asset.description=C.text(input.description,4000);asset.notes=C.text(input.notes,4000);asset.nickname=C.text(input.nickname,100);
   }else throw Error('Unsupported asset action');
   const detail=C.text((input.area||input.recipe||input.itemId||input.distance||'')+(input.quantity?' ×'+input.quantity:'')+(costPaid?' · €$'+costPaid:''),240);asset.serviceLog.push({at:Date.now(),operation,detail,cost:costPaid});asset.serviceLog=asset.serviceLog.slice(-100);player.ledger=player.ledger.slice(-300);
   Object.assign(s.player,player);Object.assign(original,asset);if(operation==='rest')s.lastHomeRestTurn=s.turn;if(asset.status==='destroyed'&&s.activeVehicle===id)s.activeVehicle=null;api.event?.('asset service',operation+': '+asset.name+' · '+detail+'. State, materials and any price already applied; do not charge or grant them again.');save();return asset;
 }
 function markup(kind){const s=state(),homes=kind==='property',list=homes?s.properties:s.vehicles,owned=list.filter(x=>x.status!=='sold');return `<header class="cps-asset-hero"><div><small>${homes?'RESIDENTIAL NETWORK':'MOTOR POOL / TELEMETRY'}</small><h2>${E(tr(homes?'Your corner of Night City':'Your garage, connected',homes?'พื้นที่ของคุณในไนท์ซิตี้':'โรงรถที่เชื่อมกับเรื่องราว'))}</h2><p>${E(tr(homes?'Storage. Workshop. A place to return to.':'Condition, cargo, upgrades and a service history.',homes?'คลังของ เวิร์กช็อป และสถานที่กลับมาพัก':'สภาพรถ สัมภาระ อัปเกรด และประวัติบริการ'))}</p></div><strong>${String(owned.length).padStart(2,'0')}<small>OWNED</small></strong></header><div class="cps-rpg-actions">${api.buttons(tr(homes?'Buy property':'Buy vehicle',homes?'ซื้อบ้าน':'ซื้อรถ'),'asset-buy:'+kind)}</div><p class="cps-rpg-note">${E(tr('Costs and capacities are explicit local RP rules, not game-engine physics or live game prices.','ราคา ความจุ และผลอัปเกรดเป็นกติกา RP ของ extension ไม่ใช่ฟิสิกส์หรือราคาสดจากเกม'))}</p><div class="cps-asset-grid">${list.map(x=>`<article class="cps-asset-card ${x.status==='sold'?'sold':''}"><div class="cps-asset-schematic ${homes?'home':'car'}" aria-hidden="true"><svg viewBox="0 0 240 100">${homes?'<path d="M25 85V28L120 8l95 20v57H25m15-10h160M80 85V35h80v50M90 48h12m10 0h12m10 0h12M45 42h18m112 0h18"/>':'<path d="m18 65 10-23 50-6 26-20h65l25 26 29 9v23H18zm60-29h102M104 16l-8 20m64-20 12 20M60 75a14 14 0 1 0 0 .1M185 75a14 14 0 1 0 0 .1"/>'}</svg><span>${E(x.status||'owned')}</span></div><small>${E(x.location||'NIGHT CITY')}</small><h3>${E(x.nickname||x.name)}</h3><p>${E(x.name)}</p><div class="cps-asset-metrics"><span>${homes?'STASH':'CONDITION'}<b>${homes?(x.storage?.length||0)+' / '+capacity(kind,x):(x.condition??100)+'%'}</b></span><span>${homes?'WORKSHOP':'FUEL'}<b>${homes?'LV.'+(x.upgrades?.workshop||0):(x.fuel??100)+'%'}</b></span><span>${homes?'GARAGE':'ODOMETER'}<b>${homes?s.vehicles.filter(v=>v.status!=='sold'&&v.garageId===x.id).length+' / '+(1+(x.upgrades?.garage||0)):(x.odometer||0)+' km'}</b></span></div><div class="cps-rpg-actions">${api.buttons(tr('Open dossier','เปิดรายละเอียด'),'asset-detail:'+kind+':'+x.id,x.status==='sold'?'disabled':'')}${api.buttons(tr('Actions','จัดการ'),'asset-op:'+kind+':'+x.id,x.status==='sold'?'disabled':'')}</div></article>`).join('')||'<div class="cps-asset-empty">NO REGISTERED ASSETS / ยังไม่มีทรัพย์สิน</div>'}</div>`;}
 function open(kind,id){const owner=api.chatBucket(),x=find(kind,id),homes=kind==='property',d=api.dialog(x.name,'<div class="cps-asset-dossier"></div>','cps-asset-window'),host=d.querySelector('.cps-asset-dossier');let page='overview';
   const btn=(key,label,extra='')=>`<button type="button" class="cps-button" data-asset="${E(key)}" ${extra}>${E(label)}</button>`;
   const draw=()=>{if(owner!==api.chatBucket()||!d.isConnected)return;const a=find(kind,id),s=state(),items=s.player.inventory,storage=a.storage||[];
     host.innerHTML=`<nav class="cps-asset-nav">${[['overview','Dossier','ข้อมูล'],['storage',homes?'Stash':'Cargo',homes?'คลังบ้าน':'สัมภาระ'],[homes?'workshop':'vehicle',homes?'Workshop':'Vehicle systems',homes?'เวิร์กช็อป':'ระบบรถ'],['history','Service log','ประวัติ']].map(([k,en,th])=>btn('page:'+k,tr(en,th),`aria-pressed="${page===k}"`)).join('')}</nav><section class="cps-asset-page">${page==='overview'?`<small>OWNERSHIP / ${E(a.id)}</small><h2>${E(a.nickname||a.name)}</h2><p>${E(a.description||tr('Add your own established details below.','เพิ่มรายละเอียดที่กำหนดไว้ในเรื่องด้านล่าง'))}</p><dl><dt>${E(tr('Location','ตำแหน่ง'))}</dt><dd>${E(a.location||'Unknown')}</dd><dt>${E(tr('Purchase price','ราคาซื้อ'))}</dt><dd>€$${a.price||0}</dd><dt>${E(tr('Upgrades','อัปเกรด'))}</dt><dd>${E(Object.entries(a.upgrades||{}).map(([k,v])=>k+' LV.'+v).join(' · ')||'None')}</dd></dl>${homes?`<form data-op="rest"><h3>LIVING / LV.${a.upgrades?.living||0}</h3><p>${E(tr('Enter this home, then rest once per story turn: each Living level restores 10 HP, 20 stamina, 1 RAM and removes 5 stress. Security is a narrative amenity; no hidden theft simulation.','เข้าบ้านก่อนแล้วพักได้หนึ่งครั้งต่อเทิร์นเรื่อง Living แต่ละเลเวลฟื้น HP 10, stamina 20, RAM 1 และลด stress 5 ส่วน Security เป็นรายละเอียดประกอบเรื่อง ไม่มีระบบสุ่มขโมยซ่อนอยู่'))}</p><button class="cps-button">${E(tr('Rest here','พักฟื้นที่นี่'))}</button></form>`:''}<form data-op="details"><label>${E(tr('Nickname','ชื่อเรียก'))}<input name="nickname" value="${E(a.nickname||'')}" maxlength="100"></label><label>${E(tr('Description','รายละเอียด'))}<textarea name="description" rows="4">${E(a.description||'')}</textarea></label><label>${E(tr('Private notes','บันทึกส่วนตัว'))}<textarea name="notes" rows="4">${E(a.notes||'')}</textarea></label><button class="cps-button">${E(tr('Save details','บันทึก'))}</button></form>`:''}
     ${page==='storage'?`<h2>${E(tr(homes?'Home stash':'Vehicle cargo',homes?'คลังบ้าน':'สัมภาระรถ'))}</h2><p>${storage.length} / ${capacity(kind,a)} ${E(tr('stack slots · equipped items must be unloaded first','ช่องกองไอเท็ม · ต้องถอดอุปกรณ์ก่อนฝาก'))}</p>${['deposit','withdraw'].map(op=>`<form data-op="${op}"><h3>${E(tr(op==='deposit'?'Deposit':'Withdraw',op==='deposit'?'ฝาก':'ถอน'))}</h3><select name="itemId" required><option value="">${E(tr('Choose item','เลือกไอเท็ม'))}</option>${(op==='deposit'?items:storage).map(i=>`<option value="${E(i.id)}">${E(i.name)} ×${i.quantity}${i.equipped?' [equipped]':''}</option>`).join('')}</select><label>${E(tr('Quantity','จำนวน'))}<input type="number" name="quantity" min="1" max="9999" value="1" required></label><button class="cps-button">${E(tr(op==='deposit'?'Store item':'Take item',op==='deposit'?'ฝากไอเท็ม':'นำออก'))}</button></form>`).join('')}`:''}
     ${page==='workshop'?`<h2>WORKSHOP / LV.${a.upgrades?.workshop||0}</h2><p>${E(tr('Consumes carried components and eddies only when confirmed. Outputs enter inventory unloaded. Upgrade Workshop in Actions first.','ใช้ชิ้นส่วนที่พกกับเงินเมื่อยืนยัน ผลผลิตเข้าคลังโดยยังไม่ติดตั้ง อัปเกรด Workshop จากจัดการก่อน'))}</p>${recipes.map(r=>`<form data-op="craft"><input type="hidden" name="recipe" value="${r.id}"><h3>${E(r.name)}</h3><p>${r.components} components · €$${r.cost}</p><button class="cps-button" ${(a.upgrades?.workshop||0)<1?'disabled':''}>${E(tr('Craft','คราฟต์'))}</button></form>`).join('')}<form data-op="upgrade-item"><h3>${E(tr('Upgrade owned equipment','อัปเกรดอุปกรณ์ที่มี'))}</h3><p>${E(tr('Cost: current level × €$100; 2 + floor(level/5) components. Maximum level = Workshop × 10. Weapon power +1; quickhack level +1 (no automatic cost reduction).','ราคา: เลเวลปัจจุบัน × €$100; ชิ้นส่วน 2 + ปัดลง(เลเวล/5) เพดานเลเวล = Workshop × 10 อาวุธเพิ่ม power 1; Quickhack เพิ่มเลเวล 1 ไม่ลด RAM อัตโนมัติ'))}</p><select name="itemId">${items.filter(i=>['weapons','quickhack'].includes(i.category)).map(i=>`<option value="${E(i.id)}">${E(i.name)} LV.${i.level||1}</option>`).join('')}</select><button class="cps-button">${E(tr('Confirm upgrade','ยืนยันอัปเกรด'))}</button></form>`:''}
     ${page==='vehicle'?`<div class="cps-asset-metrics"><span>CONDITION<b>${a.condition??100}%</b></span><span>FUEL<b>${a.fuel??100}%</b></span><span>DISTANCE<b>${a.odometer||0} km</b></span></div><p>${E(tr('Local RP trip rules: fuel = ceil(km/(5+engine level)); wear = ceil(km/(20+5×armor level)). No automatic travel or GPS.','กติกาเดินทาง RP: น้ำมัน = ปัดขึ้น(km/(5+เลเวลเครื่อง)); สึกหรอ = ปัดขึ้น(km/(20+5×เกราะ)) ไม่เคลื่อนที่อัตโนมัติและไม่ใช้ GPS'))}</p><form data-op="trip"><label>${E(tr('Record confirmed travel distance (km)','บันทึกระยะทางที่เดินทางแล้ว (km)'))}<input type="number" name="distance" min="0.1" max="1000" step="0.1" required></label><button class="cps-button">${E(tr('Record trip','บันทึกเดินทาง'))}</button></form><form data-op="refuel"><p>€$${(100-(a.fuel??100))*2} / ${E(tr('Fill tank','เติมเต็มถัง'))}</p><button class="cps-button">${E(tr('Pay & refuel','จ่ายและเติม'))}</button></form><form data-op="vehicle-upgrade"><select name="area">${['cargo','armor','engine'].map(k=>`<option value="${k}">${k} LV.${a.upgrades?.[k]||0} → ${(a.upgrades?.[k]||0)+1} / €$${1000*((a.upgrades?.[k]||0)+1)}</option>`).join('')}</select><button class="cps-button">${E(tr('Pay & upgrade','จ่ายและอัปเกรด'))}</button></form><form data-op="assign-garage"><select name="homeId"><option value="">Street parking / ไม่ผูกบ้าน</option>${s.properties.filter(h=>h.status!=='sold').map(h=>`<option value="${E(h.id)}" ${h.id===a.garageId?'selected':''}>${E(h.name)}</option>`).join('')}</select><button class="cps-button">${E(tr('Assign garage','กำหนดโรงรถ'))}</button></form>`:''}
     ${page==='history'?`<h2>${E(tr('Service history','ประวัติการใช้งาน'))}</h2>${(a.serviceLog||[]).slice().reverse().map(v=>`<div class="cps-recovery-row"><span>${E(v.operation)} · ${E(v.detail)}<small>${E(new Date(v.at).toLocaleString())}</small></span></div>`).join('')||'<p>No records / ยังไม่มีบันทึก</p>'}`:''}<p data-asset-error role="alert"></p></section>`;
     host.querySelectorAll('[data-asset]').forEach(b=>b.onclick=()=>{page=b.dataset.asset.slice(5);draw();});host.querySelectorAll('form').forEach(f=>f.onsubmit=e=>{e.preventDefault();if(owner!==api.chatBucket()||!d.isConnected)return;try{transact(kind,id,f.dataset.op,Object.fromEntries(new FormData(f)));draw();api.render?.();}catch(err){host.querySelector('[data-asset-error]').textContent=err.message;}});
   };draw();return d;
 }
 return {transact,capacity,recipes,markup,open};
};
})();
