/* Cyberpunk role-play systems. All state stays with the current ST chat. */
(() => {
'use strict';
globalThis.CyberpunkSystemsFactory = api => {
  const C=globalThis.CyberpunkRpgCore, DB=globalThis.CyberpunkCatalog, E=api.htmlEscape;
  const tr=(en,th)=>api.settings().language==='th'?th:en;
  let panel=null, breach=null, timer=null, actorName='user', tab='status', popup=null;
  const noticeTimers=new Map();
  const tags='STATE|SKILL|BREACH|TRANSFER|SHARE|CALL_END|LOCATION|QUEST|ITEM|RELIC|BLACKWALL';
  const buttons=(label,action,extra='')=>`<button type="button" class="cps-button" data-rpg="${action}" ${extra}>${E(label)}</button>`;
  const note=v=>`<p class="cps-rpg-note">${E(v)}</p>`;
  function state(){
    const b=api.chatBucket();
    if(!b.rpg||typeof b.rpg!=='object')b.rpg={};const s=b.rpg;
    s.player=C.hydrate(s.player);s.actors??={};s.turn??=0;s.settings??={riskScale:1,notifications:true,noticeSeconds:6};
    for(const k of ['events','processed','notifications','quests','shares'])if(!Array.isArray(s[k]))s[k]=[];
    s.map??={location:{district:'',subdistrict:'',building:'',floor:'',area:''},discovered:[],completed:[]};
    return s;
  }
  function actor(name='user'){
    if(['user','player',api.context()?.name1].includes(name))return state().player;
    const npc=api.findEffectiveNpc(C.handle(name));if(!npc)throw Error(tr('Unknown contact','ไม่พบผู้ติดต่อ'));
    // NPC identity follows scope; mutable economy is isolated per chat, including group chats.
    const key=`npc:${npc.id||npc.name.toLowerCase()}`;state().actors[key]=C.hydrate(state().actors[key]);return state().actors[key];
  }
  const save=()=>{api.saveChat();api.refreshPrompt();};
  function event(type,detail){const s=state();s.events.push({id:C.uid(),turn:s.turn,type,detail:C.text(detail,1200)});s.events=s.events.slice(-50);save();}
  function guard(fn){try{return fn();}catch(e){api.toast(e.message);return null;}}
  function closePanel(){api.removeUiDialog(panel);panel=null;}
  function dialog(title,body,cls=''){
    const d=document.createElement('dialog');d.className=`cps-ui cps-rpg-dialog ${cls}`;d.setAttribute('aria-label',title);
    d.innerHTML=`<header class="cps-rpg-top"><span class="cps-eyebrow">NEURAL OS / 02</span><h2>${E(title)}</h2>${buttons('×','close','aria-label="Close"')}</header><div class="cps-rpg-content">${body}</div>`;
    d.querySelector('[data-rpg="close"]').onclick=()=>api.removeUiDialog(d);d.addEventListener('cancel',e=>{e.preventDefault();api.removeUiDialog(d);});document.body.append(d);api.showUiDialog(d);return d;
  }
  function detail(title,content){api.removeUiDialog(popup);popup=dialog(title,`<div class="cps-rpg-detail">${E(content)}</div>`);}
  function notify(title,body,danger=false){
    const s=state(),n={id:C.uid(),title:C.text(title,180),body:C.text(body,3000),danger,at:Date.now()};s.notifications.push(n);s.notifications=s.notifications.slice(-60);save();
    if(!s.settings.notifications)return;
    let host=document.getElementById('cps-immersion');if(!host){host=document.createElement('aside');host.id='cps-immersion';host.setAttribute('aria-live','polite');document.body.append(host);if(typeof host.showPopover==='function'){host.setAttribute('popover','manual');try{host.showPopover();}catch{}}else document.querySelector('dialog.cps-ui[open]:last-of-type')?.append(host);}
    const b=document.createElement('button');b.className=`cps-immersion-card ${danger?'danger':''}`;b.type='button';b.innerHTML=`<small>${danger?'⚠ RESTRICTED ZONE':'◆ INCOMING DATA'}</small><strong>${E(n.title)}</strong><span>${E(tr('Tap for details','แตะดูรายละเอียด'))}</span>`;
    b.onclick=()=>{detail(n.title,n.body);remove();};const remove=()=>{clearTimeout(noticeTimers.get(n.id));noticeTimers.delete(n.id);b.remove();};
    const schedule=()=>{clearTimeout(noticeTimers.get(n.id));noticeTimers.set(n.id,setTimeout(remove,C.cap(s.settings.noticeSeconds,2,60)*1000));};
    b.onpointerenter=b.onfocus=()=>clearTimeout(noticeTimers.get(n.id));b.onpointerleave=b.onblur=schedule;
    host.append(b);while(host.children.length>3)host.firstElementChild.remove();schedule();
  }
  function icon(category='item'){
    const paths={cyberware:'M32 13v10m0 18v10M13 32h10m18 0h10M22 22h20v20H22zM28 28h8v8h-8z',weapons:'M12 23h36v10H33l-5 15H17l4-15h-9zM39 19v4',quickhack:'M36 9 17 35h14l-3 20 20-29H33z',consumable:'M25 12h14v12h12v16H39v12H25V40H13V24h12z',clothing:'M22 13l10 6 10-6 14 12-9 10-5-5v22H22V30l-5 5-9-10z',data:'M18 9h21l9 10v36H18zM38 9v12h10M25 30h15M25 38h15M25 46h9',mod:'M32 10l7 10h12v24H39L32 54l-7-10H13V20h12zM26 26h12v12H26z',component:'M32 10 52 22v22L32 56 12 44V22zM12 22l20 12 20-12M32 34v22',item:'M13 20h38v32H13zM24 20v-8h16v8M13 32h38'};
    return `<svg class="cps-item-image" viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="${paths[category]||paths.item}"/></svg>`;
  }
  function itemImage(it){return it.image&&/^data:image\/(png|jpeg|webp);base64,[a-z0-9+/=]+$/i.test(it.image)&&it.image.length<500000?`<img class="cps-item-image" src="${E(it.image)}" alt="">`:icon(it.category);}
  const meter=(label,v,max)=>`<div class="cps-rpg-meter"><span>${E(label)} <b>${Math.round(v)} / ${Math.round(max)}</b></span><meter min="0" max="${Math.max(1,max)}" value="${C.cap(v,0,max)}">${v}</meter></div>`;
  function open(name='user',nextTab='status'){guard(()=>actor(name));if(name!=='user'&&!api.findEffectiveNpc(C.handle(name)))return;actorName=name;tab=nextTab;closePanel();
    panel=dialog(name==='user'?'Cyberware':`${name} / Cyberware`,'','cps-rpg-main');panel.querySelector('[data-rpg="close"]').onclick=closePanel;render();}
  function render(){if(!panel?.isConnected)return;const a=actor(actorName),s=state();
    const tabs=[['status','Status'],['cyberware','Cyberware'],['weapons','Weapons'],['balance','Balance'],['inventory','Inventory'],['skills','Skills / Hacking'],['quests','Missions / Quests'],['map','Night City'],['relic','Relic / Blackwall'],['settings',tr('Settings','ตั้งค่า')]];
    const body=panel.querySelector('.cps-rpg-content');body.innerHTML=`<nav class="cps-rpg-tabs" aria-label="Cyberware sections">${tabs.map(([k,v])=>buttons(v,`tab:${k}`,`aria-pressed="${tab===k}"`)).join('')}</nav><div class="cps-rpg-body"></div>`;
    const area=body.querySelector('.cps-rpg-body');
    if(tab==='status')area.innerHTML=`<div class="cps-rpg-hero"><span>BIOMETRIC TELEMETRY</span><h3>${E(actorName==='user'?api.context()?.name1||'V':actorName)}</h3><strong>${a.cyberpsychosis?'NEURAL INSTABILITY':'CONNECTED'}</strong></div><div class="cps-rpg-meters">${meter('HEALTH',a.hp,a.maxHp)}${meter('STAMINA',a.stamina,a.maxStamina)}${meter('RAM',a.ram,a.maxRam)}${meter('CYBERWARE',C.load(a),a.capacity)}${meter('STRESS',a.stress,100)}</div>${note(`${tr('Cyberpsychosis chance per story turn','โอกาส Cyberpsychosis ต่อเทิร์นเนื้อเรื่อง')}: ${C.risk(a,s.settings.riskScale).toFixed(1)}% · ${tr('Extension role-play rule','กติกาโรลเพลย์ของ extension')}`)}${buttons(tr('Recover: spend a turn','พักฟื้น: ใช้หนึ่งเทิร์น'),'recover')}${buttons(tr('Edit starting status','แก้ไขสถานะตั้งต้น'),'setup')}${buttons(tr('Notification history','ประวัติแจ้งเตือน'),'notices')}`;
    if(['cyberware','weapons','inventory'].includes(tab)){
      const items=a.inventory.filter(it=>tab==='inventory'||it.category===tab);
      area.innerHTML=`<div class="cps-rpg-actions">${buttons(tr('Browse catalog','ค้นหาแค็ตตาล็อก'),'catalog')}${buttons(tr('Add custom item','เพิ่มไอเท็มเอง'),'custom-item')}</div>${note(tr('Local role-play equipment. Numbers are editable extension tuning, not game stats.','อุปกรณ์โรลเพลย์ในแชต ค่าต่าง ๆ เป็นกติกาของ extension ที่แก้ไขได้ ไม่ใช่สเตตัสจากเกม'))}<div class="cps-rpg-items">${items.map(it=>`<article class="cps-rpg-item">${itemImage(it)}<div><small>${E(it.category)} ${it.equipped?'// LINKED':''}</small><h3>${E(it.name)}</h3><p>×${it.quantity}${it.category==='cyberware'?` · ${it.capacity} capacity · ${E(it.slot)}`:''}</p>${note(it.effect)}<div class="cps-rpg-actions">${['cyberware','weapons','clothing'].includes(it.category)?buttons(it.equipped?'Unequip':'Equip',`equip:${it.id}`):''}${buttons('Use',`use:${it.id}`)}${buttons('Edit',`edit-item:${it.id}`)}${buttons('Share',`share-item:${it.id}`)}${buttons('−1',`remove-item:${it.id}`)}</div></div></article>`).join('')||note(tr('Inventory empty. Add established equipment from the catalog.','ยังไม่มีอุปกรณ์ เพิ่มของที่มีในเนื้อเรื่องจากแค็ตตาล็อกได้'))}</div>`;
    }
    if(tab==='balance')area.innerHTML=`<div class="cps-rpg-hero"><span>EURODOLLAR ACCOUNT</span><h3>€$ ${a.balance.toLocaleString()}</h3></div><div class="cps-rpg-actions">${buttons(tr('Transfer','โอนเงิน'),'transfer')}${buttons(tr('Set starting balance','ตั้งยอดเงินเริ่มต้น'),'setup')}</div>${note(tr('Main chat: /cp transfer @handle 500 · Transfers require a stored contact and sufficient funds.','พิมพ์ในแชต: /cp transfer @handle 500 หรือ โอนเงิน 500 ให้ @handle · ต้องมีผู้ติดต่อและเงินเพียงพอ'))}<div class="cps-rpg-ledger">${a.ledger.slice().reverse().map(e=>`<article><strong>${e.delta>0?'+':''}${e.delta} €$</strong> ${E(e.reason)}<small>${E(e.at)}</small></article>`).join('')}</div>`;
    if(tab==='skills')area.innerHTML=`<div class="cps-rpg-actions">${buttons('Breach Protocol','practice')}${buttons(tr('Add skill','เพิ่มสกิล'),'add-skill')}${s.puzzle&&['ready','running'].includes(s.puzzle.status)?buttons('Resume breach','resume'):''}</div>${a.skills.map(sk=>`<article class="cps-rpg-skill"><span>Lv.${sk.level} / ${sk.xp} XP</span><h3>${E(sk.name)}</h3>${note(sk.description)}<p>${sk.cost} ${E(sk.resource)} · cooldown ${sk.cooldown} turns</p>${buttons(sk.readyTurn>s.turn?'Recharging':'Activate',`skill:${sk.id}`,sk.readyTurn>s.turn?'disabled':'')}</article>`).join('')||note(tr('Skills appear when used in the story, or add them here.','สกิลจะถูกเพิ่มเมื่อใช้ในเนื้อเรื่อง หรือกดเพิ่มเองได้'))}`;
    if(tab==='quests')area.innerHTML=`${buttons(tr('Add mission','เพิ่มภารกิจ'),'add-quest')}${s.quests.map(q=>`<article class="cps-rpg-skill"><small>${E(q.status)}</small><h3>${E(q.title)}</h3>${note(q.description)}${note(q.objective)}${buttons('Share',`share-quest:${q.id}`)}${buttons('Advance status',`quest:${q.id}`)}</article>`).join('')}`;
    if(tab==='map')renderMap(area);
    if(tab==='relic')area.innerHTML=`<div class="cps-rpg-hero"><span>RESTRICTED NEURAL PARTITION</span><h3>RELIC / BLACKWALL</h3></div>${note(tr('Story-gated role-play systems. Unlock only when established in your scenario.','ระบบโรลเพลย์ที่ปลดล็อกตามเนื้อเรื่อง เปิดเมื่อสถานการณ์รองรับเท่านั้น'))}${buttons(a.relic.unlocked?'Relic linked':'Unlock Relic','unlock-relic')}${meter('RELIC POINTS',a.relic.points,10)}${['Jailbreak','Emergency Cloaking','Vulnerability Analytics'].map(name=>buttons(a.relic.abilities.includes(name)?`${name} ✓`:`${name} · 1 RP`,`relic:${name}`,!a.relic.unlocked||a.relic.abilities.includes(name)?'disabled':'')).join('')}${buttons('Earn 1 RP (story setup)','relic-point')}${buttons(a.blackwall.unlocked?'Blackwall linked':'Unlock Blackwall','unlock-blackwall')}${meter('BLACKWALL EXPOSURE',a.blackwall.exposure,100)}${buttons('Interface · 4 RAM / +20 exposure','blackwall',!a.blackwall.unlocked?'disabled':'')}${buttons('Disconnect / recover','disconnect')}${note(tr('High exposure drains health and increases stress. Relic abilities use simplified local mechanics.','การสัมผัสระดับสูงลดพลังชีวิตและเพิ่มความเครียด ความสามารถ Relic ใช้กลไกย่อของ extension'))}`;
    if(tab==='settings')area.innerHTML=`<form data-rpg-settings><label>${tr('Notifications','การแจ้งเตือน')}<input name="notifications" type="checkbox" ${s.settings.notifications?'checked':''}></label><label>${tr('Dismiss after (seconds)','เวลาหาย (วินาที)')}<input name="noticeSeconds" type="number" min="2" max="60" value="${s.settings.noticeSeconds}" required></label><label>${tr('Cyberpsychosis risk multiplier (0 disables)','ตัวคูณความเสี่ยง Cyberpsychosis (0 = ปิด)')}<input name="riskScale" type="number" min="0" max="3" step="0.1" value="${s.settings.riskScale}" required></label><button class="cps-button primary" type="submit">Save</button></form>${note(tr('Stored in this chat. Location is narrative information, not GPS.','บันทึกแยกตามแชต ตำแหน่งเป็นข้อมูลจากเนื้อเรื่อง ไม่ใช่ GPS'))}`;
    body.querySelectorAll('[data-rpg]').forEach(b=>b.onclick=()=>guard(()=>action(b.dataset.rpg)));
    body.querySelector('[data-rpg-settings]')?.addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;s.settings={notifications:f.elements.notifications.checked,noticeSeconds:C.cap(f.elements.noticeSeconds.value,2,60),riskScale:C.cap(f.elements.riskScale.value,0,3)};save();api.toast('Saved');});
  }
  function form(title,fields,submit){
    const owner=safeOwner();
    const d=dialog(title,`<form class="cps-rpg-form">${fields.map(([name,label,value='',type='text',extra=''])=>`<label>${E(label)}${type==='textarea'?`<textarea name="${name}" ${extra}>${E(value)}</textarea>`:type==='select'?`<select name="${name}">${value}</select>`:`<input name="${name}" type="${type}" value="${E(value)}" ${extra}>`}</label>`).join('')}<button class="cps-button primary" type="submit">${tr('Save / Send','บันทึก / ส่ง')}</button><p role="alert" data-error></p></form>`);
    d.querySelector('form').onsubmit=e=>{e.preventDefault();try{if(owner!==safeOwner()||!d.isConnected)throw Error('Chat changed; reopen this form.');submit(Object.fromEntries(new FormData(e.currentTarget)));api.removeUiDialog(d);save();render();}catch(err){d.querySelector('[data-error]').textContent=err.message;}};return d;
  }
  function setup(){const a=actor(actorName);form('Starting status / RP setup',[['balance','Balance €$',a.balance,'number','min="0" max="1000000000000" required'],...['hp','maxHp','ram','maxRam','stamina','maxStamina','capacity','stress'].map(k=>[k,k,a[k],'number','min="0" max="1000" required'])],v=>{const balance=C.money(v.balance),old=a.balance;a.balance=balance;a.ledger.push({id:C.uid(),delta:balance-old,reason:'Manual story setup',at:new Date().toISOString()});for(const k of ['maxHp','maxRam','maxStamina','capacity'])a[k]=C.cap(v[k],1,1000);for(const [k,max]of [['hp',a.maxHp],['ram',a.maxRam],['stamina',a.maxStamina],['stress',100]])a[k]=C.cap(v[k],0,max);event('setup',`${actorName}: manual status adjustment`);});}
  function editItem(it){form(it?'Edit equipment':'Custom equipment',[['name','Name',it?.name||'','text','required maxlength="180"'],['category','Category',['cyberware','weapons','quickhack','consumable','clothing','mod','component','data','item'].map(k=>`<option ${it?.category===k?'selected':''}>${k}</option>`).join(''),'select'],['slot','Slot',it?.slot||''],['quantity','Quantity',it?.quantity||1,'number','min="1" max="9999" required'],['capacity','Capacity cost (RP)',it?.capacity??10,'number','min="0" max="300"'],['power','Power / healing (RP)',it?.power??20,'number','min="0" max="1000"'],['cooldown','Cooldown turns',it?.cooldown??2,'number','min="0" max="30"'],['effect','Description',it?.effect||'','textarea']],v=>{const entry=C.item({...it,...v});if(it)Object.assign(it,entry,{equipped:it.equipped,cooldownUntil:it.cooldownUntil});else actor(actorName).inventory.push(entry);event('equipment',`${actorName}: ${entry.name}`);});}
  function transferDialog(peer=api.chatBucket().call.peer?.name){const names=api.effectiveRecords('npcs');if(!names.length)throw Error('Add a contact first');form(tr('Transfer eurodollars','โอนเงิน Eurodollars'),[['to','To',names.map(n=>`<option value="${E(n.name)}" ${n.name===peer?'selected':''}>${E(n.name)}</option>`).join(''),'select'],['amount','€$',1,'number','min="1" max="1000000000000" required'],['reason',tr('Reason','เหตุผล'),'']],v=>transfer('user',v.to,v.amount,v.reason));}
  function transfer(from,to,amount,reason,txid=C.uid()){
    if(!C.transfer(actor(from),actor(to),amount,reason||`${from} → ${to}`,txid))return false;
    event('transfer',`${from} → ${to}: €$${amount}. ${C.text(reason,500)}`);notify('TRANSFER COMPLETE',`${from} → ${to} · €$${amount}\n${reason||''}`);
    if(api.chatBucket().call.active)share({kind:'receipt',title:'TRANSFER COMPLETE',description:`${from} → ${to} · €$${amount}`,id:txid},from==='user'?'user':'assistant',from);
    return true;
  }
  function userText(raw,key){const s=state();const receipt=`user:${key}`;if(s.processed.includes(receipt))return;
    const m=C.text(raw,4000).match(/^\/cp\s+transfer\s+(.+?)\s+(\d+)(?:\s+(.+))?$/i)||C.text(raw,4000).match(/^โอนเงิน\s+(\d+)\s+ให้\s+(.+?)\s*$/u)?.map((v,i,arr)=>i===1?arr[2]:i===2?arr[1]:v);
    if(!m)return; s.processed.push(receipt);s.processed=s.processed.slice(-3000);guard(()=>transfer('user',C.handle(m[1]),m[2],m[3]||'Main-chat instruction',receipt));save();}
  function share(data,role='assistant',name=api.chatBucket().call.peer?.name||'System'){
    const entry={id:C.text(data.id||C.uid(),160),kind:C.text(data.kind,30),title:C.text(data.title||data.item?.name||data.contact?.name||'Data',180),description:C.text(data.description,5000)};
    if(!['location','mission','item','contact','data','receipt'].includes(entry.kind))throw Error('Unknown attachment kind');
    if(entry.kind==='item')entry.item=C.item(data.item||{name:entry.title});
    if(entry.kind==='contact'){
      const fields=['name','handle','role','status','affiliation','age','gender','personality','appearance','notes'];
      if(!data.contact||fields.some(k=>!C.text(data.contact[k])))throw Error('Contact requires a complete dossier');
      entry.contact=Object.fromEntries(fields.map(k=>[k,C.text(data.contact[k],k==='notes'?3000:2000)]));entry.contact.handle=C.handle(entry.contact.handle);
      entry.contact.rpg={balance:C.money(data.contact.balance??0),inventory:Array.isArray(data.contact.inventory)?data.contact.inventory.slice(0,100).map(C.item):[]};
    }
    const s=state();if(s.shares.some(x=>x.id===entry.id))return; s.shares.push(entry);s.shares=s.shares.slice(-100);
    if(api.chatBucket().call.active){const m=api.appendCallMessage(role,name,entry.title,role==='user');if(m){m.attachment=entry;api.renderCallLog();}}
    else notify(entry.title,entry.description||tr('Open Cyberware to inspect received data.','เปิด Cyberware เพื่อดูข้อมูล'));
    event('share',`${role}: ${entry.kind}: ${entry.title} · ${entry.description}`);save();return entry;
  }
  function attachment(node,message){const v=message.attachment;if(!v||node.querySelector('.cps-attachment'))return;
    const card=document.createElement('article');card.className='cps-attachment';card.innerHTML=`${v.item?itemImage(v.item):icon('data')}<div><small>${E(v.kind)}</small><strong>${E(v.title)}</strong>${note(v.description)}${buttons(v.kind==='contact'?tr('Add contact','เพิ่มผู้ติดต่อ'):tr('Open data','เปิดข้อมูล'),'open-attachment')}</div>`;
    card.querySelector('button').onclick=()=>guard(()=>{if(v.kind==='contact')addContact(v.contact);else detail(v.title,v.description||v.item?.effect||v.item?.name||v.title);});node.append(card);
  }
  function addContact(contact){if(!contact?.name)throw Error('Invalid contact');if(api.findEffectiveNpc(contact.name)||api.findEffectiveNpc(contact.handle)){api.toast('Contact already exists');return;}
    const npc={...contact,id:C.uid(),handle:C.handle(contact.handle),createdAt:new Date().toISOString()};delete npc.rpg;api.chatBucket().npcs.push(npc);const a=actor(npc.name);a.balance=C.money(contact.rpg?.balance??0);a.inventory=(contact.rpg?.inventory||[]).map(C.item);save();notify('CONTACT ADDED',`${npc.name} · @${npc.handle}`);}
  function shareDialog(){form('Send data',[['kind','Type',['data','location','mission'].map(k=>`<option>${k}</option>`).join(''),'select'],['title','Title','','text','required maxlength="180"'],['description','Details','','textarea','required maxlength="5000"']],v=>share(v,'user',api.context()?.name1||'User'));}
  function callToolbar(overlay){if(overlay.querySelector('.cps-call-tools'))return;const bar=document.createElement('div');bar.className='cps-call-tools';bar.innerHTML=buttons('€$','transfer')+buttons(tr('Location','โลเคชั่น'),'send-location')+buttons(tr('Send data','ส่งข้อมูล'),'share')+buttons('Cyberware','open');bar.querySelectorAll('button').forEach(b=>b.onclick=()=>guard(()=>action(b.dataset.rpg)));overlay.querySelector('.cps-call-composer')?.prepend(bar);}
  function catalog(){const target=actorName;const d=dialog('Equipment database',`<label>${tr('Search names or game IDs','ค้นชื่อหรือรหัสไอเท็ม')}<input type="search" data-catalog-search placeholder="Monowire / Items…"></label><label><input type="checkbox" data-technical> ${tr('Include 3,420 technical IDs (unverified display names)','รวมรหัสเทคนิค 3,420 รายการ (ยังไม่ยืนยันชื่อแสดงผล)')}</label>${note(tr('50 named entries plus an imported ID index. Not a verified complete game catalog. SVG symbols are original; role-play stats are editable. Adding an item records a manual grant, not a purchase.','มี 50 รายการชื่ออ่านง่ายและดัชนีรหัสนำเข้า ยังไม่ใช่รายการทุกอย่างที่ตรวจสอบครบ ไอคอน SVG วาดใหม่ ค่าสำหรับโรลเพลย์แก้ไขได้ การเพิ่มเป็นการตั้งอุปกรณ์เอง ไม่ใช่การซื้อ'))}<p data-count></p><div class="cps-rpg-catalog"></div>`);
    const draw=()=>{const q=d.querySelector('input[type=search]').value.trim().toLowerCase(),technical=d.querySelector('[data-technical]').checked;
      const all=[...DB.curated,...(technical?DB.records:[])].filter(x=>`${x.name} ${x.id} ${x.category}`.toLowerCase().includes(q));d.querySelector('[data-count]').textContent=`${all.length} results · showing ${Math.min(60,all.length)}`;
      const grid=d.querySelector('.cps-rpg-catalog');grid.innerHTML=all.slice(0,60).map((it,i)=>`<article class="cps-rpg-item">${itemImage(it)}<div><small>${E(it.category)}${it.technical?' / TECHNICAL ID':''}</small><h3>${E(it.name)}</h3>${buttons(tr('Add to inventory','เพิ่มในคลัง'),`catalog:${i}`)}</div></article>`).join('');grid.querySelectorAll('button').forEach((b,i)=>b.onclick=()=>guard(()=>{const it=C.item({...all[i],id:C.uid(),catalogId:all[i].id});actor(target).inventory.push(it);event('manual grant',`${target}: ${it.name}`);b.textContent='Added ✓';b.disabled=true;render();}));};
    d.querySelector('[data-catalog-search]').oninput=draw;d.querySelector('[data-technical]').onchange=draw;draw();
  }
  function renderMap(area){const m=state().map,l=m.location;const location=[l.district,l.subdistrict,l.building,l.floor?`${tr('Floor','ชั้น')} ${l.floor}`:'',l.area].filter(Boolean).join(' / ');
    area.innerHTML=`<div class="cps-rpg-hero"><span>NIGHT CITY / EXPLORATION</span><h3>${E(l.subdistrict||tr('Location unknown','ยังไม่ทราบตำแหน่ง'))}</h3></div>${note(location||tr('Set the established location to begin mapping.','ตั้งตำแหน่งตามเนื้อเรื่องเพื่อเริ่มสำรวจ'))}<svg class="cps-world-map" viewBox="0 0 100 105" role="img" aria-label="Night City schematic map"><defs><pattern id="cps-map-grid" width="5" height="5" patternUnits="userSpaceOnUse"><path d="M5 0H0V5" fill="none" stroke="currentColor" stroke-opacity=".13" stroke-width=".2"/></pattern></defs><rect width="100" height="105" fill="url(#cps-map-grid)"/><path class="cps-map-road" d="M37 20 35 42 36 61 34 82M37 20 68 36 69 64 86 86M35 42 68 36M36 61 69 64"/>${DB.districts.map(d=>{const visible=m.discovered.includes(d.id),done=m.completed.includes(d.id),current=l.district===d.id;return `<g class="cps-map-zone ${visible?'discovered':'locked'} ${done?'completed':''}" role="button" tabindex="0" data-zone="${d.id}" aria-label="${E(visible?d.name:'Unexplored area')}"><path d="M${d.x-13} ${d.y-7}h22l4 4v10h-26z"/><text x="${d.x}" y="${d.y+1}" text-anchor="middle">${visible?E(d.name):'LOCKED'}</text>${current?`<circle class="cps-map-player" cx="${d.x}" cy="${d.y+5}" r="1.3"/>`:''}</g>`;}).join('')}</svg>${note(tr('Original schematic, not an official street map. Unexplored districts hide details; incomplete areas remain restricted. Position comes from story updates, including floor and interior.','แผนที่แผนผังวาดใหม่ ไม่ใช่แผนที่ถนนทางการ พื้นที่ที่ยังไม่สำรวจจะซ่อนข้อมูล พื้นที่ไม่สำเร็จยังถูกจำกัด ตำแหน่งอัปเดตจากเนื้อเรื่อง รวมชั้นและบริเวณภายใน'))}${buttons(tr('Update location','อัปเดตตำแหน่ง'),'location')}${buttons(tr('Mark current district completed','ทำเครื่องหมายพื้นที่ปัจจุบันสำเร็จ'),'complete-zone')}`;
    area.querySelectorAll('[data-zone]').forEach(g=>{const show=()=>{const d=DB.districts.find(x=>x.id===g.dataset.zone);detail(m.discovered.includes(d.id)?d.name:'LOCKED',m.discovered.includes(d.id)?`${d.areas.join(' · ')}\n${m.completed.includes(d.id)?'Area completed':'Restricted / objectives incomplete'}`:tr('Explore this area in the story to reveal it.','สำรวจพื้นที่นี้ในเนื้อเรื่องเพื่อเปิดเผยข้อมูล'));};g.onclick=show;g.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show();}};});
  }
  function location(data){const m=state().map,known=DB.districts.find(d=>d.id===data.district||d.name.toLowerCase()===String(data.district).toLowerCase());if(!known)throw Error('Unknown Night City district');
    const old=JSON.stringify(m.location);m.location={district:known.id,...Object.fromEntries(['subdistrict','building','floor','area'].map(k=>[k,C.text(data[k],180)])),danger:data.danger===true};if(!m.discovered.includes(known.id))m.discovered.push(known.id);
    if(old!==JSON.stringify(m.location))notify(data.danger?'DANGER ZONE':known.name,[known.name,data.subdistrict,data.building,data.floor?`Floor ${data.floor}`:'',data.area,data.reason].filter(Boolean).join(' / '),data.danger===true);event('location',JSON.stringify(m.location));}
  function locationDialog(){const l=state().map.location;form('Location / narrative coordinates',[['district','District',DB.districts.map(d=>`<option value="${d.id}" ${l.district===d.id?'selected':''}>${E(d.name)}</option>`).join(''),'select'],...['subdistrict','building','floor','area'].map(k=>[k,k,l[k]||'']),['danger','Danger',['false','true'].map(v=>`<option ${String(l.danger)===v?'selected':''}>${v}</option>`).join(''),'select']],v=>location({...v,danger:v.danger==='true'}));}
  function stopBreach(){clearInterval(timer);timer=null;api.removeUiDialog(breach);breach=null;}
  function minimized(){let b=document.getElementById('cps-breach-resume');const p=state().puzzle;if(!p||!['ready','running'].includes(p.status)||!p.minimized){b?.remove();return;}if(!b){b=document.createElement('button');b.id='cps-breach-resume';b.className='cps-button';b.onclick=openBreach;document.body.append(b);if(typeof b.showPopover==='function'){b.setAttribute('popover','manual');try{b.showPopover();}catch{}}else document.querySelector('dialog.cps-ui[open]:last-of-type')?.append(b);}b.textContent=`▣ BREACH / ${p.target} · ${tr('Resume','เปิดต่อ')}`;}
  function beginBreach(data={}){const s=state();if(s.puzzle&&['ready','running'].includes(s.puzzle.status)){notify('BREACH PENDING','Finish or cancel the current access point first.');return false;}s.puzzle=C.puzzle(data);save();openBreach();return true;}
  function settle(p){if(p.revealed)return;if(!['success','failed','cancelled'].includes(p.status))return;p.revealed=true;save();
    event('breach result',`${p.target}: ${p.status}${p.status==='success'?` · unlocked data: ${p.data}`:''}`);
    if(p.status==='success'){const sk=C.addSkill(state().player,{name:'Netrunner',resource:'ram'});sk.xp+=25;if(sk.xp>=100&&sk.level<60){sk.level++;sk.xp-=100;}notify('ACCESS GRANTED',p.data||p.target);}else notify('ACCESS DENIED',`${p.target}: ${p.status}`,true);save();
  }
  function openBreach(){const p=state().puzzle;if(!p)return;stopBreach();p.minimized=false;minimized();
    breach=document.createElement('dialog');breach.className='cps-ui cps-breach';breach.setAttribute('aria-label','Breach Protocol');breach.innerHTML=`<section class="cps-breach-terminal"><header class="cps-breach-drag"><span>BREACH PROTOCOL / ${E(p.target)}</span><small>↕ ${tr('Drag to move','ลากขึ้นลง')}</small></header><div class="cps-breach-controls">${buttons('—','minimize','aria-label="Minimize and pause"')}${buttons('Cancel','cancel')}${buttons('Finish upload','finish')}</div><label class="cps-breach-position">↕ <input type="range" min="-100" max="100" value="${C.cap(p.offset,-100,100)}" aria-label="Vertical position"></label><div class="cps-breach-clock" role="timer"></div><div class="cps-breach-buffer"></div><div class="cps-breach-columns"><div class="cps-breach-grid" role="group" aria-label="Code matrix"></div><div class="cps-breach-daemons"></div></div><p class="cps-breach-help"></p></section>`;
    const terminal=breach.querySelector('.cps-breach-terminal'),owner=safeOwner();terminal.style.setProperty('--breach-offset',`${p.offset||0}px`);
    const move=v=>{p.offset=C.cap(v,-100,100);terminal.style.setProperty('--breach-offset',`${p.offset}px`);breach.querySelector('input').value=p.offset;};let drag=null;
    const h=breach.querySelector('.cps-breach-drag');h.onpointerdown=e=>{drag={y:e.clientY,start:p.offset||0};h.setPointerCapture?.(e.pointerId);};h.onpointermove=e=>{if(drag)move(drag.start+e.clientY-drag.y);};h.onpointerup=h.onpointercancel=()=>{drag=null;save();};
    breach.querySelector('input').oninput=e=>move(e.target.value);breach.querySelector('input').onchange=save;
    const pause=()=>{C.pause(p);save();stopBreach();minimized();};breach.addEventListener('cancel',e=>{e.preventDefault();pause();});
    breach.querySelector('[data-rpg=minimize]').onclick=pause;breach.querySelector('[data-rpg=cancel]').onclick=()=>{if(['ready','running'].includes(p.status)){C.pause(p);p.status='cancelled';settle(p);}stopBreach();minimized();};breach.querySelector('[data-rpg=finish]').onclick=()=>{C.finish(p);settle(p);drawBreach();};
    document.body.append(breach);api.showUiDialog(breach);drawBreach();timer=setInterval(()=>{if(owner!==safeOwner()){stopBreach();return;}if(C.remaining(p)<=0&&['ready','running'].includes(p.status)){C.finish(p);settle(p);drawBreach();}const clock=breach?.querySelector('.cps-breach-clock');if(clock)clock.textContent=`${(C.remaining(p)/1000).toFixed(1)}s / ${p.status.toUpperCase()}`;},100);
  }
  const safeOwner=()=>api.chatBucket();
  function drawBreach(){if(!breach)return;const p=state().puzzle,finished=!['ready','running'].includes(p.status);const grid=breach.querySelector('.cps-breach-grid');grid.style.setProperty('--matrix-size',p.grid.length);
    grid.innerHTML=p.grid.flatMap((row,r)=>row.map((value,c)=>{const used=p.selected.some(v=>v[0]===r&&v[1]===c),valid=!used&&(p.axis==='row'?r===p.row:c===p.col);return `<button type="button" data-cell="${r},${c}" class="${used?'used':valid?'available':''}" ${!valid||finished?'disabled':''} aria-label="Row ${r+1}, column ${c+1}, ${value}">${used?'·':value}</button>`;})).join('');
    grid.querySelectorAll('button').forEach(b=>b.onclick=()=>{const[r,c]=b.dataset.cell.split(',').map(Number);C.choose(p,r,c);settle(p);save();drawBreach();});
    breach.querySelector('.cps-breach-buffer').innerHTML=Array.from({length:p.buffer},(_,i)=>`<span>${p.sequence[i]||'—'}</span>`).join('');
    breach.querySelector('.cps-breach-daemons').innerHTML=p.daemons.map(d=>`<article class="${d.done?'complete':''}"><strong>${d.name} ${d.done?'✓':''}</strong><div>${d.codes.map(c=>`<b>${c}</b>`).join('')}</div></article>`).join('');
    breach.querySelector('.cps-breach-help').textContent=finished?(p.status==='success'?`ACCESS GRANTED · ${p.data}`:'ACCESS DENIED'):tr(`Select ${p.axis}. Start in the top row; alternate column / row. Match ACCESS before buffer fills. Timer starts on first selection; minimizing pauses it.`,`เลือก${p.axis==='row'?'แถว':'คอลัมน์'} เริ่มแถวบน สลับคอลัมน์/แถว ให้รหัส ACCESS ตรงก่อน buffer เต็ม เริ่มจับเวลาเมื่อกดครั้งแรก ย่อหน้าต่างเพื่อพักเวลา`);
    breach.querySelector('[data-rpg=finish]').disabled=finished;breach.querySelector('[data-rpg=minimize]').disabled=finished;
  }
  function action(command){const [kind,...rest]=command.split(':'),value=rest.join(':'),a=actor(actorName),s=state();
    if(kind==='tab'){tab=value;render();return;}
    const actions={open:()=>open(),catalog,setup,transfer:()=>transferDialog(actorName==='user'?api.chatBucket().call.peer?.name:actorName),share:shareDialog,location:locationDialog,practice:()=>beginBreach({target:'Training access point',data:'Training completed. No story secrets unlocked.'}),resume:openBreach,'custom-item':()=>editItem(),
      recover:()=>{s.turn++;a.stress=C.cap(a.stress-20,0,100);a.ram=a.maxRam;a.stamina=a.maxStamina;if(a.stress<30&&C.load(a)<=a.capacity)a.cyberpsychosis=false;event('recovery',`${actorName} rests one turn`);},
      'send-location':()=>share({kind:'location',title:'Location pin',description:Object.entries(s.map.location).map(([k,v])=>`${k}: ${v}`).join('\n')},'user',api.context()?.name1||'User'),
      'complete-zone':()=>{if(!s.map.location.district)throw Error('Set a location first');if(!s.map.completed.includes(s.map.location.district))s.map.completed.push(s.map.location.district);event('area completed',s.map.location.district);},
      'add-skill':()=>form('Add ability',[['name','Skill name','','text','required'],['description','Description','','textarea'],['cost','Resource cost',0,'number','min="0" max="100"'],['resource','Resource','<option>stamina</option><option>ram</option>','select'],['cooldown','Cooldown turns',1,'number','min="0" max="30"']],v=>{C.addSkill(a,v);event('skill learned',`${actorName}: ${v.name}`);}),
      'add-quest':()=>form('Mission',[['title','Title','','text','required'],['description','Brief','','textarea'],['objective','Current objective','','textarea']],v=>{s.quests.push({id:C.uid(),...v,status:'active'});event('quest',v.title);}),
      notices:()=>{const d=dialog('Notification history',s.notifications.slice().reverse().map(n=>`<article class="cps-rpg-skill"><h3>${E(n.title)}</h3>${note(n.body)}</article>`).join('')+s.shares.slice().reverse().map((x,i)=>`<article class="cps-rpg-skill"><h3>${E(x.title)}</h3>${note(x.description)}${buttons('Open',`received:${s.shares.length-1-i}`)}</article>`).join(''));d.querySelectorAll('[data-rpg^="received:"]').forEach(b=>b.onclick=()=>guard(()=>{const x=s.shares[Number(b.dataset.rpg.split(':')[1])];if(x.kind==='contact')addContact(x.contact);else detail(x.title,x.description||x.item?.name||'');}));},
      'unlock-relic':()=>{a.relic.unlocked=true;event('Relic','Manually unlocked for scenario');},'relic-point':()=>{if(!a.relic.unlocked)throw Error('Unlock Relic first');a.relic.points=C.cap(a.relic.points+1,0,99);event('Relic','Manual story award: 1 point');},
      'unlock-blackwall':()=>{a.blackwall.unlocked=true;event('Blackwall','Manually unlocked for scenario');},
      blackwall:()=>{if(!a.blackwall.unlocked||a.ram<4)throw Error('Blackwall locked or insufficient RAM');a.ram-=4;a.blackwall.exposure=C.cap(a.blackwall.exposure+20,0,100);a.stress=C.cap(a.stress+10,0,100);if(a.blackwall.exposure>=60){a.hp=C.cap(a.hp-15,0,a.maxHp);notify('BLACKWALL CONTAMINATION','Neural feedback: −15 health / +10 stress',true);}event('Blackwall',`${actorName} interfaces: exposure ${a.blackwall.exposure}`);},
      disconnect:()=>{a.blackwall.exposure=C.cap(a.blackwall.exposure-15,0,100);a.stress=C.cap(a.stress-5,0,100);s.turn++;event('Blackwall','Disconnected; recovered for one turn');},
    };
    if(actions[kind])actions[kind]();else if(kind==='equip'){C.equip(a,value);event('equipment',`${actorName}: equipment changed`);}else if(kind==='use'){const it=C.use(a,value,s.turn);event('item used',`${actorName}: ${it.name}`);localSkill(actorName,it.name,it.effect);notify('ABILITY / '+it.name,it.effect||`${actorName} activated ${it.name}`);}else if(kind==='edit-item')editItem(a.inventory.find(x=>x.id===value));
    else if(kind==='remove-item'){const it=a.inventory.find(x=>x.id===value);if(it){it.quantity--;a.inventory=a.inventory.filter(x=>x.quantity>0);event('equipment removed',`${actorName}: ${it.name}`);}}
    else if(kind==='share-item'){const it=a.inventory.find(x=>x.id===value);if(it)share({kind:'item',title:it.name,item:it,description:it.effect},'user',api.context()?.name1||'User');}
    else if(kind==='skill'){const sk=a.skills.find(x=>x.id===value);if(sk){C.useSkill(a,sk,s.turn);event('skill',`${actorName}: ${sk.name}`);localSkill(actorName,sk.name,sk.description);}}
    else if(kind==='quest'){const q=s.quests.find(x=>x.id===value);if(q){q.status={active:'completed',completed:'failed',failed:'active'}[q.status]||'active';event('quest',`${q.title}: ${q.status}`);}}
    else if(kind==='share-quest'){const q=s.quests.find(x=>x.id===value);if(q)share({kind:'mission',title:q.title,description:`${q.description}\n${q.objective}\n${q.status}`},'user',api.context()?.name1||'User');}
    else if(kind==='relic'){if(!a.relic.unlocked||a.relic.points<1||a.relic.abilities.includes(value))throw Error('Relic locked or no points');a.relic.points--;a.relic.abilities.push(value);if(value==='Jailbreak')a.capacity+=20;if(value==='Emergency Cloaking')C.addSkill(a,{name:value,cost:20,resource:'stamina',cooldown:3,description:'Break visual contact in the role-play scene.'});if(value==='Vulnerability Analytics')C.addSkill(a,{name:value,cost:2,resource:'ram',cooldown:2,description:'Analyze an observable weak point; does not reveal secrets.'});event('Relic',`${actorName}: ${value} unlocked`);}
    save();render();
  }
  function skillHtml(name,skill,description=''){return `<section class="cps-chat-block cps-chat-skill"><div class="cps-chat-kicker">${icon('quickhack')}<span>${E(name)}</span><small>SKILL ACTIVATED</small></div><strong>${E(skill)}</strong>${note(description)}</section>`;}
  function localSkill(name,skill,description){const s=state(),index=(api.context()?.chat?.length||0)-1;s.skillCards??=[];s.skillCards.push({id:C.uid(),index,name,skill,description});s.skillCards=s.skillCards.slice(-100);save();document.querySelectorAll('.mes_text').forEach(decorate);}
  function decorate(element){const index=Number(element.closest('[mesid]')?.getAttribute('mesid'));if(!element.closest('[mesid]')||!Number.isInteger(index))return;for(const card of state().skillCards||[]){if(card.index!==index||[...element.querySelectorAll('[data-local-skill]')].some(n=>n.dataset.localSkill===card.id))continue;const block=document.createElement('div');block.dataset.localSkill=card.id;block.innerHTML=skillHtml(card.name,card.skill,card.description);element.append(block);}}
  function decode(value){const n=document.createElement('div');n.innerHTML=value;return n.textContent||'';}
  function transform(value){let out=String(value||'').replace(/\[CP_SKILL\|([^\]|]+)\|([^\]]+)\]([\s\S]*?)\[\/CP_SKILL\]/gi,(_,name,skill,desc)=>skillHtml(decode(name),decode(skill),decode(desc)));
    out=out.replace(/\[CP_SKILL\]([\s\S]*?)\[\/CP_SKILL\]/gi,(_,json)=>{try{const v=JSON.parse(decode(json));return skillHtml(v.actor||'user',v.name||'Ability',v.description||'');}catch{return '';}});
    out=out.replace(new RegExp(`\\[CP_(${tags})\\](?:[\\s\\S]*?)\\[\\/CP_\\1\\]`,'gi'),'');
    // Streamed machine payloads (especially breach secrets) must never flash in chat.
    return out.replace(new RegExp(`\\[CP_(?:${tags})\\][\\s\\S]*$`,'gi'),'');
  }
  function process(raw,key=''){
    if(!api.settings().enabled)return;const s=state(),claimed=new Set(s.processed);
    const records=[...String(raw||'').matchAll(new RegExp(`\\[CP_(${tags})\\]([\\s\\S]*?)\\[\\/CP_\\1\\]`,'gi'))];
    for(const m of String(raw||'').matchAll(/\[CP_SKILL\|([^\]|]+)\|([^\]]+)\]([\s\S]*?)\[\/CP_SKILL\]/gi))records.push([m[0],'SKILL',JSON.stringify({actor:m[1],name:m[2],description:m[3]})]);
    const turnKey=`turn:${key}`;if(!claimed.has(turnKey)){claimed.add(turnKey);s.turn++;for(const a of [s.player,...Object.values(s.actors)]){const was=a.cyberpsychosis;C.tick(a,Math.random,s.settings.riskScale);if(!was&&a.cyberpsychosis)notify('NEURAL INSTABILITY','Cyberpsychosis episode: recover, reduce implant load or seek help in the story.',true);}}
    for(const m of records){let data;try{data=JSON.parse(m[2]);if(!data||Array.isArray(data)||typeof data!=='object')continue;}catch{continue;}
      const type=m[1].toUpperCase(),receipt=`record:${data.id?C.text(data.id,160):key+':'+type+':'+api.fingerprint(m[2])}`;if(claimed.has(receipt))continue;claimed.add(receipt);
      try{
        if(type==='SKILL'){const a=actor(data.actor||'user');C.useSkill(a,data,s.turn);event('skill',`${data.actor||'user'}: ${data.name}`);}
        if(type==='STATE'){const a=actor(data.actor||'user');for(const [field,max]of [['hp',a.maxHp],['ram',a.maxRam],['stamina',a.maxStamina],['stress',100]])if(data[field]!==undefined)a[field]=C.cap(data[field],0,max);}
        if(type==='ITEM'){const a=actor(data.actor||'user');if(data.operation==='remove'){const it=a.inventory.find(x=>x.id===data.itemId||x.catalogId===data.itemId);if(it){it.quantity-=Math.max(1,Math.round(C.cap(data.quantity??1,1,9999)));a.inventory=a.inventory.filter(x=>x.quantity>0);}}else if(data.item?.name){a.inventory.push(C.item(data.item));notify('EQUIPMENT RECEIVED',data.item.name);}}
        if(type==='TRANSFER'){if(!data.from||['user','player',api.context()?.name1].includes(data.from))throw Error('Player transfers require the Transfer button or /cp transfer command.');transfer(data.from,data.to||'user',data.amount,data.reason,receipt);}
        if(type==='SHARE')share({...data,id:receipt},'assistant',data.from||api.chatBucket().call.peer?.name||'System');
        if(type==='LOCATION')location(data);
        if(type==='QUEST'){if(!C.text(data.title))throw Error('Quest title missing');const q=s.quests.find(x=>x.id===data.questId||x.title===data.title);const v={id:q?.id||C.text(data.questId||C.uid(),160),title:C.text(data.title,180),description:C.text(data.description||q?.description,4000),objective:C.text(data.objective||q?.objective,1000),status:['active','completed','failed'].includes(data.status)?data.status:q?.status||'active'};if(q)Object.assign(q,v);else s.quests.push(v);notify('MISSION UPDATE',`${v.title}: ${v.status}\n${v.objective}`);}
        if(type==='BREACH'){if(api.settings().hackingEnabled)beginBreach({...data,id:receipt});}
        if(type==='RELIC'){const a=actor(data.actor||'user');if(data.unlock===true)a.relic.unlocked=true;if(a.relic.unlocked&&data.points!==undefined)a.relic.points=C.cap(a.relic.points+Math.round(C.cap(data.points,-10,10)),0,99);}
        if(type==='BLACKWALL'){const a=actor(data.actor||'user');if(data.unlock===true)a.blackwall.unlocked=true;if(a.blackwall.unlocked&&data.exposure!==undefined)a.blackwall.exposure=C.cap(a.blackwall.exposure+C.cap(data.exposure,-100,100),0,100);}
        if(type==='CALL_END'){const call=api.chatBucket().call;if(call.active&&C.handle(data.actor).toLowerCase()===C.handle(call.peer?.name).toLowerCase()){if(data.reason)api.appendCallMessage('system',call.peer.name,C.text(data.reason));api.endCall();}}
      }catch(e){notify('SYSTEM RECORD REJECTED',`${type}: ${e.message}`);}
    }
    // Nested notifications and transfers may save; commit the full claim set last.
    s.processed=[...new Set([...s.processed,...claimed])].slice(-3000);save();render();
  }
  function prompt(){if(!api.settings().enabled)return '';const s=state();const a=s.player;const summary=x=>({balance:x.balance,hp:x.hp,ram:x.ram,capacity:x.capacity,stress:x.stress,cyberpsychosis:x.cyberpsychosis,inventory:x.inventory.slice(0,30).map(it=>({id:it.id,name:it.name,quantity:it.quantity,equipped:it.equipped})),skills:x.skills.slice(0,15),relic:x.relic,blackwall:x.blackwall});
    const active=s.puzzle&&['ready','running'].includes(s.puzzle.status);
    return `\n[Cyberware role-play state and event protocol]
This is fictional simulation only. Values are extension rules, not exact game balance. State is private narrator context; NPCs do not automatically know the player's balance, equipment, thoughts, location, hidden missions or other NPCs' information. No unearned powers or forced plot. Never simulate puzzle success: the user must play it.
Emit complete JSON records only for events that actually happen. Each record needs an id unique to that event; reuse that id if restating the same event. Do not print examples unless that event occurs. JSON strings must escape newlines and quotes. Never include closing tag text inside a JSON string.
- Show every actual ability use by USER or NPC with [CP_SKILL]{"id":"event-id","actor":"user or exact NPC name","name":"skill","description":"observable effect","resource":"ram or stamina","cost":2,"cooldown":1}[/CP_SKILL]. Do not invent user actions. Existing skill costs/cooldowns are authoritative. No repeated skill record for one action.
- When a scene requires decrypting an access point or shard: [CP_BREACH]{"id":"event-id","target":"terminal name","difficulty":2,"seconds":45,"buffer":8,"data":"data unlocked ONLY on success"}[/CP_BREACH]. Stop before revealing its secrets. Not an enemy quickhack.
- State updates: [CP_STATE]{"id":"event-id","actor":"user or exact NPC","hp":80,"stress":10}[/CP_STATE]. Only changed hp/ram/stamina/stress; omit unspecified fields. Do not change balance here.
- NPC pays another stored contact or user: [CP_TRANSFER]{"id":"event-id","from":"exact NPC","to":"user","amount":100,"reason":"..."}[/CP_TRANSFER]. Insufficient balances reject. Never debit user; ask the user to use Transfer or /cp transfer @handle AMOUNT. A narration is not a completed transfer.
- Equipment acquired/lost: [CP_ITEM]{"id":"event-id","actor":"user","operation":"add","item":{"name":"...","category":"cyberware/weapons/quickhack/consumable/clothing/mod/component/data/item","quantity":1,"slot":"...","capacity":15,"effect":"..."}}[/CP_ITEM]. Remove uses operation remove, itemId and quantity. Do not re-add equipped objects every turn.
- Attach a card inside a call or notifications: [CP_SHARE]{"id":"event-id","from":"NPC name","kind":"location/mission/item/contact/data","title":"...","description":"..."}[/CP_SHARE]. kind must be ONE enum value. For item add item object as above. For contact add contact object containing ALL nonempty fields: name, handle WITHOUT @, role, status, affiliation, age, gender, personality, appearance, notes; optional balance (nonnegative integer) and inventory (full item objects). Invent a coherent complete fictional profile when introducing a new contact; never merely create a name/handle stub. User clicks Add contact to accept.
- NPC may end its active call: [CP_CALL_END]{"id":"event-id","actor":"exact active caller name","reason":"..."}[/CP_CALL_END]. Use AFTER final CP_SIGNAL/attachments.
- Location change: [CP_LOCATION]{"id":"event-id","district":"watson/westbrook/city-center/heywood/santo-domingo/pacifica/badlands (choose ONE)","subdistrict":"...","building":"...","floor":"...","area":"...","danger":false,"reason":"..."}[/CP_LOCATION]. Use actual established narrative location, not guesses; can trigger dangerous-zone alert.
- Mission updates: [CP_QUEST]{"id":"event-id","questId":"stable quest id","title":"...","description":"...","objective":"...","status":"active/completed/failed (choose ONE)"}[/CP_QUEST].
- Only when story earned: [CP_RELIC]{"id":"event-id","actor":"user","unlock":true,"points":1}[/CP_RELIC] or [CP_BLACKWALL]{"id":"event-id","actor":"user","unlock":true,"exposure":10}[/CP_BLACKWALL]. Do not award repeatedly. Blackwall/Relic are optional scenario mechanics, avoid story spoilers.
Private player state: ${JSON.stringify(summary(a))}
Stored NPC assets (private narrator context): ${JSON.stringify(api.effectiveRecords('npcs').slice(0,20).map(n=>({name:n.name,...summary(actor(n.name))})))}
Location: ${JSON.stringify(s.map.location)}
Active missions: ${JSON.stringify(s.quests.filter(q=>q.status==='active').slice(-10))}
Pending breach: ${active?JSON.stringify({target:s.puzzle.target,status:s.puzzle.status}):'none'}
Recent authoritative outcomes (do not replay records for these): ${JSON.stringify(s.events.slice(-12))}`;
  }
  function ensureWand(){const host=document.getElementById('extensionsMenu'),old=document.getElementById('cyberpunk-cyberware-wand');if(!api.settings().showWand){old?.remove();return;}if(!host||old)return;const b=document.createElement('div');b.id='cyberpunk-cyberware-wand';b.className='list-group-item flex-container flexGap5 interactable';b.tabIndex=0;b.setAttribute('role','button');b.innerHTML='<i class="fa-solid fa-microchip fa-fw"></i><span>Cyberware</span>';b.onclick=e=>{e.preventDefault();e.stopPropagation();api.closeHostWand();open();};b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();b.click();}};host.append(b);}
  function onChatChanged(){document.querySelectorAll('.cps-rpg-dialog').forEach(api.removeUiDialog);closePanel();stopBreach();api.removeUiDialog(popup);popup=null;noticeTimers.forEach(clearTimeout);noticeTimers.clear();document.getElementById('cps-immersion')?.remove();minimized();}
  return Object.freeze({open,process,prompt,transform,decorate,ensureWand,callToolbar,attachment,userText,onChatChanged,beginBreach,state:()=>JSON.parse(JSON.stringify(state())),transfer,share,addContact,icon});
};
})();
