/* Recovery and request tooling. All records remain inside the current ST chat. */
(() => {
'use strict';
const copy=v=>JSON.parse(JSON.stringify(v));
globalThis.CyberpunkSupportFactory=api=>{
  const E=api.htmlEscape,C=globalThis.CyberpunkRpgCore,tr=(a,b)=>api.settings().language==='th'?b:a;
  let panel=null,tick=null;const jobs=new Map();
  const s=()=>api.state(),save=()=>{api.saveChat();api.refreshPrompt();};
  const recovery=()=>{const b=api.chatBucket();b.recovery??={snapshots:[]};return b.recovery;};
  function payload(){const {recovery:unused,...data}=api.chatBucket();return {format:'cyberpunk-system-backup',schema:1,createdAt:new Date().toISOString(),persona:api.context()?.name1||'USER',chat:copy(data),character:copy(api.characterBucket?.()||{})};}
  function validate(value){
    if(!value||value.format!=='cyberpunk-system-backup'||value.schema!==1||!value.chat?.rpg?.player)throw Error('Unsupported backup format');
    const object=v=>v&&typeof v==='object'&&!Array.isArray(v);if(!object(value.chat)||!object(value.chat.rpg)||!object(value.chat.rpg.player)||value.character!==undefined&&!object(value.character))throw Error('Invalid backup object');
    const visit=(v,depth=0)=>{if(depth>50)throw Error('Backup nesting too deep');if(v&&typeof v==='object')for(const [k,x] of Object.entries(v)){if(['__proto__','prototype','constructor'].includes(k))throw Error('Unsafe backup key');visit(x,depth+1);}};visit(value);
    for(const bucket of [value.chat,value.character||{}])for(const k of ['npcs','skills'])if(bucket[k]!==undefined&&!Array.isArray(bucket[k]))throw Error('Invalid backup '+k);
    const r=value.chat.rpg;for(const k of ['quests','properties','vehicles','processed','events','recordLog','recordReceipts','failedReceipts','requests','assetReceipts'])if(r[k]!==undefined&&!Array.isArray(r[k]))throw Error('Invalid backup '+k);
    if(r.deviceSystem!==undefined){
      const b=r.deviceSystem;if(!object(b)||!Number.isInteger(b.slotCount)||b.slotCount<1||b.slotCount>16||!Number.isSafeInteger(b.visit)||b.visit<0||typeof b.location!=='string'||typeof b.enabled!=='boolean')throw Error('Invalid device settings');
      const ids=['shutdown','loop','view','unlock','lock','jam','retarget','read','reboot'];
      if(!Array.isArray(b.slots)||b.slots.length!==b.slotCount||b.slots.some(id=>id!==null&&!ids.includes(id))||new Set(b.slots.filter(Boolean)).size!==b.slots.filter(Boolean).length)throw Error('Invalid device slots');
      if(!Array.isArray(b.devices)||b.devices.length>300||new Set(b.devices.map(d=>d?.id)).size!==b.devices.length)throw Error('Invalid device registry');
      for(const d of b.devices){if(!object(d)||typeof d.id!=='string'||!d.id||typeof d.name!=='string'||!['camera','door','drone','turret','terminal','device'].includes(d.type)||!['online','offline','destroyed'].includes(d.status)||!['open','secured'].includes(d.access)||typeof d.location!=='string'||!Number.isSafeInteger(d.visit)||typeof d.reachable!=='boolean'||typeof d.revision!=='string'||typeof d.networkId!=='string'||!Array.isArray(d.actions)||d.actions.some(id=>!ids.includes(id))||!Array.isArray(d.effects)||d.effects.some(e=>!object(e)||!ids.includes(e.id)||!Number.isSafeInteger(e.until)||e.until<0))throw Error('Invalid saved device');}
      for(const d of b.devices)if(d.requestedProgram!==undefined&&!ids.includes(d.requestedProgram))throw Error('Invalid requested device program');
      for(const k of ['receipts','grants'])if(!Array.isArray(b[k])||b[k].some(v=>typeof v!=='string'))throw Error('Invalid device '+k);
      if(!object(b.cooldowns)||Object.entries(b.cooldowns).some(([id,turn])=>!ids.includes(id)||!Number.isSafeInteger(turn)||turn<0))throw Error('Invalid device cooldowns');
    }
    if(r.market!==undefined){
      const b=r.market,validId=v=>typeof v==='string'&&/^[a-zA-Z0-9_.:-]{1,140}$/.test(v)&&!['__proto__','prototype','constructor'].includes(v),qty=v=>Number.isInteger(v)&&v>=0&&v<=9999;
      const categories=['clothing','weapons','essentials','medicine','equipment','cyberware','quickhack','ammo','other'];
      if(!object(b)||!Array.isArray(b.shops)||b.shops.length>200||new Set(b.shops.map(x=>x?.id)).size!==b.shops.length||!Array.isArray(b.receipts)||b.receipts.some(v=>typeof v!=='string'))throw Error('Invalid shop registry');
      for(const shop of b.shops){
        if(shop.pendingStock!==undefined&&(!Array.isArray(shop.pendingStock)||shop.pendingStock.length>80||shop.pendingStock.some(x=>!object(x)||!object(x.input)||typeof x.reason!=='string')))throw Error('Invalid pending shop goods');
        if(!object(shop)||!validId(shop.id)||typeof shop.name!=='string'||!shop.name||typeof shop.merchant!=='string'||!object(shop.location)||!shop.location.building||!shop.location.area||!Number.isSafeInteger(shop.version)||shop.version<1||!Array.isArray(shop.history)||!Array.isArray(shop.stock)||shop.stock.length>200||new Set(shop.stock.map(x=>x?.id)).size!==shop.stock.length||!object(shop.buyPrices))throw Error('Invalid saved shop');
        if(!Number.isSafeInteger(shop.funds))throw Error('Invalid shop funds');C.money(shop.funds);for(const [key,price]of Object.entries(shop.buyPrices)){if(!categories.includes(key)||!Number.isSafeInteger(price))throw Error('Invalid shop buyback category or price');C.money(price);}
        for(const row of shop.stock){if(!object(row)||!validId(row.id)||!qty(row.quantity)||!categories.includes(row.category)||!object(row.item)||typeof row.item.name!=='string'||!row.item.name||!['catalog','story','resale'].includes(row.origin))throw Error('Invalid shop stock');if(!Number.isSafeInteger(row.price)||!Number.isSafeInteger(row.buyPrice)||C.money(row.price)<1||C.money(row.buyPrice)>row.price)throw Error('Invalid shop prices');}
        if(shop.visit){const v=shop.visit;if(!object(v)||typeof v.id!=='string'||!validId(v.recordId)||v.shopId!==shop.id||typeof v.active!=='boolean'||!Number.isSafeInteger(v.index)||v.index<0||!Number.isSafeInteger(v.swipe)||v.swipe<0)throw Error('Invalid shop visit');}
        if(shop.history.some(x=>!object(x)||typeof x.id!=='string'||typeof x.kind!=='string'||!Number.isFinite(x.at)))throw Error('Invalid shop history');
      }
    }
    C.money(r.player.balance);if(!Array.isArray(r.player.inventory))throw Error('Invalid inventory');
    for(const a of [r.player,...Object.values(r.actors||{}),...Object.values(r.merchants||{})]){if(!object(a)||!Number.isSafeInteger(a.balance))throw Error('Invalid actor balance');C.money(a.balance);if(!Array.isArray(a.inventory))throw Error('Invalid actor inventory');for(const i of a.inventory){if(!i?.id||!i.name||!Number.isInteger(i.quantity)||i.quantity<1||i.quantity>9999)throw Error('Invalid saved item');}}
    if(r.mailbox&&(!Array.isArray(r.mailbox.documents)||!Array.isArray(r.mailbox.seen)||!r.mailbox.offers||Array.isArray(r.mailbox.offers)||(r.mailbox.trash!==undefined&&!Array.isArray(r.mailbox.trash))))throw Error('Invalid mailbox');
    for(const doc of [...r.mailbox?.documents||[],...r.mailbox?.trash||[]])if(!doc.id||typeof doc.subject!=='string'||typeof doc.body!=='string'||typeof doc.at!=='string'||!Number.isFinite(Date.parse(doc.at)))throw Error('Invalid saved document');
    for(const a of [...r.properties||[],...r.vehicles||[]]){if(!a.id||!a.name||a.storage!==undefined&&!Array.isArray(a.storage))throw Error('Invalid saved asset');for(const i of a.storage||[])if(!i.id||!i.name||!Number.isInteger(i.quantity)||i.quantity<1||i.quantity>9999)throw Error('Invalid stored item');for(const level of Object.values(a.upgrades||{}))if(!Number.isInteger(level)||level<0||level>5)throw Error('Invalid upgrade level');for(const key of ['condition','fuel'])if(a[key]!==undefined&&(!Number.isFinite(a[key])||a[key]<0||a[key]>100))throw Error('Invalid vehicle '+key);}
    return copy(value);
  }
  function checkpoint(label='Manual checkpoint'){const p=payload(),r=recovery(),bytes=JSON.stringify(p).length*2,budget=12*1024*1024;if(bytes>budget)throw Error('State exceeds the local checkpoint budget; export a backup instead');r.snapshots.push({id:C.uid(),label:C.text(label,180),at:Date.now(),bytes,payload:p});r.snapshots=r.snapshots.slice(-5);while(r.snapshots.length>1&&r.snapshots.reduce((n,x)=>n+(x.bytes||JSON.stringify(x.payload).length*2),0)>budget)r.snapshots.shift();api.saveChat();return r.snapshots.at(-1);}
  function restore(value,includeCharacter=false){
    if(jobs.size||api.isGenerating?.()||api.busy?.())throw Error('Cancel generation before restoring');
    const v=validate(value),owner=api.chatBucket();checkpoint('Before restore');api.closeWorkspaces?.();
    const keep=owner.recovery;for(const k of Object.keys(owner))if(k!=='recovery')delete owner[k];Object.assign(owner,v.chat);owner.recovery=keep;
    if(owner.call){owner.call.active=false;owner.call.minimized=false;}if(owner.rpg?.bd){owner.rpg.bd.status='stopped';owner.rpg.bd.rendering=false;}if(owner.rpg?.puzzle)owner.rpg.puzzle.status='cancelled';for(const row of owner.rpg.requests||[])if(row.status==='running'){row.status='cancelled';row.ended=Date.now();row.error='Restored checkpoint; retry explicitly';}
    for(const shop of owner.rpg.market?.shops||[])if(shop.visit){shop.visit.active=false;shop.visit.reason='Restored checkpoint; return to the shop for a new visit';}
    if(includeCharacter&&api.characterBucket){const target=api.characterBucket();for(const k of Object.keys(target))delete target[k];Object.assign(target,v.character||{});api.saveSettings?.();}
    save();return true;
  }
  function request(kind,execute,options={}){
    if(jobs.size)throw Error('Another extension request is running');
    const owner=api.chatBucket(),ctx=api.context(),started=Date.now(),id=C.uid(),seconds=Math.max(15,Math.min(600,s().settings.requestTimeout||120));
    const row={id,kind,status:'running',started};s().requests??=[];s().requests.push(row);s().requests=s().requests.slice(-50);api.saveChat();
    let rejectAbort,clock;const aborted=new Promise((_,reject)=>{rejectAbort=reject;});
    const fail=(status,message)=>{if(!jobs.has(kind)||row.status!=='running')return;row.status=status;row.error=message;try{ctx?.stopGeneration?.();}catch{}rejectAbort(Error(message));};
    jobs.set(kind,{row,cancel:()=>fail('cancelled','Cancelled; your draft is retained')});
    clock=setTimeout(()=>fail('timeout',`Request timed out after ${seconds}s. Retry explicitly; no automatic duplicate request was sent.`),options.timeoutMs??seconds*1000);
    let transport;try{transport=execute();}catch(e){transport=Promise.reject(e);}
    return Promise.race([transport,aborted]).then(value=>{if(owner!==api.chatBucket())throw Error('Chat changed; result ignored');row.status='completed';return value;}).catch(e=>{if(row.status==='running'){row.status='failed';row.error=C.text(e.message,600);}throw e;}).finally(()=>{clearTimeout(clock);row.ended=Date.now();jobs.delete(kind);if(owner===api.chatBucket())api.saveChat();});
  }
  const cancel=kind=>{const job=jobs.get(kind);if(!job)return false;job.cancel();return true;};
  const cancelAll=()=>[...jobs.keys()].forEach(cancel);
  function open(){
    api.removeUiDialog(panel);clearInterval(tick);const owner=api.chatBucket();panel=api.dialog(tr('System / Recovery','ระบบ / กู้คืน'),'<div class="cps-support"></div>','cps-support-window');const current=panel,host=panel.querySelector('.cps-support');let filter='failed';
    const button=(key,label)=>`<button type="button" class="cps-button" data-support="${E(key)}">${E(label)}</button>`;
    const draw=()=>{if(!current.isConnected||owner!==api.chatBucket()){clearInterval(tick);return;}const logs=s().recordLog||[],entries=logs.filter(x=>filter==='all'||x.status===filter).slice(-60).reverse();
      host.innerHTML=`<header class="cps-support-hero"><small>INTEGRITY / CONTROL CENTER</small><h2>${E(tr('Every action, accounted for.','ตรวจสอบทุกการเปลี่ยนแปลง'))}</h2><p>${E(tr('Review failed story records, manage AI requests and keep recovery points.','ตรวจรายการจากเรื่องที่ล้มเหลว จัดการคำขอ AI และเก็บจุดกู้คืน'))}</p></header><section class="cps-support-section"><h3>${E(tr('AI request monitor','ติดตามคำขอ AI'))}</h3><div data-request-live></div><label>${E(tr('Timeout (seconds)','หมดเวลาหลัง (วินาที)'))}<input type="number" data-timeout min="15" max="600" value="${s().settings.requestTimeout||120}"></label><p>${E(tr('Retry from the original mail, call or AI channel after reviewing the error. No automatic retry.','ลองใหม่จากเมล สาย หรือช่อง AI เดิมหลังอ่านข้อผิดพลาด ระบบไม่ส่งซ้ำเอง'))}</p></section><section class="cps-support-section"><h3>${E(tr('Recovery vault','คลังกู้คืน'))}</h3><div class="cps-rpg-actions">${button('checkpoint',tr('Save checkpoint','เก็บจุดกู้คืน'))}${button('export',tr('Export backup','ส่งออกสำรอง'))}</div><label>${E(tr('Import backup JSON (max 25 MB)','นำเข้าไฟล์สำรอง JSON (สูงสุด 25 MB)'))}<input type="file" accept="application/json,.json" data-import></label><p>${E(tr('Restores extension state only, not SillyTavern messages. A pre-restore checkpoint is kept. Up to five local checkpoints within a 12 MB budget; download important backups.','กู้คืนเฉพาะข้อมูล extension ไม่ย้อนข้อความ SillyTavern เก็บจุดก่อนกู้คืนให้อัตโนมัติ เก็บได้สูงสุด 5 จุด ภายในงบ 12 MB ควรดาวน์โหลดสำรองสำคัญ'))}</p>${recovery().snapshots.slice().reverse().map(x=>`<div class="cps-recovery-row"><span>${E(x.label)}<small>${E(new Date(x.at).toLocaleString())}</small></span>${button('restore:'+x.id,tr('Review restore','ตรวจและกู้คืน'))}</div>`).join('')}</section><section class="cps-support-section"><h3>${E(tr('Story record inspector','ตรวจรายการจากเนื้อเรื่อง'))}</h3><select data-record-filter><option value="failed">Failed / ล้มเหลว</option><option value="succeeded">Succeeded / สำเร็จ</option><option value="all">All / ทั้งหมด</option></select>${entries.map(x=>`<details class="cps-record"><summary><b>${E(x.type)}</b> <span class="cps-record-status">${E(x.status)}</span> ${E(x.error||x.key)}</summary><p>${E(x.error||'Committed')}</p><small>${E(x.key)} · ${x.attempts||1} attempts</small><pre>${E(x.raw)}</pre>${x.status==='failed'?button('retry:'+x.key,tr('Review & retry','ตรวจและลองใหม่')):''}</details>`).join('')||'<p>No matching records / ไม่มีรายการ</p>'}</section><p role="alert" data-support-error></p>`;
      host.querySelector('[data-record-filter]').value=filter;host.querySelector('[data-record-filter]').onchange=e=>{filter=e.target.value;draw();};host.querySelector('[data-timeout]').onchange=e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=15&&n<=600){s().settings.requestTimeout=n;save();}else e.target.value=s().settings.requestTimeout||120;};
      const review=value=>{const v=validate(value);const d=api.dialog(tr('Review restore','ตรวจข้อมูลก่อนกู้คืน'),`<div class="cps-support-section"><h3>${E(v.persona)}</h3><p>${E(v.createdAt)} · €$${v.chat.rpg.player.balance} · ${v.chat.rpg.player.inventory.length} items</p><p>NPCs: ${v.chat.npcs?.length||0} · Mail: ${v.chat.rpg.mailbox?.documents.length||0} · Quests: ${v.chat.rpg.quests?.length||0}</p><label><input type="checkbox" data-character> ${E(tr('Also replace current character-scoped NPCs/skills (affects other chats for this character)','แทนที่ NPC/ทักษะขอบเขตตัวละครด้วย (มีผลกับแชตอื่นของตัวละครนี้)'))}</label><p>${E(tr('Replace the current extension timeline? Story messages and scene HUD snapshots are not rewound.','แทนข้อมูล extension ปัจจุบันหรือไม่? ข้อความเรื่องและภาพสถานะเก่าจะไม่ย้อนตาม'))}</p><button class="cps-button" data-confirm-restore>${E(tr('Confirm restore','ยืนยันกู้คืน'))}</button><p role="alert"></p></div>`);d.querySelector('[data-confirm-restore]').onclick=()=>{try{if(owner!==api.chatBucket())throw Error('Chat changed');restore(v,d.querySelector('[data-character]').checked);api.removeUiDialog(d);open();}catch(e){d.querySelector('[role=alert]').textContent=e.message;}};};
      host.querySelector('[data-import]').onchange=async e=>{try{const f=e.target.files?.[0];if(!f)return;if(f.size>25*1024*1024)throw Error('Backup exceeds 25 MB');const v=JSON.parse(await f.text());if(owner===api.chatBucket()&&current.isConnected)review(v);}catch(err){host.querySelector('[data-support-error]').textContent=err.message;}};
      host.querySelectorAll('[data-support]').forEach(b=>b.onclick=()=>{try{if(owner!==api.chatBucket())return;const [action,...rest]=b.dataset.support.split(':'),id=rest.join(':');if(action==='checkpoint'){checkpoint();draw();}if(action==='restore')review(recovery().snapshots.find(x=>x.id===id).payload);if(action==='export'){const url=URL.createObjectURL(new Blob([JSON.stringify(payload(),null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='cyberpunk-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}if(action==='retry'){const row=logs.find(x=>x.key===id);const d=api.dialog(tr('Review failed event','ตรวจรายการล้มเหลว'),`<form class="cps-support-section"><p>${E(row.error)}</p><textarea rows="12" name="raw">${E(row.raw)}</textarea><p>${E(tr('Only this failed event ID can be retried. Successful events cannot run again. Review any currency or item changes.','ลองใหม่ได้เฉพาะ ID ที่ล้มเหลวนี้ รายการสำเร็จจะไม่ทำซ้ำ ตรวจยอดเงินและไอเท็มก่อน'))}</p><button class="cps-button" type="submit">${E(tr('Confirm retry','ยืนยันลองใหม่'))}</button><p role="alert"></p></form>`);d.querySelector('form').onsubmit=e=>{e.preventDefault();try{if(owner!==api.chatBucket())throw Error('Chat changed');api.retry(id,e.currentTarget.elements.raw.value);api.removeUiDialog(d);draw();}catch(err){d.querySelector('[role=alert]').textContent=err.message;}};}}catch(e){host.querySelector('[data-support-error]').textContent=e.message;}});live();
    };
    const live=()=>{if(!current.isConnected||owner!==api.chatBucket()){clearInterval(tick);return;}const el=host.querySelector('[data-request-live]');if(!el)return;el.innerHTML=(s().requests||[]).slice(-5).reverse().map(r=>`<div class="cps-request-row"><span>${E(r.kind)} / ${E(r.status)} · ${Math.round(((r.ended||Date.now())-r.started)/1000)}s<small>${E(r.error||'')}</small></span>${r.status==='running'?button('cancel:'+r.kind,tr('Cancel','ยกเลิก')):''}</div>`).join('')||'<p>IDLE / พร้อม</p>';el.querySelectorAll('[data-support]').forEach(b=>b.onclick=()=>cancel(b.dataset.support.slice(7)));};draw();tick=setInterval(live,1000);
  }
  function close(){cancelAll();clearInterval(tick);api.removeUiDialog(panel);panel=null;}
  return {open,payload,validate,checkpoint,restore,request,cancel,cancelAll,close,busy:()=>jobs.size>0};
};
})();
