/* Cyberpunk role-play systems. All state stays with the current ST chat. */
(() => {
'use strict';
globalThis.CyberpunkSystemsFactory = api => {
  const C=globalThis.CyberpunkRpgCore, DB=globalThis.CyberpunkCatalog, E=api.htmlEscape;
  const tr=(en,th)=>api.settings?.()?.language==='th'?th:en;
  let panel=null, breach=null, timer=null, actorName='user', tab='status', popup=null, mapCleanup=null;
  const noticeTimers=new Map();
  const tags='STATE|SKILL|BREACH|TRANSFER|SHARE|CALL_END|LOCATION|QUEST|ITEM|RELIC|BLACKWALL';
  const buttons=(label,action,extra='')=>`<button type="button" class="cps-button" data-rpg="${action}" ${extra}>${E(label)}</button>`;
  const note=v=>`<p class="cps-rpg-note">${E(v)}</p>`;
  function state(){
    const b=api.chatBucket();
    if(!b.rpg||typeof b.rpg!=='object')b.rpg={};const s=b.rpg;
    s.player=C.hydrate(s.player);s.actors??={};s.turn??=0;s.settings??={riskScale:1,notifications:true,noticeSeconds:6};
    for(const k of ['events','processed','notifications','quests','shares'])if(!Array.isArray(s[k]))s[k]=[];
    s.map??={location:{district:'',subdistrict:'',building:'',floor:'',area:''},discovered:[],completed:[]};
    return s;
  }
  function actor(name='user'){
    if(['user','player',api.context()?.name1].includes(name))return state().player;
    const npc=api.findEffectiveNpc(C.handle(name));if(!npc)throw Error(tr('Unknown contact','ไม่พบผู้ติดต่อ'));
    // NPC identity follows scope; mutable economy is isolated per chat, including group chats.
    const key=`npc:${npc.id||npc.name.toLowerCase()}`;state().actors[key]=C.hydrate(state().actors[key]);return state().actors[key];
  }
  const save=()=>{api.saveChat();api.refreshPrompt();};
  function event(type,detail){const s=state();s.events.push({id:C.uid(),turn:s.turn,type,detail:C.text(detail,1200)});s.events=s.events.slice(-50);save();}
  function guard(fn){try{return fn();}catch(e){api.toast(e.message);return null;}}
  function closePanel(){mapCleanup?.();mapCleanup=null;api.removeUiDialog(panel);panel=null;}
  function dialog(title,body,cls=''){
    const d=document.createElement('dialog');d.className=`cps-ui cps-rpg-dialog ${cls}`;d.setAttribute('aria-label',title);
    d.innerHTML=`<header class="cps-rpg-top"><span class="cps-eyebrow">NEURAL INTERFACE / v${E(api.version || '2.4.0')}</span><h2>${E(title)}</h2>${buttons('×','close','aria-label="Close"')}</header><div class="cps-rpg-content">${body}</div>`;
    d.querySelector('[data-rpg="close"]').onclick=()=>api.removeUiDialog(d);d.addEventListener('cancel',e=>{e.preventDefault();api.removeUiDialog(d);});document.body.append(d);api.showUiDialog(d);return d;
  }
  function detail(title,content){api.removeUiDialog(popup);popup=dialog(title,`<div class="cps-rpg-detail">${E(content)}</div>`);}
  function notify(title,body,danger=false){
    const s=state(),n={id:C.uid(),title:C.text(title,180),body:C.text(body,3000),danger,at:Date.now()};s.notifications.push(n);s.notifications=s.notifications.slice(-60);save();
    if(!s.settings.notifications||(breach&&/^ACCESS (GRANTED|DENIED)$/.test(title)))return;
    let host=document.getElementById('cps-immersion');if(!host){host=document.createElement('aside');host.id='cps-immersion';host.setAttribute('aria-live','polite');document.body.append(host);if(typeof host.showPopover==='function'){host.setAttribute('popover','manual');try{host.showPopover();}catch{}}else document.querySelector('dialog.cps-ui[open]:last-of-type')?.append(host);}
    const b=document.createElement('button');b.className=`cps-immersion-card ${danger?'danger':''}`;b.type='button';b.innerHTML=`<small>${danger?'⚠ RESTRICTED ZONE':'◆ INCOMING DATA'}</small><strong>${E(n.title)}</strong><span>${E(tr('Tap for details','แตะดูรายละเอียด'))}</span>`;
    b.onclick=()=>{detail(n.title,n.body);remove();};const remove=()=>{clearTimeout(noticeTimers.get(n.id));noticeTimers.delete(n.id);b.remove();};
    const schedule=()=>{clearTimeout(noticeTimers.get(n.id));noticeTimers.set(n.id,setTimeout(remove,C.cap(s.settings.noticeSeconds,2,60)*1000));};
    b.onpointerenter=b.onfocus=()=>clearTimeout(noticeTimers.get(n.id));b.onpointerleave=b.onblur=schedule;
    host.append(b);while(host.children.length>3)host.firstElementChild.remove();schedule();
  }
  function icon(category='item',variant=''){
    const paths={cyberware:'M32 13v10m0 18v10M13 32h10m18 0h10M22 22h20v20H22zM28 28h8v8h-8z',weapons:'M12 23h36v10H33l-5 15H17l4-15h-9zM39 19v4',quickhack:'M36 9 17 35h14l-3 20 20-29H33z',consumable:'M25 12h14v12h12v16H39v12H25V40H13V24h12z',clothing:'M22 13l10 6 10-6 14 12-9 10-5-5v22H22V30l-5 5-9-10z',data:'M18 9h21l9 10v36H18zM38 9v12h10M25 30h15M25 38h15M25 46h9',mod:'M32 10l7 10h12v24H39L32 54l-7-10H13V20h12zM26 26h12v12H26z',component:'M32 10 52 22v22L32 56 12 44V22zM12 22l20 12 20-12M32 34v22',item:'M13 20h38v32H13zM24 20v-8h16v8M13 32h38'};
    const name=String(variant).toLowerCase();
    const special=/gorilla/.test(name)?'M18 50V31l-5-6q-3-6 2-8l7 8V12q0-5 5-3v16V10q1-5 6-1v16V12q3-4 6 0v15V17q4-3 6 2v21l-6 10v6H23v-6zM24 35h15M25 42h13':/mantis|katana|kukri/.test(name)?'M12 53l8-8M17 39l9 9M22 41 49 10q-1 16-24 34M31 37l-4-4':/monowire/.test(name)?'M18 46h12v10H18zM24 46V30C4 19 23 3 37 13S55 36 43 37 25 21 40 20M19 50h10':/kiroshi|optic/.test(name)?'M7 32q25-31 50 0-25 31-50 0zM41 32a9 9 0 1 1-18 0 9 9 0 1 1 18 0M28 32h8M32 28v8':/blood|heart|biomonitor/.test(name)?'M32 53 12 34C-1 12 23 4 32 21 41 4 65 12 52 34Z M12 31h11l5-10 7 21 5-11h12':/carnage|crusher|tactician|satara|copperhead|masamune|ajax|kyubi|defender|pulsar|saratoga|nekomata|grad|ashura|erebus/.test(name)?'M5 24h44v4h10v5H35l-3 11h-8l3-11H15L8 41H4V29zM38 20v4M16 24v9M42 28h8M19 18h14v6':/tendon|ankle|paws/.test(name)?'M25 8h15l-4 26 4 11 12 6v5H25l-6-8 5-18zM24 31h12M24 43h14M29 12v14':/armor|camo|skin/.test(name)?'M32 6 51 15v19Q49 48 32 58 15 48 13 34V15zM23 19l9-5 9 5v17l-9 11-9-11z':null;
    return `<svg class="cps-item-image" viewBox="0 0 64 64" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="${special||paths[category]||paths.item}"/></svg>`;
  }
  function itemImage(it){return it.image&&/^data:image\/(png|jpeg|webp);base64,[a-z0-9+/=]+$/i.test(it.image)&&it.image.length<500000?`<img class="cps-item-image" src="${E(it.image)}" alt="">`:icon(it.category,it.name);}
  const sections=[['status','Status','สถานะ','consumable'],['cyberware','Cyberware','ไซเบอร์แวร์','cyberware'],['weapons','Weapons','อาวุธ','weapons'],['balance','Balance','บัญชี','component'],['inventory','Inventory','คลังอุปกรณ์','item'],['skills','Skills / Hacking','ทักษะ / แฮ็ก','quickhack'],['quests','Missions / Quests','ภารกิจ','data'],['map','Night City','แผนที่','mod'],['relic','Relic / Blackwall','Relic / Blackwall','cyberware'],['settings','Settings','ตั้งค่า','mod']];
  const sectionTitle=key=>{const s=sections.find(x=>x[0]===key);return s?tr(s[1],s[2]):key;};
  function meter(label,value,maximum,kind='') {
    const max=Math.max(1,Number(maximum)||1),v=Math.max(0,Number(value)||0),percent=C.cap(v/max*100,0,100);
    kind=kind||({'HEALTH':'health','STAMINA':'stamina','RAM':'ram','CYBERWARE':'capacity','STRESS':'stress','RELIC POINTS':'relic','BLACKWALL EXPOSURE':'blackwall'}[label]||'capacity');
    const count=kind==='ram'?Math.min(24,Math.ceil(max)):kind==='relic'?10:20;
    return `<div class="cps-rpg-meter cps-hud-meter ${kind} ${v>max?'overload':''}" data-vital="${kind}"><div class="cps-hud-meter-head"><span>${E(label)}</span><div><b>${Math.round(v)}</b><small>/ ${Math.round(max)}</small></div></div><div class="cps-hud-track" role="progressbar" aria-label="${E(label)}" aria-valuemin="0" aria-valuemax="${max}" aria-valuenow="${Math.min(v,max)}" aria-valuetext="${Math.round(v)} / ${max}${v>max?' · over capacity':''}" style="--hud-level:${percent}%;--hud-segments:${count}"><div class="cps-hud-fill"></div><div class="cps-hud-divisions" aria-hidden="true"></div></div><div class="cps-hud-meter-foot"><span>${kind==='ram'?tr('MEMORY UNITS','หน่วยความจำ'):kind==='health'?tr('VITAL SIGNS','สัญญาณชีพ'):v>max?tr('OVER CAPACITY','เกินขีดจำกัด'):tr('NEURAL TELEMETRY','การตรวจวัดประสาท')}</span><span>${Math.round(v/max*100)}%</span></div></div>`;
  }
  function heading(kicker,title,meta=''){return `<header class="cps-section-heading"><div><small>${E(kicker)}</small><h3>${E(title)}</h3></div>${meta?`<span class="cps-section-count">${E(meta)}</span>`:''}</header>`;}
  function bodyDiagram(a){
    const linked=a.inventory.filter(it=>it.equipped&&it.category==='cyberware');
    const outline='M120 22C108 22 101 30 102 44L104 60Q109 74 116 76V86Q104 89 91 93C78 94 72 103 69 116L61 153 54 180 46 216 43 230 44 247Q47 252 49 246L50 233 52 249Q55 253 56 248L57 232 59 244Q62 247 63 242L64 228 68 220Q70 216 67 211L64 207 76 177 85 148 88 134 93 151 96 179 93 203Q85 225 88 247L92 288 94 307 93 329 96 367 95 384 87 394Q84 400 91 402H111Q116 400 113 390L112 376 116 340 116 313 119 283 120 256';
    const muscles='M115 96Q104 96 91 104L92 125Q103 137 117 128M94 143Q104 151 117 145M99 163L115 165M99 179L115 181M99 195L115 197M94 213Q108 211 118 225M96 239Q111 246 111 270L105 294M102 319Q100 341 105 361M79 113Q72 127 70 150M69 165L59 199M113 37Q108 39 108 44M108 53L115 53M112 64L118 66';
    return `<div class="cps-body-scan cps-anatomy"><div class="cps-scan-caption"><span>BIOMETRIC / LINK</span><b>${String(linked.length).padStart(2,'0')} ${E(tr('INSTALLED','ติดตั้ง'))}</b></div><svg viewBox="0 0 240 420" role="img" aria-label="${E(tr('Human anatomy with installed cyberware regions','แผนผังร่างกายและตำแหน่งไซเบอร์แวร์'))}"><g class="cps-anatomy-guides" fill="none" stroke="currentColor" stroke-width=".5"><path d="M20 20h30M20 20v30M220 20h-30M220 20v30M20 400h30M20 400v-30M220 400h-30M220 400v-30M120 12v396"/><ellipse cx="120" cy="410" rx="52" ry="4"/>${[85,155,225,305].map(y=>`<path d="M30 ${y}h180"/>`).join('')}</g><g class="cps-human-shell" stroke="currentColor" stroke-width="1.2"><path d="${outline}Z"/><path d="${outline}Z" transform="translate(240 0) scale(-1 1)"/></g><g class="cps-human-detail" fill="none" stroke="currentColor" stroke-width=".8"><path d="${muscles}"/><path d="${muscles}" transform="translate(240 0) scale(-1 1)"/><path d="M116 78h8M113 84h14M109 89h22M117 136h6v70h-6zM111 232l9 9 9-9M101 303h8M131 303h8M117 58l3 3 3-3M115 69h10"/></g><path class="cps-anatomy-neural" fill="none" d="M120 82v153M120 97l-28 12-16 58-16 45M120 97l28 12 16 58 16 45M120 235l-14 71 1 73M120 235l14 71-1 73"/>${C.implantGroups.map((g,i)=>{const active=linked.some(it=>C.implantSlot(it.slot)===g.id),left=i%2===0,x2=left?28:212;return `<g class="cps-anatomy-region ${active?'linked':''}"><title>${E(tr(g.en,g.th))}: ${linked.filter(it=>C.implantSlot(it.slot)===g.id).length}</title><path d="M${g.x} ${g.y}L${left?79:161} ${g.y+(i%3-1)*8}H${x2}"/><circle cx="${g.x}" cy="${g.y}" r="${active?4:2.5}"/><text x="${left?15:215}" y="${g.y+(i%3-1)*8+2}">${String(i+1).padStart(2,'0')}</text></g>`;}).join('')}</svg><div class="cps-scan-caption"><span>${E(tr('CAPACITY','ขีดจำกัด'))}</span><b>${C.load(a)} / ${a.capacity}</b></div></div>`;
  }
  function implantSlots(a){
    const all=a.inventory.filter(it=>it.category==='cyberware'&&it.equipped);
    const groups=[...C.implantGroups,...[...new Set(all.map(it=>C.implantSlot(it.slot)))].filter(slot=>!C.implantGroups.some(g=>g.id===slot)).map(id=>({id,en:id||'Unassigned',th:id||'ไม่ระบุตำแหน่ง'}))];
    return `<div class="cps-implant-slots">${groups.map((g,i)=>{const installed=all.filter(it=>C.implantSlot(it.slot)===g.id),limit=C.slotLimit(a,g.id);return `<section class="cps-implant-group ${installed.length?'linked':''}"><header><span>${String(i+1).padStart(2,'0')}</span><h4>${E(tr(g.en,g.th))}</h4><b>${installed.length}/${limit}</b></header><div class="cps-implant-sockets">${Array.from({length:Math.max(limit,installed.length)},(_,j)=>{const it=installed[j];return `<button type="button" class="cps-implant-socket ${it?'linked':''}" data-rpg="${E(it?`edit-item:${it.id}`:`slot:${g.id}`)}"><span aria-hidden="true">${it?'◆':'+'}</span><strong>${E(it?.name||tr('Empty socket','ช่องว่าง'))}</strong></button>`;}).join('')}</div>${installed.length>limit?note(tr('Legacy loadout exceeds socket count; unequip before adding.','อุปกรณ์เดิมเกินจำนวนช่อง ถอดบางชิ้นก่อนเพิ่ม')):''}</section>`;}).join('')}</div><details class="cps-rpg-advanced"><summary>${E(tr('Additional implant sockets','ช่องฝังเพิ่มเติม'))}</summary>${note(tr('Story unlocks: License to Chrome adds one Skeleton socket; Ambidextrous adds one Hands socket.','ปลดล็อกตามเนื้อเรื่อง: License to Chrome เพิ่มโครงกระดูก 1 ช่อง และ Ambidextrous เพิ่มมือ 1 ช่อง'))}${buttons(`${a.implantUnlocks?.skeleton?'✓':'+'} License to Chrome`,'socket-unlock:skeleton')}${buttons(`${a.implantUnlocks?.hands?'✓':'+'} Ambidextrous`,'socket-unlock:hands')}</details>`;
  }
  function statusMarkup(a,s){const name=actorName==='user'?api.context()?.name1||'V':actorName;const risk=C.risk(a,s.settings.riskScale);return `${heading('BIOMONITOR / PERSONAL LINK',name,a.cyberpsychosis?'NEURAL INSTABILITY':'CONNECTED')}<div class="cps-status-overview"><div class="cps-status-vitals">${meter('HEALTH',a.hp,a.maxHp)}<div class="cps-vital-pair">${meter('STAMINA',a.stamina,a.maxStamina)}${meter('RAM',a.ram,a.maxRam)}</div>${meter('CYBERWARE',C.load(a),a.capacity)}</div>${bodyDiagram(a)}</div><div class="cps-neural-assessment"><div><small>${E(tr('NEURAL STRAIN','ภาระระบบประสาท'))}</small><strong>${risk.toFixed(1)}<span>%</span></strong><p>${E(tr('Episode chance per story turn','โอกาสเกิดอาการต่อเทิร์นเนื้อเรื่อง'))}</p></div>${meter('STRESS',a.stress,100)}</div><div class="cps-rpg-actions">${buttons(tr('Recover','พักฟื้น'),'recover')}${buttons(tr('Activity & notifications','กิจกรรมและแจ้งเตือน'),'notices')}</div><details class="cps-rpg-advanced"><summary>${E(tr('Starting values & scenario setup','ค่าตั้งต้นและการตั้งสถานการณ์'))}</summary>${note(tr('Recovery spends one turn. Risk uses adjustable role-play rules.','พักฟื้นใช้หนึ่งเทิร์น ความเสี่ยงใช้กติกาโรลเพลย์ที่ปรับได้'))}${buttons(tr('Edit starting status','แก้ไขสถานะตั้งต้น'),'setup')}</details>`;}
  function itemMarkup(it,s){const canEquip=['cyberware','weapons','clothing'].includes(it.category);const cooling=Number(it.cooldownUntil)>s.turn;const canUse=!cooling&&(it.category==='consumable'||it.category==='quickhack'||it.equipped);return `<article class="cps-rpg-item cps-gear-card ${it.equipped?'linked':''}"><div class="cps-gear-topline"><span>${E(it.category.toUpperCase())}</span><b>${it.equipped?'● LINKED':tr('STORED','จัดเก็บ')}</b></div><div class="cps-gear-visual"><span class="cps-gear-blueprint-label">${E(tr('EQUIPMENT SCAN','สแกนอุปกรณ์'))}</span>${itemImage(it)}<span class="cps-gear-quantity">×${it.quantity}</span></div><div class="cps-gear-copy"><h3>${E(it.name)}</h3>${note(it.effect)}<div class="cps-gear-specs">${it.category==='cyberware'?`<span>${E(tr('Capacity','ภาระติดตั้ง'))}<b>${it.capacity}</b></span><span>${E(tr('Slot','ตำแหน่ง'))}<b>${E(it.slot||'—')}</b></span>`:`<span>${E(tr('Cooldown','คูลดาวน์'))}<b>${it.cooldown} ${E(tr('turns','เทิร์น'))}</b></span>`}</div><div class="cps-rpg-actions">${canEquip?buttons(it.equipped?tr('Unequip','ถอดออก'):tr('Equip','ติดตั้ง'),`equip:${it.id}`):''}${buttons(cooling?tr('Recharging','กำลังฟื้น'):tr('Activate','ใช้งาน'),`use:${it.id}`,canUse?'':'disabled')}</div><details class="cps-gear-more"><summary>${E(tr('Details & manage','รายละเอียดและจัดการ'))}</summary><div class="cps-rpg-actions">${buttons(tr('Edit','แก้ไข'),`edit-item:${it.id}`)}${buttons(tr('Share','ส่งข้อมูล'),`share-item:${it.id}`)}${buttons(tr('Remove one','นำออกหนึ่งชิ้น'),`remove-item:${it.id}`)}</div></details></div></article>`;}
  function skillMarkup(sk,s){const remaining=Math.max(0,sk.readyTurn-s.turn);return `<article class="cps-rpg-skill cps-ability-card"><div class="cps-ability-heading">${icon('quickhack')}<div><small>QUICK ACCESS / LV.${sk.level}</small><h3>${E(sk.name)}</h3></div><span class="cps-state-pill ${remaining?'waiting':''}">${remaining?`${remaining} ${tr('turns','เทิร์น')}`:tr('READY','พร้อม')}</span></div>${note(sk.description)}${meter('MASTERY',sk.xp,100,'mastery')}<div class="cps-ability-footer"><span><b>${sk.cost}</b> ${E(sk.resource.toUpperCase())}<small>${sk.cooldown} ${E(tr('turn cooldown','เทิร์นคูลดาวน์'))}</small></span>${buttons(tr('Activate','ใช้งาน'),`skill:${sk.id}`,remaining?'disabled':'')}</div></article>`;}
  function relicMarkup(a){return `${heading('RESTRICTED NEURAL PARTITIONS','Relic / Blackwall')}<div class="cps-partition-grid"><section class="cps-neural-partition relic"><div class="cps-partition-header">${icon('cyberware')}<div><small>RELIC INTERFACE</small><h3>${a.relic.unlocked?'LINK ESTABLISHED':'LOCKED'}</h3></div></div>${meter('RELIC POINTS',a.relic.points,Math.max(10,a.relic.points))}<div class="cps-relic-tree">${['Jailbreak','Emergency Cloaking','Vulnerability Analytics'].map((name,i)=>buttons(`${String(i+1).padStart(2,'0')} / ${name}${a.relic.abilities.includes(name)?' ✓':' · 1 RP'}`,`relic:${name}`,`${!a.relic.unlocked||a.relic.abilities.includes(name)?'disabled':''}`)).join('')}</div><details class="cps-rpg-advanced"><summary>${E(tr('Scenario unlocks','ปลดล็อกตามสถานการณ์'))}</summary>${buttons(a.relic.unlocked?tr('Relic linked','Relic เชื่อมต่อแล้ว'):tr('Unlock Relic','ปลดล็อก Relic'),'unlock-relic')}${buttons(tr('Award 1 point','เพิ่ม 1 แต้ม'),'relic-point')}</details></section><section class="cps-neural-partition blackwall"><div class="cps-partition-header">${icon('quickhack')}<div><small>BLACKWALL / RESTRICTED</small><h3>${a.blackwall.unlocked?'ACCESS AUTHORIZED':'LOCKED'}</h3></div></div>${meter('BLACKWALL EXPOSURE',a.blackwall.exposure,100)}${note(tr('4 RAM per interface. Exposure increases by 20; high exposure causes neural feedback.','ใช้ 4 RAM ต่อการเชื่อมต่อ เพิ่มการสัมผัส 20 ระดับสูงทำให้เกิดผลสะท้อนทางประสาท'))}<div class="cps-rpg-actions">${buttons(tr('Interface','เชื่อมต่อ'),'blackwall',!a.blackwall.unlocked||a.ram<4?'disabled':'')}${buttons(tr('Disconnect / recover','ตัดการเชื่อมต่อ / ฟื้นฟู'),'disconnect')}</div><details class="cps-rpg-advanced"><summary>${E(tr('Scenario unlocks','ปลดล็อกตามสถานการณ์'))}</summary>${buttons(a.blackwall.unlocked?'Blackwall linked':'Unlock Blackwall','unlock-blackwall')}</details></section></div>`;}
  function open(name='user',nextTab='status'){guard(()=>actor(name));if(name!=='user'&&!api.findEffectiveNpc(C.handle(name)))return;actorName=name;tab=nextTab;closePanel();panel=dialog(name==='user'?'Cyberware':`${name} / Cyberware`,'','cps-rpg-main');panel.querySelector('[data-rpg="close"]').onclick=closePanel;panel.addEventListener('cancel',closePanel);render();}
  function render(){
    if(!panel?.isConnected)return;const a=actor(actorName),s=state();const body=panel.querySelector('.cps-rpg-content');const oldArea=body.querySelector('.cps-rpg-body');const sameTab=panel.dataset.currentTab===tab;const scroll=sameTab?oldArea?.scrollTop||0:0;
    const drafts=sameTab?[...body.querySelectorAll('[data-rpg-settings] input')].map(el=>({name:el.name,value:el.value,checked:el.checked})):[];const focused=body.contains(document.activeElement)?document.activeElement.name:'';
    mapCleanup?.();mapCleanup=null;panel.dataset.currentTab=tab;body.innerHTML=`<div class="cps-rpg-workspace"><nav class="cps-rpg-tabs" aria-label="Cyberware sections">${sections.map(([k,en,th,ic],i)=>`<button type="button" class="cps-button" data-rpg="tab:${k}" aria-pressed="${tab===k}">${icon(ic)}<span>${E(tr(en,th))}</span><small>${String(i+1).padStart(2,'0')}</small></button>`).join('')}<div class="cps-rpg-link-state"><i></i> ${E(tr('CHAT LINKED','เชื่อมต่อแชต'))}<small>${E(actorName==='user'?api.context()?.name1||'USER':actorName)}</small></div></nav><div class="cps-rpg-main-column"><div class="cps-rpg-mobile-nav"><label>${E(tr('SECTION','หมวด'))}<select data-section-picker aria-label="${E(tr('Cyberware section','หมวด Cyberware'))}">${sections.map(([k,en,th])=>`<option value="${k}" ${tab===k?'selected':''}>${E(tr(en,th))}</option>`).join('')}</select></label><span class="cps-state-pill">● ${E(tr('LIVE','เชื่อมต่อ'))}</span></div><div class="cps-rpg-body" tabindex="0" aria-label="${E(sectionTitle(tab))}"></div></div></div>`;
    const area=body.querySelector('.cps-rpg-body');
    if(tab==='status')area.innerHTML=statusMarkup(a,s);
    if(['cyberware','weapons','inventory'].includes(tab)){const items=a.inventory.filter(it=>tab==='inventory'||it.category===tab);area.innerHTML=`${heading(tab==='cyberware'?'RIPPERDOC / LOADOUT':'EQUIPMENT DATABASE',sectionTitle(tab),`${items.length} ${tr('ITEMS','รายการ')}`)}${tab==='cyberware'?`<div class="cps-loadout-overview">${bodyDiagram(a)}<div class="cps-loadout-summary">${meter('CYBERWARE',C.load(a),a.capacity)}<div class="cps-socket-total"><strong>${a.inventory.filter(it=>it.category==='cyberware'&&it.equipped).length}<small> / ${C.implantGroups.reduce((n,g)=>n+C.slotLimit(a,g.id),0)}</small></strong><span>${E(tr('IMPLANT SOCKETS','ช่องฝังไซเบอร์แวร์'))}</span></div>${note(tr('Select an occupied socket to inspect its implant, or an empty socket to browse compatible equipment.','แตะช่องที่ติดตั้งเพื่อดูอุปกรณ์ หรือช่องว่างเพื่อเลือกอุปกรณ์ที่เข้ากัน'))}</div>${implantSlots(a)}</div>`:''}<div class="cps-rpg-actions">${buttons(tr('Browse catalog','ค้นหาแค็ตตาล็อก'),'catalog')}${buttons(tr('Add custom item','เพิ่มไอเท็มเอง'),'custom-item')}</div><div class="cps-rpg-items">${items.map(it=>itemMarkup(it,s)).join('')||`<div class="cps-rpg-empty">${icon(tab==='inventory'?'item':tab)}<strong>${E(tr('No equipment stored','ยังไม่มีอุปกรณ์'))}</strong>${note(tr('Add the equipment established in your story.','เพิ่มอุปกรณ์ที่มีอยู่ในเนื้อเรื่อง'))}</div>`}</div>`;}
    if(tab==='balance')area.innerHTML=`${heading('EURODOLLAR ACCOUNT',sectionTitle(tab))}<div class="cps-account-card"><span>AVAILABLE BALANCE</span><h3><small>€$</small> ${a.balance.toLocaleString()}</h3><footer><span>${E(actorName==='user'?api.context()?.name1||'USER':actorName)}</span><b>LOCAL ACCOUNT</b></footer></div><div class="cps-rpg-actions">${buttons(tr('Transfer','โอนเงิน'),'transfer')}</div>${heading('TRANSACTION LOG',tr('Recent activity','รายการล่าสุด'),String(a.ledger.length))}<div class="cps-rpg-ledger">${a.ledger.slice().reverse().map(e=>`<article class="${e.delta>0?'credit':'debit'}"><div><small>${E(e.delta>0?tr('RECEIVED','รับเข้า'):tr('SENT / ADJUSTED','โอนออก / ปรับยอด'))}</small><p>${E(e.reason)}</p><time>${E(new Date(e.at).toLocaleString(api.settings().language==='th'?'th-TH':'en-GB'))}</time></div><strong>${e.delta>0?'+':''}${e.delta.toLocaleString()}<small>€$</small></strong></article>`).join('')||note(tr('No transactions yet.','ยังไม่มีรายการ'))}</div><details class="cps-rpg-advanced"><summary>${E(tr('Transfer by chat / starting balance','โอนผ่านแชต / ยอดเงินเริ่มต้น'))}</summary>${note('/cp transfer @lucy 500\nโอนเงิน 500 ให้ @lucy')}${buttons(tr('Set starting balance','ตั้งยอดเงินเริ่มต้น'),'setup')}</details>`;
    if(tab==='skills')area.innerHTML=`${heading('NEURAL TOOLKIT',sectionTitle(tab),`${a.skills.length} ${tr('SKILLS','ทักษะ')}`)}<div class="cps-breach-launcher">${icon('quickhack')}<div><small>ACCESS POINT INTERFACE</small><h3>Breach Protocol</h3></div>${buttons(tr('Training','ฝึกแฮ็ก'),'practice')}${s.puzzle&&['ready','running'].includes(s.puzzle.status)?buttons(tr('Resume','เปิดต่อ'),'resume'):''}</div><div class="cps-rpg-actions">${buttons(tr('Add skill','เพิ่มสกิล'),'add-skill')}</div><div class="cps-ability-grid">${a.skills.map(sk=>skillMarkup(sk,s)).join('')||note(tr('Abilities used in the story appear here.','ทักษะที่ใช้ในเนื้อเรื่องจะแสดงที่นี่'))}</div>`;
    if(tab==='quests')area.innerHTML=`${heading('JOURNAL / CONTRACTS',sectionTitle(tab),`${s.quests.filter(q=>q.status==='active').length} ACTIVE`)}<div class="cps-rpg-actions">${buttons(tr('Add mission','เพิ่มภารกิจ'),'add-quest')}</div>${s.quests.map(q=>`<article class="cps-quest-card ${E(q.status)}"><header><span>${E(q.status.toUpperCase())}</span><small>MISSION FILE</small></header><h3>${E(q.title)}</h3>${note(q.description)}<div class="cps-quest-objective"><i aria-hidden="true"></i><div><small>${E(tr('OBJECTIVE','เป้าหมาย'))}</small><p>${E(q.objective||tr('Awaiting briefing','รอข้อมูลภารกิจ'))}</p></div></div><div class="cps-rpg-actions">${buttons(tr('Share briefing','ส่งข้อมูลภารกิจ'),`share-quest:${q.id}`)}${buttons(tr('Change status','เปลี่ยนสถานะ'),`quest:${q.id}`)}</div></article>`).join('')||note(tr('No mission data received.','ยังไม่ได้รับข้อมูลภารกิจ'))}`;
    if(tab==='map')renderMap(area);
    if(tab==='relic')area.innerHTML=relicMarkup(a);
    if(tab==='settings')area.innerHTML=`${heading('SYSTEM PREFERENCES',sectionTitle(tab))}<form data-rpg-settings class="cps-rpg-preferences"><label class="cps-preference-switch"><span>${tr('Immersion notifications','แจ้งเตือนบรรยากาศ')}</span><input name="notifications" type="checkbox" ${s.settings.notifications?'checked':''} role="switch"></label><label><span>${tr('Dismiss after (seconds)','เวลาหาย (วินาที)')}</span><input name="noticeSeconds" type="number" min="2" max="60" value="${s.settings.noticeSeconds}" required></label><label><span>${tr('Cyberpsychosis risk multiplier (0 disables)','ตัวคูณความเสี่ยง Cyberpsychosis (0 = ปิด)')}</span><input name="riskScale" type="number" min="0" max="3" step="0.1" value="${s.settings.riskScale}" required></label><button class="cps-button primary" type="submit">${tr('Save preferences','บันทึกการตั้งค่า')}</button></form>${note(tr('Saved for this chat. Display colors and animations follow the main extension settings.','บันทึกแยกตามแชต สีและแอนิเมชันใช้ค่าจากการตั้งค่า extension'))}`;
    body.querySelectorAll('[data-rpg]').forEach(b=>b.onclick=()=>guard(()=>action(b.dataset.rpg)));
    body.querySelector('[data-section-picker]').onchange=e=>{tab=e.target.value;render();};
    body.querySelector('[data-rpg-settings]')?.addEventListener('submit',e=>{e.preventDefault();const f=e.currentTarget;s.settings={notifications:f.elements.notifications.checked,noticeSeconds:C.cap(f.elements.noticeSeconds.value,2,60),riskScale:C.cap(f.elements.riskScale.value,0,3)};save();api.toast(tr('Saved','บันทึกแล้ว'));});
    for(const draft of drafts){const el=[...body.querySelectorAll('[name]')].find(x=>x.name===draft.name);if(el){el.value=draft.value;el.checked=draft.checked;}}
    if(focused)[...body.querySelectorAll('[name]')].find(x=>x.name===focused)?.focus({preventScroll:true});
    area.scrollTop=scroll;
    if(!sameTab){area.classList.add('cps-page-enter');area.style.setProperty('--cps-page-direction','1');}
  }
  function form(title,fields,submit){
    const owner=safeOwner();
    const d=dialog(title,`<form class="cps-rpg-form">${fields.map(([name,label,value='',type='text',extra=''])=>`<label>${E(label)}${type==='textarea'?`<textarea name="${name}" ${extra}>${E(value)}</textarea>`:type==='select'?`<select name="${name}">${value}</select>`:`<input name="${name}" type="${type}" value="${E(value)}" ${extra}>`}</label>`).join('')}<button class="cps-button primary" type="submit">${tr('Save / Send','บันทึก / ส่ง')}</button><p role="alert" data-error></p></form>`);
    d.querySelector('form').onsubmit=e=>{e.preventDefault();try{if(owner!==safeOwner()||!d.isConnected)throw Error('Chat changed; reopen this form.');submit(Object.fromEntries(new FormData(e.currentTarget)));api.removeUiDialog(d);save();render();}catch(err){d.querySelector('[data-error]').textContent=err.message;}};return d;
  }
  function setup(){const a=actor(actorName);form('Starting status / RP setup',[['balance','Balance €$',a.balance,'number','min="0" max="1000000000000" required'],...['hp','maxHp','ram','maxRam','stamina','maxStamina','capacity','stress'].map(k=>[k,k,a[k],'number','min="0" max="1000" required'])],v=>{const balance=C.money(v.balance),old=a.balance;a.balance=balance;a.ledger.push({id:C.uid(),delta:balance-old,reason:'Manual story setup',at:new Date().toISOString()});for(const k of ['maxHp','maxRam','maxStamina','capacity'])a[k]=C.cap(v[k],1,1000);for(const [k,max]of [['hp',a.maxHp],['ram',a.maxRam],['stamina',a.maxStamina],['stress',100]])a[k]=C.cap(v[k],0,max);event('setup',`${actorName}: manual status adjustment`);});}
  function editItem(it){form(it?'Edit equipment':'Custom equipment',[['name','Name',it?.name||'','text','required maxlength="180"'],['category','Category',['cyberware','weapons','quickhack','consumable','clothing','mod','component','data','item'].map(k=>`<option ${it?.category===k?'selected':''}>${k}</option>`).join(''),'select'],['slot','Implant group / equipment slot',`<option value="">—</option>${C.implantGroups.map(g=>`<option value="${g.id}" ${C.implantSlot(it?.slot)===g.id?'selected':''}>${E(tr(g.en,g.th))}</option>`).join('')}${it?.slot&&!C.implantGroups.some(g=>g.id===C.implantSlot(it.slot))?`<option selected value="${E(it.slot)}">${E(it.slot)}</option>`:''}`,'select'],['quantity','Quantity',it?.quantity||1,'number','min="1" max="9999" required'],['capacity','Capacity cost (RP)',it?.capacity??10,'number','min="0" max="300"'],['power','Power / healing (RP)',it?.power??20,'number','min="0" max="1000"'],['cooldown','Cooldown turns',it?.cooldown??2,'number','min="0" max="30"'],['effect','Description',it?.effect||'','textarea']],v=>{const entry=C.item({...it,...v});if(it)Object.assign(it,entry,{equipped:it.equipped,cooldownUntil:it.cooldownUntil});else actor(actorName).inventory.push(entry);event('equipment',`${actorName}: ${entry.name}`);});}
  function transferDialog(peer=api.chatBucket().call.peer?.name){const names=api.effectiveRecords('npcs');if(!names.length)throw Error('Add a contact first');form(tr('Transfer eurodollars','โอนเงิน Eurodollars'),[['to','To',names.map(n=>`<option value="${E(n.name)}" ${n.name===peer?'selected':''}>${E(n.name)}</option>`).join(''),'select'],['amount','€$',1,'number','min="1" max="1000000000000" required'],['reason',tr('Reason','เหตุผล'),'']],v=>transfer('user',v.to,v.amount,v.reason));}
  function transfer(from,to,amount,reason,txid=C.uid()){
    if(!C.transfer(actor(from),actor(to),amount,reason||`${from} → ${to}`,txid))return false;
    event('transfer',`${from} → ${to}: €$${amount}. ${C.text(reason,500)}`);notify('TRANSFER COMPLETE',`${from} → ${to} · €$${amount}\n${reason||''}`);
    if(api.chatBucket().call.active)share({kind:'receipt',title:'TRANSFER COMPLETE',description:`${from} → ${to} · €$${amount}`,id:txid},from==='user'?'user':'assistant',from);
    return true;
  }
  function userText(raw,key){const s=state();const receipt=`user:${key}`;if(s.processed.includes(receipt))return;
    const m=C.text(raw,4000).match(/^\/cp\s+transfer\s+(.+?)\s+(\d+)(?:\s+(.+))?$/i)||C.text(raw,4000).match(/^โอนเงิน\s+(\d+)\s+ให้\s+(.+?)\s*$/u)?.map((v,i,arr)=>i===1?arr[2]:i===2?arr[1]:v);
    if(!m)return; s.processed.push(receipt);s.processed=s.processed.slice(-3000);guard(()=>transfer('user',C.handle(m[1]),m[2],m[3]||'Main-chat instruction',receipt));save();}
  function share(data,role='assistant',name=api.chatBucket().call.peer?.name||'System'){
    const entry={id:C.text(data.id||C.uid(),160),kind:C.text(data.kind,30),title:C.text(data.title||data.item?.name||data.contact?.name||'Data',180),description:C.text(data.description,5000)};
    if(!['location','mission','item','contact','data','receipt'].includes(entry.kind))throw Error('Unknown attachment kind');
    if(entry.kind==='item')entry.item=C.item(data.item||{name:entry.title});
    if(entry.kind==='contact'){
      const fields=['name','handle','role','status','affiliation','age','gender','personality','appearance','notes'];
      if(!data.contact||fields.some(k=>!C.text(data.contact[k])))throw Error('Contact requires a complete dossier');
      entry.contact=Object.fromEntries(fields.map(k=>[k,C.text(data.contact[k],k==='notes'?3000:2000)]));entry.contact.handle=C.handle(entry.contact.handle);
      entry.contact.rpg={balance:C.money(data.contact.balance??0),inventory:Array.isArray(data.contact.inventory)?data.contact.inventory.slice(0,100).map(C.item):[]};
    }
    const s=state();if(s.shares.some(x=>x.id===entry.id))return; s.shares.push(entry);s.shares=s.shares.slice(-100);
    if(api.chatBucket().call.active){const m=api.appendCallMessage(role,name,entry.title,role==='user');if(m){m.attachment=entry;api.renderCallLog();}}
    else notify(entry.title,entry.description||tr('Open Cyberware to inspect received data.','เปิด Cyberware เพื่อดูข้อมูล'));
    event('share',`${role}: ${entry.kind}: ${entry.title} · ${entry.description}`);save();return entry;
  }
  function attachment(node,message){const v=message.attachment;if(!v||node.querySelector('.cps-attachment'))return;
    const card=document.createElement('article');card.className='cps-attachment';card.innerHTML=`${v.item?itemImage(v.item):icon('data')}<div><small>${E(v.kind)}</small><strong>${E(v.title)}</strong>${note(v.description)}${buttons(v.kind==='contact'?tr('Add contact','เพิ่มผู้ติดต่อ'):tr('Open data','เปิดข้อมูล'),'open-attachment')}</div>`;
    card.querySelector('button').onclick=()=>guard(()=>{if(v.kind==='contact')addContact(v.contact);else detail(v.title,v.description||v.item?.effect||v.item?.name||v.title);});node.append(card);
  }
  function addContact(contact){if(!contact?.name)throw Error('Invalid contact');if(api.findEffectiveNpc(contact.name)||api.findEffectiveNpc(contact.handle)){api.toast('Contact already exists');return;}
    const npc={...contact,id:C.uid(),handle:C.handle(contact.handle),createdAt:new Date().toISOString()};delete npc.rpg;api.chatBucket().npcs.push(npc);const a=actor(npc.name);a.balance=C.money(contact.rpg?.balance??0);a.inventory=(contact.rpg?.inventory||[]).map(C.item);save();notify('CONTACT ADDED',`${npc.name} · @${npc.handle}`);}
  function shareDialog(){form('Send data',[['kind','Type',['data','location','mission'].map(k=>`<option>${k}</option>`).join(''),'select'],['title','Title','','text','required maxlength="180"'],['description','Details','','textarea','required maxlength="5000"']],v=>share(v,'user',api.context()?.name1||'User'));}
  function callToolbar(overlay){
    if(overlay.querySelector('.cps-call-tools-toggle'))return;
    const trigger=document.createElement('button');trigger.type='button';trigger.className='cps-button cps-call-tools-toggle';
    trigger.setAttribute('aria-label',tr('Call tools','เครื่องมือระหว่างสาย'));trigger.setAttribute('aria-haspopup','dialog');trigger.setAttribute('aria-expanded','false');trigger.setAttribute('aria-controls','cps-call-tools-drawer');
    trigger.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z"/></svg>';
    overlay.querySelector('.cps-end-call')?.after(trigger);
    let drawer=null;
    const close=(restore=true)=>{if(!drawer)return;const old=drawer;drawer=null;api.removeUiDialog(old);trigger.setAttribute('aria-expanded','false');if(restore&&trigger.isConnected)trigger.focus({preventScroll:true});};
    overlay.cpsCloseTools=()=>close(false);
    trigger.onclick=()=>{
      if(drawer)return close();
      drawer=document.createElement('dialog');drawer.id='cps-call-tools-drawer';drawer.className='cps-ui cps-call-drawer';drawer.setAttribute('aria-labelledby','cps-call-tools-title');
      const choices=[['transfer','component','Eurodollars','Eurodollars','Transfer to your contact','โอนเงินให้ผู้ติดต่อ'],['send-location','mod','Location','โลเคชั่น','Send your current location','ส่งตำแหน่งปัจจุบัน'],['share','data','Information','ส่งข้อมูล','Share a briefing or message','ส่งรายละเอียดภารกิจหรือข้อมูล'],['open','cyberware','Cyberware','Cyberware','Inspect your status and loadout','ดูสถานะและอุปกรณ์ของคุณ']];
      drawer.innerHTML=`<section class="cps-call-tool-sheet"><div class="cps-drawer-grip" aria-hidden="true"></div><header><div><small>PRIVATE LINK / ACTIONS</small><h2 id="cps-call-tools-title">${E(tr('Call tools','เครื่องมือระหว่างสาย'))}</h2></div><button type="button" class="cps-icon-button" data-tools-close aria-label="${E(tr('Close tools','ปิดเครื่องมือ'))}">×</button></header><div class="cps-call-tools">${choices.map(([action,ic,en,th,hint,hintTh],i)=>`<button type="button" class="cps-call-tool" data-rpg="${action}">${icon(ic)}<span><strong>${E(tr(en,th))}</strong><small>${E(tr(hint,hintTh))}</small></span><b aria-hidden="true">0${i+1} ↗</b></button>`).join('')}</div></section>`;
      drawer.querySelector('[data-tools-close]').onclick=()=>close();
      drawer.addEventListener('cancel',e=>{e.preventDefault();e.stopPropagation();close();});
      drawer.addEventListener('click',e=>{if(e.target===drawer)close();});
      drawer.querySelectorAll('[data-rpg]').forEach(button=>button.onclick=()=>{const action=button.dataset.rpg;close();guard(()=>{
        if(action==='transfer')return transferDialog(api.chatBucket().call.peer?.name);
        if(action==='open')return open('user');
        if(action==='share')return shareDialog();
        const location=state().map.location,parts=Object.entries(location).filter(([,v])=>String(v??'').trim());
        if(!parts.length)throw Error(tr('No location recorded yet. Set it in Cyberware → Night City.','ยังไม่มีตำแหน่ง ตั้งค่าใน Cyberware → แผนที่ก่อน'));
        return share({kind:'location',title:tr('Location pin','พิกัดตำแหน่ง'),description:parts.map(([k,v])=>`${k}: ${v}`).join('\n')},'user',api.context()?.name1||'User');
      });});
      overlay.append(drawer);trigger.setAttribute('aria-expanded','true');api.showUiDialog(drawer);drawer.querySelector('[data-tools-close]').focus({preventScroll:true});
    };
  }
  function catalog(slot=''){const target=actorName;const d=dialog('Equipment database',`<label>${tr('Search names or game IDs','ค้นชื่อหรือรหัสไอเท็ม')}<input type="search" data-catalog-search placeholder="Monowire / Items…"></label><label><input type="checkbox" data-technical> ${tr('Include 3,420 technical IDs (unverified display names)','รวมรหัสเทคนิค 3,420 รายการ (ยังไม่ยืนยันชื่อแสดงผล)')}</label>${note(tr('58 named entries plus an imported ID index. Not a verified complete game catalog. SVG symbols are original; role-play stats are editable. Adding an item records a manual grant, not a purchase.','มี 58 รายการชื่ออ่านง่ายและดัชนีรหัสนำเข้า ยังไม่ใช่รายการทุกอย่างที่ตรวจสอบครบ ไอคอน SVG วาดใหม่ ค่าสำหรับโรลเพลย์แก้ไขได้ การเพิ่มเป็นการตั้งอุปกรณ์เอง ไม่ใช่การซื้อ'))}<p data-count></p><div class="cps-rpg-catalog"></div>`);
    const draw=()=>{const q=d.querySelector('input[type=search]').value.trim().toLowerCase(),technical=d.querySelector('[data-technical]').checked;
      const all=[...DB.curated,...(technical?DB.records:[])].filter(x=>(!slot||(x.category==='cyberware'&&C.implantSlot(x.slot)===slot))&&`${x.name} ${x.id} ${x.category}`.toLowerCase().includes(q));d.querySelector('[data-count]').textContent=`${all.length} results · showing ${Math.min(60,all.length)}`;
      const grid=d.querySelector('.cps-rpg-catalog');grid.innerHTML=all.slice(0,60).map((it,i)=>`<article class="cps-rpg-item">${itemImage(it)}<div><small>${E(it.category)}${it.technical?' / TECHNICAL ID':''}</small><h3>${E(it.name)}</h3>${buttons(tr('Add to inventory','เพิ่มในคลัง'),`catalog:${i}`)}</div></article>`).join('');grid.querySelectorAll('button').forEach((b,i)=>b.onclick=()=>guard(()=>{const it=C.item({...all[i],id:C.uid(),catalogId:all[i].id});actor(target).inventory.push(it);event('manual grant',`${target}: ${it.name}`);b.textContent='Added ✓';b.disabled=true;render();}));};
    d.querySelector('[data-catalog-search]').oninput=draw;d.querySelector('[data-technical]').onchange=draw;draw();
  }
  function renderMap(area){
    const owner=safeOwner(),s=state();
    mapCleanup=globalThis.CyberpunkMap.mount(area,{map:s.map,escape:E,language:api.settings().language,playerName:api.context()?.name1,
      npcs:api.effectiveRecords('npcs').map(n=>({name:n.name,location:actor(n.name).location})),quests:s.quests,
      onSave:()=>{if(owner===safeOwner())api.saveChat();},
      onPick:data=>guard(()=>{if(owner!==safeOwner())return;location(data);save();render();})});
  }
  function location(data){
    const m=state().map,next=globalThis.CyberpunkMap.normalizeLocation(data);
    const isPlayer=!data.actor||['user','player',api.context()?.name1].includes(data.actor);
    if(!isPlayer){
      const a=actor(data.actor);a.location={...next,knownToUser:data.knownToUser===true};
      if(a.location.knownToUser&&!m.discovered.includes(next.district))m.discovered.push(next.district);
      event('contact location',`${data.actor}: ${next.district}`);return;
    }
    const old=JSON.stringify(m.location);m.location=next;if(!m.discovered.includes(next.district))m.discovered.push(next.district);
    const known=globalThis.CyberpunkMap.district(next.district);
    if(old!==JSON.stringify(next))notify(next.danger?'DANGER ZONE':known.name,[known.name,next.subdistrict,next.building,next.floor?`Floor ${next.floor}`:'',next.area,data.reason].filter(Boolean).join(' / '),next.danger);
    event('location',JSON.stringify(next));
  }
  function locationDialog(){const l=state().map.location;form(tr('Story location / coordinates','ตำแหน่งในเรื่อง / พิกัด'),[['district','District',globalThis.CyberpunkMapData.districts.map(d=>`<option value="${d.id}" ${l.district===d.id?'selected':''}>${E(d.name)}</option>`).join(''),'select'],...['subdistrict','building','floor','area'].map(k=>[k,k,l[k]||'']),...['x','y','z'].map(k=>[k,`${k.toUpperCase()} · CET (optional)`,l[k]??'','number','step="any"']),['danger','Danger',['false','true'].map(v=>`<option ${String(l.danger)===v?'selected':''}>${v}</option>`).join(''),'select']],v=>location({...v,danger:v.danger==='true'}));}
  const suspendedPanels=[];
  let breachLayoutCleanup=null;
  function suspendPanels(){for(const el of document.querySelectorAll('dialog.cps-ui[open]')){if(el===breach||el.hasAttribute('data-cps-breach-suspended'))continue;el.setAttribute('data-cps-breach-suspended','');suspendedPanels.push(el);}}
  function stopBreach(){clearInterval(timer);timer=null;breachLayoutCleanup?.();breachLayoutCleanup=null;api.removeUiDialog(breach);breach=null;for(const el of suspendedPanels.splice(0))el.removeAttribute('data-cps-breach-suspended');}
  function minimized(){let b=document.getElementById('cps-breach-resume');const p=state().puzzle;if(!p||!['ready','running'].includes(p.status)||!p.minimized){b?.remove();return;}if(!b){b=document.createElement('button');b.id='cps-breach-resume';b.className='cps-button';b.onclick=openBreach;document.body.append(b);if(typeof b.showPopover==='function'){b.setAttribute('popover','manual');try{b.showPopover();}catch{}}else document.querySelector('dialog.cps-ui[open]:last-of-type')?.append(b);}b.textContent=`▣ BREACH / ${p.target} · ${tr('Resume','เปิดต่อ')}`;}
  function beginBreach(data={}){const s=state();if(s.puzzle&&['ready','running'].includes(s.puzzle.status)){notify('BREACH PENDING','Finish or cancel the current access point first.');return false;}s.puzzle=C.puzzle(data);save();openBreach();return true;}
  function settle(p){if(p.revealed)return;if(!['success','failed','cancelled'].includes(p.status))return;p.revealed=true;save();event('breach result',`${p.target}: ${p.status}${p.status==='success'?` · unlocked data: ${p.data}`:''}`);if(p.status==='success'){const sk=C.addSkill(state().player,{name:'Netrunner',resource:'ram'});sk.xp+=25;if(sk.xp>=100&&sk.level<60){sk.level++;sk.xp-=100;}notify('ACCESS GRANTED',p.data||p.target);}else notify('ACCESS DENIED',`${p.target}: ${p.status}`,true);save();}
  function openBreach(){const p=state().puzzle;if(!p)return;stopBreach();p.minimized=false;minimized();
    breach=document.createElement('dialog');breach.className='cps-ui cps-breach';breach.setAttribute('aria-label','Breach Protocol');
    breach.innerHTML=`<section class="cps-breach-terminal"><header class="cps-breach-drag"><div><small>NEURAL LINK / INTRUSION</small><strong>BREACH PROTOCOL</strong><span>${E(p.target)}</span></div><span class="cps-breach-grip" aria-hidden="true">⠿</span></header><div class="cps-breach-toolbar"><div class="cps-breach-time"><small>${E(tr('TIME REMAINING','เวลาคงเหลือ'))}</small><div class="cps-breach-clock" role="timer"></div></div><span class="cps-breach-status"></span><div class="cps-breach-controls">${buttons('—','minimize','aria-label="Minimize and pause"')}${buttons(tr('Cancel','ยกเลิก'),'cancel')}${buttons(tr('Upload','อัปโหลด'),'finish','aria-label="Upload sequences"')}</div></div><div class="cps-breach-buffer-label"><span>BUFFER</span><small data-buffer-count></small></div><div class="cps-breach-buffer" aria-label="Uploaded buffer"></div><div class="cps-breach-columns"><section class="cps-matrix-panel"><h3>01 / CODE MATRIX <span data-axis-label></span></h3><div class="cps-breach-grid" role="group" aria-label="Code matrix"></div></section><section class="cps-daemons-panel"><h3>02 / SEQUENCES</h3><div class="cps-breach-daemons"></div></section></div><footer class="cps-breach-bottom"><p class="cps-breach-help"></p></footer><section class="cps-breach-result" role="status" hidden></section><details class="cps-breach-adjust"><summary>${E(tr('Position & instructions','ตำแหน่งและวิธีเล่น'))}</summary><label class="cps-breach-position">${E(tr('Vertical position','ตำแหน่งแนวตั้ง'))}<input type="range" min="-100" max="100" value="${C.cap(p.offset,-100,100)}" aria-label="Vertical position"></label><p>${E(tr('Start in the top row. Alternate column and row without reusing cells. Complete ACCESS to unlock the data. Minimizing pauses the timer.','เริ่มแถวบน สลับคอลัมน์และแถวโดยไม่ใช้ช่องซ้ำ ให้รหัส ACCESS ตรงเพื่อเปิดข้อมูล ย่อหน้าต่างเพื่อพักเวลา'))}</p></details></section>`;
    const current=breach,terminal=breach.querySelector('.cps-breach-terminal'),owner=safeOwner(),slider=breach.querySelector('input');
    terminal.style.setProperty('--breach-offset',`${p.offset||0}px`);
    const move=value=>{if(!current.isConnected)return;const rect=terminal.getBoundingClientRect();const viewport=globalThis.visualViewport;const height=viewport?.height||innerHeight;const base=rect.top-(p.offset||0);const top=(viewport?.offsetTop||0)+10;const min=rect.height?Math.min(0,top-base):0;const max=rect.height?Math.max(0,Math.min(100,top+height-rect.height-base-20)):100;p.offset=C.cap(value,min,max);terminal.style.setProperty('--breach-offset',`${p.offset}px`);slider.min=String(Math.ceil(min));slider.max=String(Math.floor(max));slider.value=String(p.offset);};
    let drag=null;const header=breach.querySelector('.cps-breach-drag');header.onpointerdown=e=>{drag={y:e.clientY,start:p.offset||0};header.setPointerCapture?.(e.pointerId);};header.onpointermove=e=>{if(drag)move(drag.start+e.clientY-drag.y);};header.onpointerup=header.onpointercancel=()=>{drag=null;save();};slider.oninput=e=>move(e.target.value);slider.onchange=save;
    const pause=()=>{C.pause(p);save();stopBreach();minimized();};breach.addEventListener('cancel',e=>{e.preventDefault();if(['ready','running'].includes(p.status))pause();else stopBreach();});
    breach.querySelector('[data-rpg=minimize]').onclick=pause;breach.querySelector('[data-rpg=cancel]').onclick=()=>{if(['ready','running'].includes(p.status)){C.pause(p);p.status='cancelled';settle(p);}stopBreach();minimized();};breach.querySelector('[data-rpg=finish]').onclick=()=>{if(!p.daemons[0].done)return;C.finish(p);settle(p);drawBreach();};
    document.body.append(breach);suspendPanels();api.showUiDialog(breach);drawBreach();
    const reposition=()=>move(p.offset||0);let layoutFrame=requestAnimationFrame(reposition);const onResize=()=>{cancelAnimationFrame(layoutFrame);layoutFrame=requestAnimationFrame(reposition);};globalThis.addEventListener('resize',onResize);globalThis.visualViewport?.addEventListener('resize',onResize);breachLayoutCleanup=()=>{cancelAnimationFrame(layoutFrame);globalThis.removeEventListener('resize',onResize);globalThis.visualViewport?.removeEventListener('resize',onResize);};
    timer=setInterval(()=>{if(owner!==safeOwner()){stopBreach();return;}if(C.remaining(p)<=0&&['ready','running'].includes(p.status)){C.finish(p);settle(p);drawBreach();}if(breach)breach.querySelector('.cps-breach-clock').textContent=`${(C.remaining(p)/1000).toFixed(1)}s`;},100);
  }
  const safeOwner=()=>api.chatBucket();
  function drawBreach(){if(!breach)return;const p=state().puzzle,finished=!['ready','running'].includes(p.status);breach.dataset.status=p.status;const grid=breach.querySelector('.cps-breach-grid');grid.style.setProperty('--matrix-size',p.grid.length);
    grid.innerHTML=p.grid.flatMap((row,r)=>row.map((value,c)=>{const used=p.selected.some(v=>v[0]===r&&v[1]===c),valid=!used&&(p.axis==='row'?r===p.row:c===p.col);return `<button type="button" data-cell="${r},${c}" class="${used?'used':valid?'available':''}" ${!valid||finished?'disabled':''} aria-label="Row ${r+1}, column ${c+1}, ${value}">${used?'·':value}</button>`;})).join('');
    grid.querySelectorAll('button').forEach(b=>b.onclick=()=>{const[r,c]=b.dataset.cell.split(',').map(Number);C.choose(p,r,c);settle(p);save();drawBreach();});
    const buffer=breach.querySelector('.cps-breach-buffer');buffer.style.setProperty('--buffer-size',p.buffer);buffer.innerHTML=Array.from({length:p.buffer},(_,i)=>`<span class="${p.sequence[i]?'filled':''}">${p.sequence[i]||'—'}</span>`).join('');
    breach.querySelector('[data-buffer-count]').textContent=`${p.sequence.length} / ${p.buffer}`;breach.querySelector('[data-axis-label]').textContent=finished?'':p.axis.toUpperCase();
    breach.querySelector('.cps-breach-daemons').innerHTML=p.daemons.map((d,i)=>`<article class="${d.done?'complete':''}"><div><strong>${d.name}</strong><small>${d.done?'✓':i===0?tr('REQUIRED','จำเป็น'):tr('OPTIONAL','เสริม')}</small></div><div>${d.codes.map(c=>`<b>${c}</b>`).join('')}</div></article>`).join('');
    const help=breach.querySelector('.cps-breach-help');help.textContent=finished?(p.status==='success'?`ACCESS GRANTED · ${p.data}`:tr('Access denied. No data unlocked.','ปฏิเสธการเข้าถึง ไม่มีข้อมูลถูกเปิด')):p.daemons[0].done?tr('ACCESS matched. Upload or continue for bonus sequences.','รหัส ACCESS ตรงแล้ว อัปโหลดหรือเล่นต่อเพื่อรับรหัสเสริม'):tr(`Select ${p.axis==='row'?'ROW':'COLUMN'} ${p.axis==='row'?p.row+1:p.col+1}. Match the ACCESS sequence.`,`เลือก${p.axis==='row'?'แถว':'คอลัมน์'} ${p.axis==='row'?p.row+1:p.col+1} ให้รหัสตรงกับ ACCESS`);
    const result=breach.querySelector('.cps-breach-result');result.hidden=!finished;result.innerHTML=finished?`<small>CONNECTION ${p.status==='success'?'VERIFIED':'CLOSED'}</small><strong>${p.status==='success'?'ACCESS GRANTED':'ACCESS DENIED'}</strong><p>${E(p.status==='success'?p.data||p.target:tr('No data released. Close to return.','ไม่มีข้อมูลถูกเปิด ปิดเพื่อกลับหน้าก่อนหน้า'))}</p>`:'';
    help.hidden=finished;breach.querySelector('.cps-breach-status').textContent=p.status.toUpperCase();breach.querySelector('.cps-breach-clock').textContent=`${(C.remaining(p)/1000).toFixed(1)}s`;
    breach.querySelector('[data-rpg=finish]').disabled=finished||!p.daemons[0].done;breach.querySelector('[data-rpg=minimize]').disabled=finished;breach.querySelector('[data-rpg=cancel]').textContent=finished?tr('Close','ปิด'):tr('Cancel','ยกเลิก');
  }
  function action(command){const [kind,...rest]=command.split(':'),value=rest.join(':'),a=actor(actorName),s=state();
    if(kind==='tab'){tab=value;render();return;}
    const actions={open:()=>open(),catalog,setup,transfer:()=>transferDialog(actorName==='user'?api.chatBucket().call.peer?.name:actorName),share:shareDialog,location:locationDialog,practice:()=>beginBreach({target:'Training access point',data:'Training completed. No story secrets unlocked.'}),resume:openBreach,'custom-item':()=>editItem(),
      recover:()=>{s.turn++;a.stress=C.cap(a.stress-20,0,100);a.ram=a.maxRam;a.stamina=a.maxStamina;if(a.stress<30&&C.load(a)<=a.capacity)a.cyberpsychosis=false;event('recovery',`${actorName} rests one turn`);},
      'send-location':()=>share({kind:'location',title:'Location pin',description:Object.entries(s.map.location).map(([k,v])=>`${k}: ${v}`).join('\n')},'user',api.context()?.name1||'User'),
      'complete-zone':()=>{if(!s.map.location.district)throw Error('Set a location first');if(!s.map.completed.includes(s.map.location.district))s.map.completed.push(s.map.location.district);event('area completed',s.map.location.district);},
      'add-skill':()=>form('Add ability',[['name','Skill name','','text','required'],['description','Description','','textarea'],['cost','Resource cost',0,'number','min="0" max="100"'],['resource','Resource','<option>stamina</option><option>ram</option>','select'],['cooldown','Cooldown turns',1,'number','min="0" max="30"']],v=>{C.addSkill(a,v);event('skill learned',`${actorName}: ${v.name}`);}),
      'add-quest':()=>form('Mission',[['title','Title','','text','required'],['description','Brief','','textarea'],['objective','Current objective','','textarea']],v=>{s.quests.push({id:C.uid(),...v,status:'active'});event('quest',v.title);}),
      notices:()=>{const d=dialog('Notification history',s.notifications.slice().reverse().map(n=>`<article class="cps-rpg-skill"><h3>${E(n.title)}</h3>${note(n.body)}</article>`).join('')+s.shares.slice().reverse().map((x,i)=>`<article class="cps-rpg-skill"><h3>${E(x.title)}</h3>${note(x.description)}${buttons('Open',`received:${s.shares.length-1-i}`)}</article>`).join(''));d.querySelectorAll('[data-rpg^="received:"]').forEach(b=>b.onclick=()=>guard(()=>{const x=s.shares[Number(b.dataset.rpg.split(':')[1])];if(x.kind==='contact')addContact(x.contact);else detail(x.title,x.description||x.item?.name||'');}));},
      'unlock-relic':()=>{a.relic.unlocked=true;event('Relic','Manually unlocked for scenario');},'relic-point':()=>{if(!a.relic.unlocked)throw Error('Unlock Relic first');a.relic.points=C.cap(a.relic.points+1,0,99);event('Relic','Manual story award: 1 point');},
      'unlock-blackwall':()=>{a.blackwall.unlocked=true;event('Blackwall','Manually unlocked for scenario');},
      blackwall:()=>{if(!a.blackwall.unlocked||a.ram<4)throw Error('Blackwall locked or insufficient RAM');a.ram-=4;a.blackwall.exposure=C.cap(a.blackwall.exposure+20,0,100);a.stress=C.cap(a.stress+10,0,100);if(a.blackwall.exposure>=60){a.hp=C.cap(a.hp-15,0,a.maxHp);notify('BLACKWALL CONTAMINATION','Neural feedback: −15 health / +10 stress',true);}event('Blackwall',`${actorName} interfaces: exposure ${a.blackwall.exposure}`);},
      disconnect:()=>{a.blackwall.exposure=C.cap(a.blackwall.exposure-15,0,100);a.stress=C.cap(a.stress-5,0,100);s.turn++;event('Blackwall','Disconnected; recovered for one turn');},
    };
    if(actions[kind])actions[kind]();else if(kind==='slot')catalog(value);else if(kind==='socket-unlock'){C.patchActor(a,{implantUnlocks:{[value]:!a.implantUnlocks?.[value]}});event('implant sockets',`${actorName}: ${value}`);}else if(kind==='equip'){C.equip(a,value);event('equipment',`${actorName}: equipment changed`);}else if(kind==='use'){const it=C.use(a,value,s.turn);event('item used',`${actorName}: ${it.name}`);localSkill(actorName,it.name,it.effect,it);notify('ABILITY / '+it.name,it.effect||`${actorName} activated ${it.name}`);}else if(kind==='edit-item')editItem(a.inventory.find(x=>x.id===value));
    else if(kind==='remove-item'){const it=a.inventory.find(x=>x.id===value);if(it){it.quantity--;a.inventory=a.inventory.filter(x=>x.quantity>0);event('equipment removed',`${actorName}: ${it.name}`);}}
    else if(kind==='share-item'){const it=a.inventory.find(x=>x.id===value);if(it)share({kind:'item',title:it.name,item:it,description:it.effect},'user',api.context()?.name1||'User');}
    else if(kind==='skill'){const sk=a.skills.find(x=>x.id===value);if(sk){C.useSkill(a,sk,s.turn);event('skill',`${actorName}: ${sk.name}`);localSkill(actorName,sk.name,sk.description);}}
    else if(kind==='quest'){const q=s.quests.find(x=>x.id===value);if(q){q.status={active:'completed',completed:'failed',failed:'active'}[q.status]||'active';event('quest',`${q.title}: ${q.status}`);}}
    else if(kind==='share-quest'){const q=s.quests.find(x=>x.id===value);if(q)share({kind:'mission',title:q.title,description:`${q.description}\n${q.objective}\n${q.status}`},'user',api.context()?.name1||'User');}
    else if(kind==='relic'){if(!a.relic.unlocked||a.relic.points<1||a.relic.abilities.includes(value))throw Error('Relic locked or no points');a.relic.points--;a.relic.abilities.push(value);if(value==='Jailbreak')a.capacity+=20;if(value==='Emergency Cloaking')C.addSkill(a,{name:value,cost:20,resource:'stamina',cooldown:3,description:'Break visual contact in the role-play scene.'});if(value==='Vulnerability Analytics')C.addSkill(a,{name:value,cost:2,resource:'ram',cooldown:2,description:'Analyze an observable weak point; does not reveal secrets.'});event('Relic',`${actorName}: ${value} unlocked`);}
    save();render();
  }
  // Read-only card data: displaying history must never create an actor or spend resources.
  function skillReading(name,skill,record={},itemRecord=null){
    const player=['user','player',api.context?.()?.name1].includes(name),rpg=api.chatBucket?.()?.rpg;
    const npc=player?null:api.findEffectiveNpc?.(C.handle(name));
    const a=player?rpg?.player:rpg?.actors?.[`npc:${npc?.id||npc?.name?.toLowerCase()}`];
    const match=v=>String(v.name).toLowerCase()===String(skill).toLowerCase();
    const sk=a?.skills?.find(match),it=itemRecord||(!sk&&a?.inventory?.find(match));
    const legacy=player?api.effectiveRecords?.('skills')?.find(match):null;
    const info={description:record.description||sk?.description||it?.effect||legacy?.notes||'',category:it?.category||legacy?.category||'ABILITY',rank:legacy?.rank||'',level:legacy?.level??sk?.level,progress:legacy?.level??sk?.xp,maximum:legacy?.max??(sk?100:undefined),cost:sk?.cost??record.cost,resource:sk?.resource??record.resource,cooldown:sk?.cooldown??it?.cooldown??record.cooldown,slot:it?.slot,capacity:it?.category==='cyberware'?it.capacity:undefined};
    if(it){info.cost=it.category==='quickhack'?Math.max(1,Math.round(it.power/10)):undefined;info.resource=it.category==='quickhack'?'ram':undefined;}
    return info;
  }
  function skillKey(data){return data.id?`id:${C.text(data.id,160)}`:`payload:${api.fingerprint?.(JSON.stringify(data))||JSON.stringify(data)}`;}
  function rememberSkill(data,info){const s=state();s.skillReadings??=[];s.skillReadings.push({key:skillKey(data),info});s.skillReadings=s.skillReadings.slice(-300);}
  function skillHtml(name,skill,description='',info=null){
    info=info||skillReading(name,skill,{description});
    const number=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v));
    const field=(label,value)=>`<div><dt>${E(label)}</dt><dd>${E(value)}</dd></div>`;
    const stats=[number(info.cost)?field(tr('COST','ค่าใช้'),`${info.cost} ${String(info.resource||'').toUpperCase()}`):'',number(info.cooldown)?field(tr('COOLDOWN','คูลดาวน์'),`${info.cooldown} ${tr('turns','เทิร์น')}`):'',number(info.capacity)?field(tr('CAPACITY','ภาระติดตั้ง'),info.capacity):'',info.slot?field(tr('SLOT','ตำแหน่ง'),info.slot):''].join('');
    const progress=number(info.progress)&&number(info.maximum)&&Number(info.maximum)>0?C.cap(Number(info.progress)/Number(info.maximum)*100,0,100):null;
    const displayName=['user','player'].includes(name)?api.context?.()?.name1||tr('You','คุณ'):C.handle(name);
    return `<section class="cps-chat-block cps-chat-skill ${info.rejected?'rejected':''}"><div class="cps-chat-kicker">${icon('quickhack')}<span>${E(displayName)}</span><small>${E(info.rejected?tr('NOT ACTIVATED','ไม่ได้ใช้งาน'):tr('SKILL ACTIVATED','ใช้งานสกิล'))}</small></div><div class="cps-chat-skill-heading"><div><small>${E(String(info.category||'ABILITY').toUpperCase())}${number(info.level)?` / LV.${E(info.level)}`:''}</small><strong>${E(skill)}</strong></div>${info.rank?`<span class="cps-chat-skill-rank"><small>${E(tr('RANK','แรงก์'))}</small><b>${E(info.rank)}</b></span>`:''}</div>${(description||info.description)?note(description||info.description):''}${stats?`<dl class="cps-chat-skill-specs">${stats}</dl>`:''}${progress===null?'':`<div class="cps-chat-mastery"><div><span>${E(tr('MASTERY','ความชำนาญ'))}</span><b>${E(info.progress)} / ${E(info.maximum)}</b></div><div class="cps-progress" role="progressbar" aria-label="${E(tr('Mastery','ความชำนาญ'))}" aria-valuemin="0" aria-valuemax="${E(info.maximum)}" aria-valuenow="${C.cap(info.progress,0,info.maximum)}" style="--cps-progress:${progress}%"><i></i></div></div>`}${info.rejected?note(info.rejected):''}</section>`;
  }
  function localSkill(name,skill,description,itemRecord=null){const s=state(),index=(api.context()?.chat?.length||0)-1;s.skillCards??=[];s.skillCards.push({id:C.uid(),index,name,skill,description,info:skillReading(name,skill,{description},itemRecord)});s.skillCards=s.skillCards.slice(-100);save();document.querySelectorAll('.mes_text').forEach(decorate);}
  function decorate(element){const index=Number(element.closest('[mesid]')?.getAttribute('mesid'));if(!element.closest('[mesid]')||!Number.isInteger(index))return;for(const card of state().skillCards||[]){if(card.index!==index||[...element.querySelectorAll('[data-local-skill]')].some(n=>n.dataset.localSkill===card.id))continue;const block=document.createElement('div');block.dataset.localSkill=card.id;block.innerHTML=skillHtml(card.name,card.skill,card.description,card.info);element.append(block);}}
  function recordedSkill(data){const info=api.chatBucket?.()?.rpg?.skillReadings?.find(x=>x.key===skillKey(data))?.info;return skillHtml(data.actor||'user',data.name||'Ability',data.description||'',info||skillReading(data.actor||'user',data.name,{description:data.description,cost:data.cost,resource:data.resource,cooldown:data.cooldown}));}
  function decode(value){const n=document.createElement('div');n.innerHTML=value;return n.textContent||'';}
  function transform(value){let out=String(value||'').replace(/\[CP_SKILL\|([^\]|]+)\|([^\]]+)\]([\s\S]*?)\[\/CP_SKILL\]/gi,(_,name,skill,desc)=>recordedSkill({actor:decode(name),name:decode(skill),description:decode(desc)}));
    out=out.replace(/\[CP_SKILL\]([\s\S]*?)\[\/CP_SKILL\]/gi,(_,json)=>{try{const v=JSON.parse(decode(json));return recordedSkill(v);}catch{return '';}});
    out=out.replace(new RegExp(`\\[CP_(${tags})\\](?:[\\s\\S]*?)\\[\\/CP_\\1\\]`,'gi'),'');
    // Streamed machine payloads (especially breach secrets) must never flash in chat.
    return out.replace(new RegExp(`\\[CP_(?:${tags})\\][\\s\\S]*$`,'gi'),'');
  }
  function process(raw,key=''){
    if(!api.settings().enabled)return;const s=state(),claimed=new Set(s.processed);
    const records=[...String(raw||'').matchAll(new RegExp(`\\[CP_(${tags})\\]([\\s\\S]*?)\\[\\/CP_\\1\\]`,'gi'))];
    for(const m of String(raw||'').matchAll(/\[CP_SKILL\|([^\]|]+)\|([^\]]+)\]([\s\S]*?)\[\/CP_SKILL\]/gi))records.push([m[0],'SKILL',JSON.stringify({actor:m[1],name:m[2],description:m[3]})]);
    let changed=false;
    const turnKey=`turn:${String(key).replace(/:swipe:\d+$/, '')}`;if(!claimed.has(turnKey)){changed=true;claimed.add(turnKey);s.turn++;for(const a of [s.player,...Object.values(s.actors)]){const was=a.cyberpsychosis;C.tick(a,Math.random,s.settings.riskScale);if(!was&&a.cyberpsychosis)notify('NEURAL INSTABILITY','Cyberpsychosis episode: recover, reduce implant load or seek help in the story.',true);}}
    for(const m of records){let data;try{data=JSON.parse(m[2]);if(!data||Array.isArray(data)||typeof data!=='object')continue;}catch{continue;}
      const type=m[1].toUpperCase(),receipt=`record:${data.id?C.text(data.id,160):key+':'+type+':'+api.fingerprint(m[2])}`;if(claimed.has(receipt))continue;claimed.add(receipt);changed=true;
      try{
        if(type==='SKILL'){const a=actor(data.actor||'user');C.useSkill(a,data,s.turn);rememberSkill(data,skillReading(data.actor||'user',data.name,data));event('skill',`${data.actor||'user'}: ${data.name}`);}
        if(type==='STATE'){C.patchActor(actor(data.actor||'user'),data);event('status',`${data.actor||'user'}: ${C.text(data.reason||'Story status updated',500)}`);}
        if(type==='ITEM'){
          const a=actor(data.actor||'user');
          const it=a.inventory.find(x=>x.id===data.itemId||x.catalogId===data.itemId);
          if(data.operation==='remove') {if(!it)throw Error('Item missing');it.quantity-=Math.max(1,Math.round(C.cap(data.quantity??1,1,9999)));a.inventory=a.inventory.filter(x=>x.quantity>0);}
          else if(['equip','unequip'].includes(data.operation)) {if(!it)throw Error('Item missing');if(data.operation==='equip'&&!it.equipped)C.equip(a,it.id);else if(data.operation==='unequip')it.equipped=false;}
          else if(data.operation==='use') {if(!it)throw Error('Item missing');C.use(a,it.id,s.turn);localSkill(data.actor||'user',it.name,it.effect,it);}
          else if((!data.operation||data.operation==='add')&&data.item?.name) {const added=C.item(data.item);if(a.inventory.some(x=>x.id===added.id))throw Error('Item ID already stored; use its existing record');a.inventory.push(added);notify('EQUIPMENT RECEIVED',data.item.name);}
          else throw Error('Invalid equipment operation');
          event('equipment',`${data.actor||'user'}: ${data.operation||'add'} ${it?.name||data.item?.name||''}`);
        }
        if(type==='TRANSFER'){if(!data.from||['user','player',api.context()?.name1].includes(data.from))throw Error('Player transfers require the Transfer button or /cp transfer command.');transfer(data.from,data.to||'user',data.amount,data.reason,receipt);}
        if(type==='SHARE')share({...data,id:receipt},'assistant',data.from||api.chatBucket().call.peer?.name||'System');
        if(type==='LOCATION')location(data);
        if(type==='QUEST'){if(!C.text(data.title))throw Error('Quest title missing');const q=s.quests.find(x=>x.id===data.questId||x.title===data.title);const v={id:q?.id||C.text(data.questId||C.uid(),160),title:C.text(data.title,180),description:C.text(data.description||q?.description,4000),objective:C.text(data.objective||q?.objective,1000),status:['active','completed','failed'].includes(data.status)?data.status:q?.status||'active',location:data.location===null?null:data.location?globalThis.CyberpunkMap.normalizeLocation(data.location):q?.location};if(q)Object.assign(q,v);else s.quests.push(v);notify('MISSION UPDATE',`${v.title}: ${v.status}\n${v.objective}`);}
        if(type==='BREACH'){if(api.settings().hackingEnabled)beginBreach({...data,id:receipt});}
        if(type==='RELIC'){const a=actor(data.actor||'user');if(data.unlock===true)a.relic.unlocked=true;if(a.relic.unlocked&&data.points!==undefined)a.relic.points=C.cap(a.relic.points+Math.round(C.cap(data.points,-10,10)),0,99);}
        if(type==='BLACKWALL'){const a=actor(data.actor||'user');if(data.unlock===true)a.blackwall.unlocked=true;if(a.blackwall.unlocked&&data.exposure!==undefined)a.blackwall.exposure=C.cap(a.blackwall.exposure+C.cap(data.exposure,-100,100),0,100);}
        if(type==='CALL_END'){const call=api.chatBucket().call;if(call.active&&C.handle(data.actor).toLowerCase()===C.handle(call.peer?.name).toLowerCase()){if(data.reason)api.appendCallMessage('system',call.peer.name,C.text(data.reason));api.endCall();}}
      }catch(e){if(type==='SKILL')rememberSkill(data,{...skillReading(data.actor||'user',data.name,data),rejected:e.message});notify('SYSTEM RECORD REJECTED',`${type}: ${e.message}`);}
    }
    // Nested notifications and transfers may save; commit the full claim set last.
    if(!changed)return;
    s.processed=[...new Set([...s.processed,...claimed])].slice(-3000);save();render();
  }
  function prompt(){if(!api.settings().enabled)return '';const s=state();const a=s.player;const summary=x=>({balance:x.balance,hp:x.hp,maxHp:x.maxHp,stamina:x.stamina,maxStamina:x.maxStamina,ram:x.ram,maxRam:x.maxRam,capacity:x.capacity,implantUnlocks:x.implantUnlocks,location:x.location,stress:x.stress,cyberpsychosis:x.cyberpsychosis,inventory:x.inventory.slice(0,30).map(it=>({id:it.id,name:it.name,quantity:it.quantity,equipped:it.equipped,category:it.category,slot:it.slot,capacity:it.capacity})),skills:x.skills.slice(0,15),relic:x.relic,blackwall:x.blackwall});
    const active=s.puzzle&&['ready','running'].includes(s.puzzle.status);
    return `\n[Cyberware role-play state and event protocol]
This is fictional simulation only. Values are extension rules, not exact game balance. State is private narrator context; NPCs do not automatically know the player's balance, equipment, thoughts, location, hidden missions or other NPCs' information. No unearned powers or forced plot. Never simulate puzzle success: the user must play it.
Evaluate status, equipment, skills, missions and location changes after every normal main-chat reply. Emit all relevant updates in that same response; no extra API request is needed. Emit complete JSON records only for events that actually happen. Each record needs an id unique to that event; reuse that id if restating the same event. Do not print examples unless that event occurs. JSON strings must escape newlines and quotes. Never include closing tag text inside a JSON string.
- Show every actual ability use by USER or NPC with [CP_SKILL]{"id":"event-id","actor":"user or exact NPC name","name":"skill","description":"observable effect","resource":"ram or stamina","cost":2,"cooldown":1}[/CP_SKILL]. Do not invent user actions. Existing skill costs/cooldowns are authoritative. No repeated skill record for one action.
- When a scene requires decrypting an access point or shard: [CP_BREACH]{"id":"event-id","target":"terminal name","difficulty":2,"seconds":45,"buffer":8,"data":"data unlocked ONLY on success"}[/CP_BREACH]. Stop before revealing its secrets. Not an enemy quickhack.
- State updates: [CP_STATE]{"id":"event-id","actor":"user or exact NPC","hp":80,"stress":10}[/CP_STATE]. Use absolute numeric values. Accepts changed hp/maxHp, ram/maxRam, stamina/maxStamina, capacity and stress; omit unchanged fields. implantUnlocks:{"skeleton":true,"hands":true} is allowed only for established License to Chrome / Ambidextrous unlocks. Maxima/capacity increases require actual training, installed upgrades or an established story reward. Do not change balance here.
- NPC pays another stored contact or user: [CP_TRANSFER]{"id":"event-id","from":"exact NPC","to":"user","amount":100,"reason":"..."}[/CP_TRANSFER]. Insufficient balances reject. Never debit user; ask the user to use Transfer or /cp transfer @handle AMOUNT. A narration is not a completed transfer.
- Equipment acquired/lost: [CP_ITEM]{"id":"event-id","actor":"user","operation":"add","item":{"name":"...","category":"cyberware/weapons/quickhack/consumable/clothing/mod/component/data/item","quantity":1,"slot":"...","capacity":15,"effect":"..."}}[/CP_ITEM]. Cyberware slot must be frontal-cortex, face, operating-system, arms, hands, skeleton, nervous-system, circulatory-system, integumentary-system or legs. Existing inventory operations use operation remove/equip/unequip/use, exact itemId and quantity for removal. Use consumes resources, handles cooldown and shows a skill header automatically: do not emit an extra CP_SKILL for that same item action. Do not re-add equipped objects every turn.
- Attach a card inside a call or notifications: [CP_SHARE]{"id":"event-id","from":"NPC name","kind":"location/mission/item/contact/data","title":"...","description":"..."}[/CP_SHARE]. kind must be ONE enum value. For item add item object as above. For contact add contact object containing ALL nonempty fields: name, handle WITHOUT @, role, status, affiliation, age, gender, personality, appearance, notes; optional balance (nonnegative integer) and inventory (full item objects). Invent a coherent complete fictional profile when introducing a new contact; never merely create a name/handle stub. User clicks Add contact to accept.
- NPC may end its active call: [CP_CALL_END]{"id":"event-id","actor":"exact active caller name","reason":"..."}[/CP_CALL_END]. Use AFTER final CP_SIGNAL/attachments.
- Location change: [CP_LOCATION]{"id":"event-id","district":"watson/westbrook/city-center/heywood/santo-domingo/pacifica/dogtown/ncx-morro-rock/badlands (choose ONE)","subdistrict":"...","building":"...","floor":"...","area":"...","danger":false,"reason":"..."}[/CP_LOCATION]. Use actual established narrative location, not guesses; can trigger dangerous-zone alert. Optional numeric x,y are a paired CET game coordinate; z is elevation, separate from narrative floor. Omit coordinates unless established by a saved pin or supplied by the user; never invent exact coordinates from a place name. With actor:"exact NPC name", update only that contact location. Set knownToUser:true only when their location has been shared with the user; otherwise it stays private and has no visible map marker.
- Mission updates: [CP_QUEST]{"id":"event-id","questId":"stable quest id","title":"...","description":"...","objective":"...","status":"active/completed/failed (choose ONE)"}[/CP_QUEST]. Optional location:{"district":"watson","subdistrict":"Kabuki"} adds a mission marker. Location accepts the same named fields and established numeric x,y,z; omit unknown coordinates. Set location:null to remove its marker.
- Only when story earned: [CP_RELIC]{"id":"event-id","actor":"user","unlock":true,"points":1}[/CP_RELIC] or [CP_BLACKWALL]{"id":"event-id","actor":"user","unlock":true,"exposure":10}[/CP_BLACKWALL]. Do not award repeatedly. Blackwall/Relic are optional scenario mechanics, avoid story spoilers.
Private player state: ${JSON.stringify(summary(a))}
Stored NPC assets (private narrator context): ${JSON.stringify(api.effectiveRecords('npcs').slice(0,20).map(n=>({name:n.name,...summary(actor(n.name))})))}
Location: ${JSON.stringify(s.map.location)}
Active missions: ${JSON.stringify(s.quests.filter(q=>q.status==='active').slice(-10))}
Pending breach: ${active?JSON.stringify({target:s.puzzle.target,status:s.puzzle.status}):'none'}
Recent authoritative outcomes (do not replay records for these): ${JSON.stringify(s.events.slice(-12))}`;
  }
  function ensureWand(){const host=document.getElementById('extensionsMenu'),old=document.getElementById('cyberpunk-cyberware-wand');if(!api.settings().showWand){old?.remove();return;}if(!host||old)return;const b=document.createElement('div');b.id='cyberpunk-cyberware-wand';b.className='list-group-item flex-container flexGap5 interactable';b.tabIndex=0;b.setAttribute('role','button');b.innerHTML='<i class="fa-solid fa-microchip fa-fw"></i><span>Cyberware</span>';b.onclick=e=>{e.preventDefault();e.stopPropagation();api.closeHostWand();open();};b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();b.click();}};host.append(b);}
  function onChatChanged(){document.querySelectorAll('.cps-rpg-dialog').forEach(api.removeUiDialog);closePanel();stopBreach();api.removeUiDialog(popup);popup=null;noticeTimers.forEach(clearTimeout);noticeTimers.clear();document.getElementById('cps-immersion')?.remove();minimized();}
  return Object.freeze({open,process,prompt,transform,decorate,ensureWand,callToolbar,attachment,userText,onChatChanged,beginBreach,state:()=>JSON.parse(JSON.stringify(state())),transfer,share,addContact,icon});
};
})();
