/* Chat-local direct messages and UI audio. Never initiates a real phone call. */
(() => {
'use strict';
globalThis.CyberpunkCommsFactory=api=>{
 const E=api.htmlEscape,tr=(en,th)=>api.settings().language==='th'?th:en;
 let window=null,thread=null,owner=null,request=null,serial=0,loop=null;
 const audio=new Map();let pendingLoop=null,pendingMessage=false,floating=null,minimized=null,audioStatus='',messagePrimed=false;
 const glyph=name=>globalThis.CyberpunkRpgCore.arrow(name);
 function soundStatus(value){audioStatus=value;const label=window?.querySelector('[data-dm-audio-status]');if(label)label.textContent=value;}
 function sound(key){let a=audio.get(key);if(!a){a=new Audio(api.assetUrl('assets/audio/'+files[key]));a.preload='auto';audio.set(key,a);}return a;}
 function primeMessage(){if(messagePrimed||api.settings().phoneSounds===false)return;try{const a=sound('message');a.muted=true;const token=a.cpsToken=(a.cpsToken||0)+1;const done=()=>{if(a.cpsToken===token){a.pause();a.currentTime=0;a.muted=false;}};Promise.resolve(a.play()).then(()=>{messagePrimed=true;done();},done);}catch{/* A visible test button remains available. */}}
 function refreshFloating(){if(!floating)return;const t=minimized;floating.querySelector('strong').textContent=t.name;floating.querySelector('small').textContent=request?.thread===t?tr('Waiting for reply…','กำลังรอคำตอบ…'):t.unread?tr('New messages: ','ข้อความใหม่: ')+t.unread:tr('Open messages','เปิดข้อความ');}
 function removeFloating(){floating?.remove();floating=null;minimized=null;}
 function minimize(){if(!thread)return;const t=thread;close();removeFloating();minimized=t;const b=document.createElement('button');b.type='button';b.className='cps-ui cps-dm-minimized';b.setAttribute('popover','manual');b.innerHTML= glyph('up-right')+'<span><strong></strong><small role="status"></small></span>';b.onclick=()=>open(t.name);floating=b;document.body.append(b);try{b.showPopover?.();}catch{}refreshFloating();b.focus();}

 const files={ring:'v-phone-ringtone.mp3',outgoing:'outgoing-call.mp3',open:'opening-phone-contacts.mp3',close:'closing-phone-contacts.mp3',message:'v-phone-new-message.mp3'};
 function stopAudio(){for(const a of audio.values()){a.pause();a.currentTime=0;}loop=null;pendingLoop=null;}
 function stopLoop(){pendingLoop=null;if(loop){loop.pause();loop.currentTime=0;loop=null;}}
function play(key,repeat=false){if(api.settings().enabled===false||api.settings().phoneSounds===false)return;if(document.hidden){if(key==='message')pendingMessage=true;return;}try{const a=sound(key);a.cpsToken=(a.cpsToken||0)+1;a.muted=false;if(repeat)stopLoop();a.loop=repeat;a.volume=Math.max(0,Math.min(1,Number(api.settings().phoneVolume??55)/100));a.currentTime=0;if(repeat){loop=a;pendingLoop=key;}return Promise.resolve(a.play()).then(()=>{if(key==='message'){messagePrimed=true;soundStatus(tr('Sound ready','เสียงพร้อมใช้งาน'));}},()=>{if(!repeat)soundStatus(tr('Tap Test sound below to enable notifications.','แตะ ทดสอบเสียง ด้านล่างเพื่อเปิดเสียงแจ้งเตือน'));});}catch{soundStatus(tr('Sound unavailable. Try Test sound again.','เสียงไม่พร้อมใช้งาน ลองกดทดสอบเสียงอีกครั้ง'));}}

 function store(){const b=api.chatBucket();if(!Array.isArray(b.directThreads))b.directThreads=[];return b.directThreads;}
 function get(name){const npc=api.findEffectiveNpc(name);if(!npc||api.npcDisabled(name))throw Error(tr('Enabled contact required','ต้องเป็นผู้ติดต่อที่เปิดใช้อยู่'));const key=npc.id||npc.name;let t=store().find(t=>t.key===key);if(!t){t={key,name:npc.name,messages:[],draft:'',unread:0};store().push(t);}t.name=npc.name;return t;}
 function append(t,role,text,attachment=null,renderNow=true,notify=true){const value=String(text||'').trim().slice(0,4000);if(!value&&!attachment)return;const m={id:'dm-'+Date.now().toString(36)+'-'+(++serial),role,name:role==='user'?api.context()?.name1||'USER':t.name,text:value,at:new Date().toISOString(),pending:role==='user'&&!attachment};if(attachment)m.attachment=attachment;t.messages.push(m);if(role==='assistant'){if(window?.isConnected&&thread===t&&!document.hidden)t.unread=0;else t.unread=Math.min(999,(t.unread||0)+1);if(notify)play('message');}api.saveChat();refreshFloating();if(renderNow&&window?.isConnected&&thread===t)render();return m;}
 function receive(name,text){try{const t=get(name);return append(t,'assistant',text);}catch(e){api.toast(e.message);}}
 function destination(t=thread,bucket=owner){return {peer:t?.name,valid:()=>bucket===api.chatBucket()&&store().includes(t),append:(role,name,text,attachment)=>{if(bucket!==api.chatBucket()||!store().includes(t))return;const m=append(t,role,text,attachment);if(m&&attachment&&role==='user'&&attachment.kind!=='receipt')m.pending=true;api.saveChat();return m;}};}
 function close(){if(window)api.removeUiDialog(window);window=null;}
 function cancel(){const old=request;if(!old)return;request=null;old.cancel();api.systems().support.cancel('message');old.pending.forEach(m=>m.pending=true);api.saveChat();render();}
 function changed(){cancel();close();owner=null;thread=null;removeFloating();pendingMessage=false;stopAudio();}
 function render(){refreshFloating();if(!window?.isConnected||owner!==api.chatBucket()||!thread)return;const t=thread,bucket=owner,log=window.querySelector('.cps-dm-log'),atBottom=log.scrollHeight-log.scrollTop-log.clientHeight<70,scroll=log.scrollTop;log.replaceChildren();
  for(const m of t.messages){const row=document.createElement('article');row.className='cps-dm-row '+m.role;row.dataset.dmId=m.id;row.innerHTML=`<header><span>${E(m.role==='user'?tr('YOU','คุณ'):t.name)}</span><time>${E(new Date(m.at).toLocaleTimeString(api.settings().language,{hour:'2-digit',minute:'2-digit'}))}</time></header><div class="cps-dm-copy">${E(m.text)}</div><small>${E(m.pending?tr('Queued · press Send for reply','เข้าคิวแล้ว · กดส่งเพื่อรับคำตอบ'):m.role==='user'?tr('Sent','ส่งแล้ว'):'')}</small>`;api.systems().attachment(row,m);api.animateText?.(row.querySelector('.cps-dm-copy'),m);
   if(!m.attachment){const actions=document.createElement('div');actions.className='cps-dm-row-actions';for(const kind of m.role==='user'?['edit','delete']:['regenerate','delete']){const b=document.createElement('button');b.type='button';b.className='cps-button';b.textContent=kind==='edit'?tr('Edit','แก้ไข'):kind==='delete'?tr('Delete','ลบ'):tr('Regenerate','สร้างใหม่');b.disabled=!!request;b.onclick=()=>{if(bucket!==api.chatBucket()||thread!==t||request||!t.messages.includes(m))return;if(kind==='regenerate')return send(m);if(kind==='delete'){t.messages=t.messages.filter(x=>x!==m);api.saveChat();render();return;}const editor=document.createElement('textarea');editor.value=m.text;editor.maxLength=4000;editor.setAttribute('aria-label',tr('Edit message','แก้ไขข้อความ'));const save=document.createElement('button');save.className='cps-button';save.textContent=tr('Save','บันทึก');save.onclick=()=>{if(bucket!==api.chatBucket()||thread!==t||request||!t.messages.includes(m)||!editor.value.trim())return;m.text=editor.value.trim();m.pending=true;api.saveChat();render();};actions.replaceChildren(editor,save);};actions.append(b);}row.append(actions);}log.append(row);
  }
  const queued=t.messages.filter(m=>m.role==='user'&&m.pending).length;window.querySelector('[data-dm-status]').textContent=request?tr('Waiting for reply…','กำลังรอคำตอบ…'):queued?tr(`${queued} queued · press Send to generate`,`เข้าคิว ${queued} ข้อความ · กดส่งเพื่อเริ่มเจน`):'';window.querySelector('[data-dm-cancel]').hidden=!request;window.querySelector('[data-dm-send]').disabled=!!request;requestAnimationFrame(()=>{if(log.isConnected)log.scrollTop=atBottom?log.scrollHeight:scroll;});
 }
 function queue(){if(!thread||!window?.isConnected||request||owner!==api.chatBucket())return false;const input=window.querySelector('textarea.cps-dm-input'),value=input.value.trim();if(!value)return false;const m=append(thread,'user',value);input.value='';thread.draft='';api.systems().userText(m.text,m.id,destination(thread,owner));api.saveChat();return true;}
 async function send(replace=null){if(!thread||!window?.isConnected||request||api.busy()||api.npcDisabled(thread.name)||owner!==api.chatBucket()){api.toast(tr('Wait for the current generation','รอการสร้างข้อความปัจจุบัน'));return;}primeMessage();const t=thread,bucket=owner,input=window.querySelector('textarea.cps-dm-input');if(!replace&&input.value.trim())queue();const pending=replace?[]:t.messages.filter(m=>m.pending);if(!replace&&!pending.length)return;
  const transcript=(replace?t.messages.slice(0,t.messages.indexOf(replace)):t.messages).slice(-16).map(m=>`${m.role}: ${m.text}${m.attachment?'\nAttachment: '+JSON.stringify(m.attachment):''}`).join('\n');const npc=api.findEffectiveNpc(t.name);let reject;const cancelled=new Promise((_,r)=>reject=r);const job={thread:t,pending,cancel:()=>reject(Error('Cancelled'))};request=job;pending.forEach(m=>m.pending=false);api.saveChat();render();
  try{const prompt=`Private text-message conversation, NOT a phone call. Reply as ${t.name} only. Match the language, register, and writing style of the newest USER role-play message and established SillyTavern dialogue; ignore the extension UI language. NPC dossier: ${JSON.stringify(npc)}.\n${api.contextPrompt()}\n${api.systems().channelPrompt('message',t.name)}\nDIRECT MESSAGE TRANSCRIPT:\n${transcript}\n${replace?`Return exactly one [CP_MESSAGE|${t.name}]replacement[/CP_MESSAGE].`:`Return 2–5 separate [CP_MESSAGE|${t.name}]message bubble[/CP_MESSAGE] records, choosing the natural count for this character and moment. Keep each bubble focused; do not combine them into one long block.`} Never emit CP_SIGNAL, CP_CALL_REQUEST or CP_CALL_END. Never control the player or repeat earlier messages. ${replace?'Regenerate only this reply; NO gameplay records or transactions.':''}`;
   const result=await Promise.race([api.systems().support.generate('message',prompt,{hostContext:true,responseLength:1200}),cancelled]);if(request!==job||bucket!==api.chatBucket()||!store().includes(t)||api.npcDisabled(t.name))return;
   const matches=api.parse(result,'CP_MESSAGE').filter(m=>[t.name,npc?.handle].filter(Boolean).some(n=>String(n).toLowerCase()===String(m[1]).toLowerCase()));const texts=matches.map(m=>api.strip(m[6]).trim()).filter(Boolean).slice(0,5);if(!texts.length&&!/\[CP_/i.test(result))texts.push(api.strip(result).trim());if(texts.length===1&&texts[0].length>160){const parts=texts[0].split(/(?<=[.!?。！？])\s*|\n+/u).map(x=>x.trim()).filter(Boolean);if(parts.length>1){texts.length=0;let bubble='';for(const part of parts){if(bubble&&(bubble+' '+part).length>150&&texts.length<4){texts.push(bubble);bubble=part;}else bubble+=(bubble?' ':'')+part;}if(bubble)texts.push(bubble);}}if(!texts.length)throw Error('Empty private message response');
   if(replace){if(!t.messages.includes(replace))return;replace.text=texts.join('\n\n');api.saveChat();}else{for(const [i,text] of texts.entries())append(t,'assistant',text,null,false,i===0);const safe=result.replace(/\[CP_(?:CALL_END|CALL_REQUEST|SIGNAL)(?:\|[^\]]*)?\][\s\S]*?\[\/CP_(?:CALL_END|CALL_REQUEST|SIGNAL)\]/gi,'');api.systems().process(safe,'dm:'+pending.map(m=>m.id).join(','),{destination:destination(t,bucket)});}
  }catch(e){if(request===job&&bucket===api.chatBucket()){pending.forEach(m=>m.pending=true);api.saveChat();api.toast(e.message);}}finally{if(request===job){request=null;render();}}
 }
 function open(name){try{if(!api.settings().enabled)return;const t=get(name);if(window?.isConnected&&t===thread)return;close();if(minimized===t)removeFloating();owner=api.chatBucket();thread=t;t.unread=0;api.saveChat();api.beforeOpen();const d=document.createElement('dialog');d.className='cps-ui cps-dm-window';d.setAttribute('aria-label',tr('Messages with ','ข้อความกับ ')+t.name);d.innerHTML=`<header class="cps-dm-top"><span>PERSONAL MESSAGES</span><button type="button" class="cps-button" data-dm-minimize aria-label="${E(tr('Minimize messages','ย่อข้อความ'))}">${glyph('minimize')}</button><button type="button" class="cps-button cps-end-call" data-dm-close>${E(tr('Close','ปิด'))}</button></header><header class="cps-dm-contact">${api.avatar(t.name)}<div><small>DIRECT CHANNEL</small><h2>${E(t.name)}</h2><p>${E(tr('Private messages','ข้อความส่วนตัว'))}</p></div></header><main class="cps-dm-log" role="log" aria-live="polite" aria-label="${E(tr('Messages','ข้อความ'))}"></main><footer class="cps-dm-composer"><label for="cps-dm-input">${E(tr('TO ','ถึง ')+t.name)}</label><div class="cps-dm-compose-row"><textarea class="cps-dm-input" id="cps-dm-input" rows="2" maxlength="4000" enterkeyhint="send" placeholder="${E(tr('Type a message…','พิมพ์ข้อความ…'))}"></textarea><button type="button" class="cps-button primary" data-dm-send aria-label="${E(tr('Generate reply','เริ่มเจนคำตอบ'))}">${glyph('up-right')}</button></div><div class="cps-dm-audio"><button type="button" class="cps-button" data-dm-sound>${E(tr('Test sound','ทดสอบเสียง'))}</button><span data-dm-audio-status role="status">${E(audioStatus||tr('Enter = queue message · Send = generate reply','Enter ส่งเข้าคิว · ปุ่มส่งเริ่มเจนคำตอบ'))}</span></div><div class="cps-dm-status"><span data-dm-status role="status"></span><button type="button" class="cps-button" data-dm-cancel hidden>${E(tr('Cancel generation','ยกเลิกการสร้าง'))}</button></div></footer>`;window=d;d.querySelector('[data-dm-close]').onclick=close;d.querySelector('[data-dm-minimize]').onclick=minimize;d.querySelector('[data-dm-sound]').onclick=()=>{api.settings().phoneSounds=true;if(Number(api.settings().phoneVolume??55)<=0)api.settings().phoneVolume=55;api.saveSettings();play('message');};d.addEventListener('cancel',e=>{e.preventDefault();close();});const input=d.querySelector('textarea');input.value=t.draft||'';input.oninput=()=>{t.draft=input.value;api.saveChat();};input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();e.stopPropagation();queue();}};d.querySelector('[data-dm-send]').onclick=()=>send();d.querySelector('[data-dm-cancel]').onclick=cancel;document.body.append(d);api.systems().callToolbar(d,destination(t,owner));api.showUiDialog(d);render();}catch(e){api.toast(e.message);}}
 function list(){if(!api.settings().enabled)return;api.beforeOpen();close();owner=api.chatBucket();const d=document.createElement('dialog');d.className='cps-ui cps-dm-window';d.setAttribute('aria-label',tr('Messages','ข้อความ'));d.innerHTML=`<header class="cps-dm-top"><span>PERSONAL MESSAGES</span><button class="cps-button" type="button" data-close>×</button></header><main class="cps-dm-directory">${api.contacts().map(n=>{const t=store().find(t=>t.key===(n.id||n.name));return `<button class="cps-dm-contact-button" type="button" data-peer="${E(n.name)}">${api.avatar(n.name)}<span><strong>${E(n.name)}</strong><small>${E(t?.messages.at(-1)?.text||tr('Start conversation','เริ่มสนทนา'))}</small></span><b>${t?.unread||''}</b></button>`;}).join('')}<details><summary>${E(tr('Legacy call transcript (read only)','ประวัติสายเดิม (อ่านอย่างเดียว)'))}</summary><div class="cps-dm-legacy">${api.chatBucket().call.messages.map(m=>`<p><b>${E(m.name)}</b> ${E(m.text)}</p>`).join('')}</div></details></main>`;window=d;thread=null;d.querySelector('[data-close]').onclick=close;d.addEventListener('cancel',e=>{e.preventDefault();close();});const bucket=owner;d.querySelectorAll('[data-peer]').forEach(b=>b.onclick=()=>{if(bucket===api.chatBucket())open(b.dataset.peer);});document.body.append(d);api.showUiDialog(d);}
 document.addEventListener('pointerdown',()=>{if(pendingLoop&&loop?.paused)play(pendingLoop,true);},{passive:true});
 document.addEventListener('visibilitychange',()=>{if(document.hidden){const key=pendingLoop;stopAudio();pendingLoop=key;}else {if(pendingLoop)play(pendingLoop,true);if(pendingMessage){pendingMessage=false;play('message');}}});globalThis.addEventListener('pagehide',stopAudio);
 const route=name=>{const t=store().find(t=>t.name===name);return t?destination(t,api.chatBucket()):{peer:name,valid:()=>true,append:()=>{}};};
 return {open,list,receive,append,destination,route,play,stopLoop,stopAudio,changed,close,cancel,busy:()=>!!request};
};
})();
