/* Estate Grid housing layer. Extends the connected asset system without changing vehicles. */
(() => {
'use strict';
const BaseFactory=globalThis.CyberpunkAssetsFactory;
globalThis.CyberpunkAssetsFactory=api=>{
 const base=BaseFactory(api),C=globalThis.CyberpunkRpgCore,E=api.htmlEscape;
 const tr=(en,th)=>api.settings?.()?.language==='th'?th:en;
 const copy=v=>JSON.parse(JSON.stringify(v));
 const presetFiles=['img-7707.webp','img-7710.webp','img-7711.webp','img-7712.webp','img-7713.webp','img-7714.webp','img-7715.webp','img-7716.webp'];
 const presets=presetFiles.map((file,index)=>({id:'estate-'+(index+1),file,label:tr('Night City interior '+(index+1),'ที่พัก Night City '+(index+1))}));
 const state=()=>api.state();
 const preset=id=>presets.find(x=>x.id===id)||presets[0];
 const bannerUrl=home=>home.customBanner||api.assetUrl?.('assets/properties/'+preset(home.bannerPreset).file)||'';
 const bannerStyle=home=>`style="--cps-estate-image:url('${E(bannerUrl(home))}')"`;
 const activeHomes=()=>state().properties.filter(x=>x.status!=='sold');
 const leaseActive=home=>home.tenure!=='rent'||Number(home.lease?.expiresTurn||0)>state().turn;
 const leaseRemaining=home=>Math.max(0,Number(home.lease?.expiresTurn||0)-state().turn);
 function hydrate(home){
   if(!home)return home;
   home.storage=Array.isArray(home.storage)?home.storage:[];
   home.upgrades=home.upgrades&&typeof home.upgrades==='object'?home.upgrades:{};
   home.rooms=Array.isArray(home.rooms)?home.rooms:[];
   home.serviceLog=Array.isArray(home.serviceLog)?home.serviceLog:[];
   home.tenure=home.tenure==='rent'?'rent':'owned';
   // Existing saves predate Home Level and remain fully usable; only newly registered homes start at LV.0.
   if(!Number.isInteger(home.homeLevel))home.homeLevel=1;
   home.homeLevel=Math.max(0,Math.min(5,home.homeLevel));
   home.bannerPreset=preset(home.bannerPreset).id;
   if(home.tenure==='rent'&&home.status!=='sold'){
     home.lease=home.lease&&typeof home.lease==='object'?home.lease:{};
     home.lease.term=Math.max(1,Math.min(9999,Math.floor(Number(home.lease.term)||7)));
     home.lease.price=C.money(home.lease.price??home.price??0);
     home.lease.buyoutPrice=C.money(home.lease.buyoutPrice??Math.max(home.price||0,home.lease.price*10));
     if(!Number.isInteger(home.lease.expiresTurn))home.lease.expiresTurn=state().turn+home.lease.term;
     home.status=leaseActive(home)?'leased':'expired';
   } else home.status=home.status==='sold'?'sold':'owned';
   return home;
 }
 const homeById=id=>{const home=state().properties.find(x=>x.id===id&&x.status!=='sold');if(!home)throw Error('Owned or leased property required');return hydrate(home);};
 const save=()=>{api.saveChat();api.refreshPrompt();};
 const log=(home,operation,detail='',cost=0)=>{home.serviceLog.push({at:Date.now(),operation,detail:C.text(detail,240),cost});home.serviceLog=home.serviceLog.slice(-100);};
 const charge=(amount,reason)=>{amount=C.money(amount);const p=state().player;if(p.balance<amount)throw Error(tr('Insufficient balance','ยอดเงินไม่เพียงพอ'));p.balance-=amount;p.ledger.push({id:C.uid(),delta:-amount,reason,at:new Date().toISOString()});p.ledger=p.ledger.slice(-300);return amount;};
 const residenceRequired=home=>{if(!leaseActive(home))throw Error(tr('Lease expired. Renew or buy out this property first.','สัญญาหมดอายุ กรุณาต่อสัญญาหรือซื้อถาวรก่อน'));};
 function upgradeQuote(home,area){
   home=hydrate(home);if(!['security','stash','garage','workshop','living'].includes(area))throw Error('Unknown home upgrade');
   const level=Number(home.upgrades[area]||0),cost=({security:500,stash:400,garage:1000,workshop:750,living:500})[area]*(level+1);
   const effect={security:tr('Narrative security level; no hidden combat rolls.','ระดับความปลอดภัยประกอบเรื่อง ไม่มีการสุ่มต่อสู้ซ่อนอยู่'),stash:tr(`Stack slots ${20+20*level} → ${40+20*level}`,`ช่องกองไอเท็ม ${20+20*level} → ${40+20*level}`),garage:tr(`Vehicle spaces ${1+level} → ${2+level}`,`ที่จอดรถ ${1+level} → ${2+level}`),workshop:tr(`Crafting equipment ceiling ${level*10} → ${(level+1)*10}`,`เพดานอุปกรณ์คราฟต์ ${level*10} → ${(level+1)*10}`),living:tr(`Rest power rises to LV.${level+1}`,`ประสิทธิภาพการพักเพิ่มเป็น LV.${level+1}`)}[area];
   const blocked=!leaseActive(home)?tr('Renew the lease first','ต่อสัญญาก่อน'):home.homeLevel<1?tr('Initialize Home Level 1 first','เริ่ม Home Level 1 ก่อน'):level>=5?tr('Maximum level 5','สูงสุดเลเวล 5'):state().player.balance<cost?tr(`Need €$${cost-state().player.balance} more`,`เงินขาด €$${cost-state().player.balance}`):'';
   return {area,level,next:Math.min(5,level+1),cost,effect,blocked};
 }
 function transact(kind,id,operation,input={}){
   if(kind!=='property')return base.transact(kind,id,operation,input);
   const home=homeById(id),s=state();if(s.bd.status!=='stopped'||s.bd.rendering)throw Error('Exit Braindance first');
   if(['deposit','withdraw','craft','upgrade-item','rest'].includes(operation)){residenceRequired(home);if(home.homeLevel<1)throw Error(tr('Initialize Home Level 1 first','เริ่ม Home Level 1 ก่อน'));return base.transact(kind,id,operation,input);}
   let cost=0,detail='';
   if(operation==='home-foundation'){
     residenceRequired(home);if(home.homeLevel>=1)throw Error(tr('Home systems are already initialized','ระบบบ้านเริ่มทำงานแล้ว'));cost=charge(4800,'home-foundation: '+home.name);home.homeLevel=1;detail='LV.0 → LV.1';
   }else if(operation==='home-upgrade'){
     const q=upgradeQuote(home,input.area);if(q.blocked)throw Error(q.blocked);if(input.expectedLevel!==undefined&&Number(input.expectedLevel)!==q.level)throw Error('Upgrade changed; refresh the quote');cost=charge(q.cost,'home-upgrade: '+home.name);home.upgrades[q.area]=q.next;detail=q.area+' LV.'+q.level+' → '+q.next;
   }else if(operation==='enter'){
     residenceRequired(home);home.lastVisited=new Date().toISOString();s.map.location={...s.map.location,building:home.name,area:'Entrance'};detail=home.location||'';
   }else if(operation==='renew-lease'){
     if(home.tenure!=='rent')throw Error(tr('This property is permanently owned','อสังหาริมทรัพย์นี้เป็นของคุณถาวรแล้ว'));cost=charge(home.lease.price,'renew-lease: '+home.name);home.lease.expiresTurn=Math.max(s.turn,home.lease.expiresTurn)+home.lease.term;home.lease.noticeKey='';home.status='leased';detail=`+${home.lease.term} turns · ends ${home.lease.expiresTurn}`;
   }else if(operation==='buyout'){
     if(home.tenure!=='rent')throw Error(tr('This property is already owned','อสังหาริมทรัพย์นี้เป็นของคุณแล้ว'));cost=charge(home.lease.buyoutPrice,'buyout: '+home.name);home.tenure='owned';home.status='owned';delete home.lease;detail='PERMANENT OWNERSHIP';
   }else if(operation==='banner'){
     const id=C.text(input.preset,40);if(!presets.some(x=>x.id===id))throw Error('Choose a banner preset');home.bannerPreset=id;delete home.customBanner;detail=id;
   }else if(operation==='custom-banner'){
     const data=String(input.data||'');if(!/^data:image\/(?:png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(data)||data.length>800000)throw Error(tr('Choose a PNG, JPEG or WebP image under 550 KB','เลือกภาพ PNG, JPEG หรือ WebP ไม่เกิน 550 KB'));home.customBanner=data;detail='DEVICE IMAGE';
   }else if(operation==='details'){
     home.nickname=C.text(input.nickname,100);home.description=C.text(input.description,4000);home.notes=C.text(input.notes,4000);detail='DOSSIER';
   }else if(operation==='add-room'){
     residenceRequired(home);if(home.homeLevel<1)throw Error(tr('Initialize Home Level 1 first','เริ่ม Home Level 1 ก่อน'));if(home.rooms.length>=30)throw Error('Room limit reached');const name=C.text(input.name,120);if(!name)throw Error(tr('Room name required','กรุณาใส่ชื่อห้อง'));cost=charge(2500,'add-room: '+home.name);const selected=C.text(input.preset,40),room={id:C.uid(),name,type:C.text(input.type,80)||'room',description:C.text(input.description,1000),...(presets.some(x=>x.id===selected)?{bannerPreset:selected}:{})};home.rooms.push(room);detail=name;
   }else if(operation==='room-details'){
     const room=home.rooms.find(x=>x.id===input.roomId);if(!room)throw Error('Room not found');room.name=C.text(input.name,120)||room.name;room.type=C.text(input.type,80)||room.type;room.description=C.text(input.description,1000);detail=room.name;
   }else if(operation==='room-banner'){
     const room=home.rooms.find(x=>x.id===input.roomId);if(!room)throw Error('Room not found');const id=C.text(input.preset,40);if(!presets.some(x=>x.id===id))throw Error('Choose a room image');room.bannerPreset=id;delete room.customBanner;detail=room.name;
   }else throw Error('Unsupported estate action');
   log(home,operation,detail,cost);api.event?.('estate service',operation+': '+home.name+' · '+detail+(cost?' · €$'+cost:''));save();return home;
 }
 function syncLeases(){
   for(const home of activeHomes().map(hydrate)){if(home.tenure!=='rent')continue;const remaining=leaseRemaining(home),key=home.lease.expiresTurn+':'+(remaining===0?'expired':'due');if(remaining<=3&&home.lease.noticeKey!==key){home.lease.noticeKey=key;save();api.mailReceive?.({id:'lease:'+home.id+':'+key,from:'NIGHT CITY PROPERTY SERVICES',subject:remaining?tr('Lease renewal due','แจ้งต่อสัญญาเช่า'):tr('Lease expired','สัญญาเช่าหมดอายุ'),body:remaining?tr(`${home.name} expires in ${remaining} story turns. Renew directly below or from Estate Grid.`,`${home.name} จะหมดสัญญาใน ${remaining} เทิร์น ต่อสัญญาด้านล่างหรือใน Estate Grid ได้เลย`):tr(`${home.name} is locked until the lease is renewed or bought out.`,`${home.name} ถูกระงับการใช้งานจนกว่าจะต่อสัญญาหรือซื้อถาวร`),leaseAction:{propertyId:home.id,price:home.lease.price,term:home.lease.term}});}}
 }
 const moduleSvg={overview:'<path d="M4 6h16v12H4zM8 10h8m-8 4h5"/>',storage:'<path d="M4 8h16v11H4zM7 8V5h10v3m-6 4h2"/>',workshop:'<path d="m5 19 5-5m4-4 5-5M8 5l3 3-6 6-3-3zm8 11 3 3"/>',upgrades:'<path d="M12 3v18M5 10l7-7 7 7M5 17h14"/>',living:'<path d="M4 17v-6h16v6M7 11V7h4v4m2 0V7h4v4M4 20h16"/>',garage:'<path d="M3 17V9l9-5 9 5v8M7 17v-5h10v5M8 20a2 2 0 1 0 0-.1m8 .1a2 2 0 1 0 0-.1"/>',rooms:'<path d="M4 4h7v7H4zm9 0h7v7h-7zM4 13h7v7H4zm9 0h7v7h-7z"/>',history:'<path d="M4 12a8 8 0 1 0 2-5M4 4v6h6m2-4v6l4 2"/>'};
 const svg=key=>`<svg viewBox="0 0 24 24" aria-hidden="true">${moduleSvg[key]}</svg>`;
 function propertyMarkup(){
   syncLeases();const homes=state().properties.map(hydrate),live=homes.filter(x=>x.status!=='sold');
   return `<header class="cps-estate-mast"><div><small>ESTATE GRID / NIGHT CITY</small><h2>${E(tr('Your places. Your rules.','พื้นที่ของคุณ กฎของคุณ'))}</h2><p>${E(tr('Homes, apartments and rentals on one residential network.','บ้าน อพาร์ตเมนต์ และห้องเช่าในเครือข่ายเดียว'))}</p></div><strong>${String(live.length).padStart(2,'0')}<small>LOCATIONS</small></strong></header><div class="cps-rpg-actions cps-estate-create">${api.buttons(tr('Add property','เพิ่มที่พัก'),'asset-buy:property')}</div><div class="cps-estate-grid">${homes.map(home=>{const expired=!leaseActive(home);return `<article class="cps-estate-card ${home.status==='sold'?'sold':''} ${expired?'expired':''}"><div class="cps-estate-card-banner" ${bannerStyle(home)}><span>${E(home.tenure==='rent'?(expired?'LEASE EXPIRED':`LEASE · ${leaseRemaining(home)}T`):'PERMANENT')}</span></div><div class="cps-estate-card-copy"><small>${E(home.location||'NIGHT CITY')}</small><h3>${E(home.nickname||home.name)}</h3><p>${E(home.name)}</p><div class="cps-estate-stats"><span>HOME LV.<b>${home.homeLevel}</b></span><span>ROOMS<b>${home.rooms.length}</b></span><span>STASH<b>${home.storage.length}/${base.capacity('property',home)}</b></span></div><div class="cps-rpg-actions">${api.buttons(tr('Open Estate','เปิด Estate'),'asset-detail:property:'+home.id,home.status==='sold'?'disabled':'')}${api.buttons(tr('Actions','จัดการ'),'asset-op:property:'+home.id,home.status==='sold'?'disabled':'')}</div></div></article>`;}).join('')||'<div class="cps-asset-empty">NO REGISTERED ESTATES / ยังไม่มีที่พัก</div>'}</div>`;
 }
 function upgradeMarkup(home){
   const foundation=home.homeLevel<1?`<article class="cps-estate-foundation"><small>HOME LEVEL / 00</small><h3>${E(tr('Initialize the residence','เริ่มระบบที่พัก'))}</h3><p>${E(tr('One-time systems setup unlocks every residential module.','ตั้งค่าระบบครั้งเดียวเพื่อปลดล็อกทุกโมดูลของบ้าน'))}</p><form data-op="home-foundation"><strong>€$4,800</strong><button class="cps-button" ${!leaseActive(home)||state().player.balance<4800?'disabled':''}>${E(tr('Initialize LV.1','เริ่ม LV.1'))}</button></form></article>`:'';
   return `<div class="cps-home-page-heading"><small>STRUCTURE / DIRECT CONTROL</small><h2>${E(tr('Home upgrades','อัปเกรดบ้าน'))}</h2></div>${foundation}<div class="cps-upgrade-grid">${['workshop','living','stash','garage','security'].map(area=>{const q=upgradeQuote(home,area);return `<form data-op="home-upgrade"><input type="hidden" name="area" value="${area}"><input type="hidden" name="expectedLevel" value="${q.level}"><small>LV.${q.level} → ${q.next}</small><h3>${E(area.toUpperCase())}</h3><p>${E(q.effect)}</p><strong>€$${q.cost}</strong><p>${E(q.blocked)}</p><button class="cps-button" ${q.blocked?'disabled':''}>${E(tr('Pay & upgrade','จ่ายและอัปเกรด'))}</button></form>`;}).join('')}</div>`;
 }
 function presetPicker(home,room=null,allowNone=false){const current=room||home;return `<div class="cps-banner-presets">${allowNone?`<label class="cps-banner-none ${!current.bannerPreset?'selected':''}"><input type="radio" name="preset" value="" ${!current.bannerPreset?'checked':''}>${svg('rooms')}<span>SVG</span></label>`:''}${presets.map(p=>`<label class="${current.bannerPreset===p.id&&!current.customBanner?'selected':''}" style="--cps-estate-image:url('${E(api.assetUrl?.('assets/properties/'+p.file)||'')}')"><input type="radio" name="preset" value="${p.id}" ${current.bannerPreset===p.id?'checked':''}><span>${String(presets.indexOf(p)+1).padStart(2,'0')}</span></label>`).join('')}</div>`;}
 function openProperty(id){
   const owner=api.chatBucket(),home=homeById(id),d=api.dialog(home.name,'<div class="cps-estate-window"></div>','cps-asset-window cps-estate-dialog'),host=d.querySelector('.cps-estate-window');let page='overview';
   const modules=[['overview','DOSSIER','ข้อมูล'],['storage','STASH','คลัง'],['workshop','WORKSHOP','เวิร์กช็อป'],['upgrades','UPGRADES','อัปเกรด'],['living','LIVING','พักฟื้น'],['garage','GARAGE','โรงรถ'],['rooms','ROOMS','ห้อง'],['history','SERVICE LOG','ประวัติ']];
   const draw=()=>{if(owner!==api.chatBucket()||!d.isConnected)return;const a=homeById(id),s=state(),items=s.player.inventory,storage=a.storage||[],expired=!leaseActive(a);const err='<p data-estate-error role="alert"></p>';
     const contract=a.tenure==='rent'?`<section class="cps-estate-contract ${expired?'expired':''}"><div><small>${expired?'LEASE EXPIRED':'LEASE ACTIVE'}</small><h3>${E(tr(`${leaseRemaining(a)} story turns remaining`,`${leaseRemaining(a)} เทิร์นก่อนหมดสัญญา`))}</h3><p>€$${a.lease.price} / ${a.lease.term} turns · ${E(tr('Buyout','ซื้อถาวร'))} €$${a.lease.buyoutPrice}</p></div><div><form data-op="renew-lease"><button class="cps-button">${E(tr('Renew lease','ต่อสัญญา'))}</button></form><form data-op="buyout"><button class="cps-button">${E(tr('Buy permanently','ซื้อถาวร'))}</button></form></div></section>`:`<section class="cps-estate-contract owned"><div><small>PERMANENT OWNERSHIP</small><h3>${E(tr('No renewal required','ไม่ต้องต่อสัญญา'))}</h3><p>${E(tr('Purchase price','ราคาซื้อ'))} · €$${a.price||0}</p></div></section>`;
     const header=`<div class="cps-home-banner-stage" ${bannerStyle(a)}><div><small>${E(a.location||'NIGHT CITY')} / HOME LV.${a.homeLevel}</small><h2>${E(a.nickname||a.name)}</h2><p>${E(a.name)}</p></div><span>${E(a.tenure==='rent'?(expired?'OFFLINE':'LEASED'):'OWNED')}</span></div><nav class="cps-home-modules">${modules.map(([key,en,th])=>`<button type="button" data-estate-page="${key}" aria-pressed="${page===key}">${svg(key)}<span>${E(tr(en,th))}</span></button>`).join('')}</nav>`;
     let body='';
     if(page==='overview')body=`<div class="cps-home-page-heading"><small>PROPERTY DOSSIER</small><h2>${E(tr('Residence control','ควบคุมที่พัก'))}</h2></div>${contract}<div class="cps-estate-dossier-grid"><form data-op="enter"><h3>${E(tr('Enter residence','เข้าที่พัก'))}</h3><p>${E(a.description||tr('A registered place in Night City.','ที่พักซึ่งลงทะเบียนไว้ใน Night City'))}</p><button class="cps-button" ${expired?'disabled':''}>${E(tr('Enter','เข้า'))}</button></form><form data-op="details"><h3>${E(tr('Dossier details','รายละเอียด'))}</h3><label>${E(tr('Nickname','ชื่อเรียก'))}<input name="nickname" value="${E(a.nickname||'')}" maxlength="100"></label><label>${E(tr('Description','รายละเอียด'))}<textarea name="description" rows="3">${E(a.description||'')}</textarea></label><label>${E(tr('Private notes','บันทึกส่วนตัว'))}<textarea name="notes" rows="3">${E(a.notes||'')}</textarea></label><button class="cps-button">${E(tr('Save details','บันทึก'))}</button></form></div><section class="cps-estate-banner-control"><div class="cps-home-page-heading"><small>16:9 VISUAL ID</small><h3>${E(tr('Banner image','ภาพ Banner'))}</h3></div><form data-op="banner">${presetPicker(a)}<button class="cps-button">${E(tr('Use selected preset','ใช้ภาพที่เลือก'))}</button></form><label class="cps-estate-upload">${E(tr('Choose image from device · PNG/JPEG/WebP under 550 KB','เลือกภาพจากเครื่อง · PNG/JPEG/WebP ไม่เกิน 550 KB'))}<input type="file" accept="image/png,image/jpeg,image/webp" data-custom-banner></label></section>`;
     if(page==='storage')body=`<div class="cps-home-page-heading"><small>STACK MATRIX / ${storage.length} OF ${base.capacity('property',a)}</small><h2>${E(tr('Home stash','คลังบ้าน'))}</h2></div>${['deposit','withdraw'].map(op=>`<form class="cps-estate-service-card" data-op="${op}"><h3>${E(tr(op==='deposit'?'Deposit':'Withdraw',op==='deposit'?'ฝาก':'ถอน'))}</h3><select name="itemId" required><option value="">${E(tr('Choose item','เลือกไอเท็ม'))}</option>${(op==='deposit'?items:storage).map(i=>`<option value="${E(i.id)}">${E(i.name)} ×${i.quantity}${i.equipped?' [equipped]':''}</option>`).join('')}</select><input type="number" name="quantity" min="1" max="9999" value="1" required><button class="cps-button" ${a.homeLevel<1||expired?'disabled':''}>${E(tr(op==='deposit'?'Store item':'Take item',op==='deposit'?'ฝากไอเท็ม':'นำออก'))}</button></form>`).join('')}`;
     if(page==='workshop')body=`<div class="cps-home-page-heading"><small>FABRICATION / LV.${a.upgrades.workshop||0}</small><h2>WORKSHOP</h2></div><div class="cps-craft-grid">${base.recipes.map(r=>`<form data-op="craft"><input type="hidden" name="recipe" value="${r.id}"><small>${r.components} COMPONENTS</small><h3>${E(r.name)}</h3><strong>€$${r.cost}</strong><button class="cps-button" ${(a.upgrades.workshop||0)<1||expired?'disabled':''}>${E(tr('Craft','คราฟต์'))}</button></form>`).join('')}</div><form class="cps-estate-service-card" data-op="upgrade-item"><h3>${E(tr('Upgrade owned equipment','อัปเกรดอุปกรณ์'))}</h3><select name="itemId">${items.filter(i=>['weapons','quickhack'].includes(i.category)).map(i=>`<option value="${E(i.id)}">${E(i.name)} LV.${i.level||1}</option>`).join('')}</select><button class="cps-button" ${(a.upgrades.workshop||0)<1||expired?'disabled':''}>${E(tr('Confirm upgrade','ยืนยันอัปเกรด'))}</button></form>`;
     if(page==='upgrades')body=upgradeMarkup(a);
     if(page==='living')body=`<div class="cps-home-page-heading"><small>RECOVERY SUITE / LV.${a.upgrades.living||0}</small><h2>LIVING</h2></div><div class="cps-estate-recovery"><span>HP<b>+${(a.upgrades.living||0)*10}</b></span><span>STAMINA<b>+${(a.upgrades.living||0)*20}</b></span><span>RAM<b>+${a.upgrades.living||0}</b></span><span>STRESS<b>−${(a.upgrades.living||0)*5}</b></span></div><form class="cps-estate-service-card" data-op="rest"><p>${E(tr('Enter this residence first. Rest is available once per story turn.','เข้าที่พักนี้ก่อน พักได้หนึ่งครั้งต่อเทิร์นเนื้อเรื่อง'))}</p><button class="cps-button" ${(a.upgrades.living||0)<1||expired?'disabled':''}>${E(tr('Rest here','พักฟื้นที่นี่'))}</button></form>`;
     if(page==='garage'){const cars=s.vehicles.filter(v=>v.status!=='sold'&&v.garageId===a.id);body=`<div class="cps-home-page-heading"><small>MOTOR POOL / ${cars.length} OF ${1+(a.upgrades.garage||0)}</small><h2>GARAGE</h2></div>${cars.map(v=>`<article class="cps-estate-room"><div>${svg('garage')}</div><small>${E(v.status||'parked')}</small><h3>${E(v.name)}</h3><p>${v.condition??100}% · ${v.fuel??100}% fuel</p></article>`).join('')||`<p>${E(tr('No vehicles assigned. Assign them from the vehicle dossier.','ยังไม่มีรถประจำโรงรถ กำหนดได้จากรายละเอียดรถ'))}</p>`}`;}
     if(page==='rooms')body=`<div class="cps-home-page-heading"><small>INTERIOR MAP / ${a.rooms.length} LOCATIONS</small><h2>${E(tr('Rooms','ห้องภายใน'))}</h2></div><div class="cps-estate-room-grid">${a.rooms.map(room=>`<article class="cps-estate-room"><div class="cps-estate-room-image" ${room.customBanner||room.bannerPreset?bannerStyle(room):''}>${!room.customBanner&&!room.bannerPreset?svg('rooms'):''}</div><small>${E(room.type||'ROOM')}</small><h3>${E(room.name)}</h3><p>${E(room.description||'')}</p><form data-op="room-banner"><input type="hidden" name="roomId" value="${E(room.id)}">${presetPicker(a,room)}<button class="cps-button">${E(tr('Set room image','ตั้งภาพห้อง'))}</button></form></article>`).join('')}</div><form class="cps-estate-service-card" data-op="add-room"><small>NEW INTERIOR / €$2,500</small><h3>${E(tr('Build another room','สร้างห้องเพิ่ม'))}</h3><label>${E(tr('Room name','ชื่อห้อง'))}<input name="name" maxlength="120" required></label><label>${E(tr('Room type','ประเภทห้อง'))}<input name="type" maxlength="80" value="room"></label><label>${E(tr('Description','รายละเอียด'))}<textarea name="description" rows="3"></textarea></label>${presetPicker(a,null,true)}<button class="cps-button" ${a.homeLevel<1||expired?'disabled':''}>${E(tr('Pay & build room','จ่ายและสร้างห้อง'))}</button></form>`;
     if(page==='history')body=`<div class="cps-home-page-heading"><small>AUDIT TRAIL</small><h2>${E(tr('Service log','ประวัติการใช้งาน'))}</h2></div>${a.serviceLog.slice().reverse().map(v=>`<div class="cps-recovery-row"><span>${E(v.operation)} · ${E(v.detail||'')}<small>${E(new Date(v.at).toLocaleString())}</small></span>${v.cost?`<b>€$${v.cost}</b>`:''}</div>`).join('')||'<p>No records / ยังไม่มีบันทึก</p>'}`;
     host.innerHTML=header+`<section class="cps-estate-page">${body}${err}</section>`;
     host.querySelectorAll('[data-estate-page]').forEach(b=>b.onclick=()=>{page=b.dataset.estatePage;draw();});
     host.querySelectorAll('form').forEach(f=>f.onsubmit=e=>{e.preventDefault();if(owner!==api.chatBucket()||!d.isConnected)return;try{transact('property',id,f.dataset.op,Object.fromEntries(new FormData(f)));draw();api.render?.();}catch(error){host.querySelector('[data-estate-error]').textContent=error.message;}});
     const upload=host.querySelector('[data-custom-banner]');if(upload)upload.onchange=()=>{const file=upload.files?.[0];if(!file)return;const fail=message=>{host.querySelector('[data-estate-error]').textContent=message;upload.value='';};if(file.size>550*1024)return fail(tr('Image exceeds 550 KB','ภาพใหญ่เกิน 550 KB'));if(!['image/png','image/jpeg','image/webp'].includes(file.type))return fail(tr('Unsupported image format','ไม่รองรับไฟล์ภาพนี้'));const reader=new FileReader();reader.onload=()=>{if(owner!==api.chatBucket()||!d.isConnected)return;try{transact('property',id,'custom-banner',{data:reader.result});draw();api.render?.();}catch(error){fail(error.message);}};reader.readAsDataURL(file);};
   };draw();return d;
 }
 return {...base,presets,hydrateProperty:hydrate,syncLeases,upgradeQuote,transact,markup:kind=>kind==='property'?propertyMarkup():base.markup(kind),open:(kind,id)=>kind==='property'?openProperty(id):base.open(kind,id)};
};
globalThis.CyberpunkEstateLayer=true;
})();
